<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento_Productlist_Filter_sProductType'} = 'Product Type';
MLI18n::gi()->{'Magento_Productlist_Filter_sAttributeSet'} = 'Attribute Set';
MLI18n::gi()->{'Magento_Productlist_Filter_aSaleable__all'} = 'Filter (Item is buyable)';
MLI18n::gi()->{'Magento_Productlist_Filter_aSaleable__onlySaleable'} = 'only buyable';
