<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'aGeneralForm__general__headline'} = 'General Settings';
MLI18n::gi()->{'aGeneralForm__general__fields__pass__label'} = 'PassPhrase';
MLI18n::gi()->{'aGeneralForm__general__fields__pass__desc'} = 'You will receive your PassPhrase after Registration at www.magnalister.com. ';
MLI18n::gi()->{'aGeneralForm__sku__headline'} = 'Synchronize Number Ranges';
MLI18n::gi()->{'aGeneralForm__sku__fields__sku__label'} = 'Please Select';
MLI18n::gi()->{'aGeneralForm__sku__fields__sku__desc'} = 'Depending on the selection, either the shop item number or the shop product ID will determine the item number in the marketplace (SKU).<br/><br/>
This setting matches the shop item to the marketplace item, which is necessary for stock management systems to function.<br/><br/>
Please note! The synchronization of stocks and prices is dependent on this setting. Please don\'t change this setting if you have already uploaded items via magnalister. Otherwise, the synchronization won\'t work for older items.';
MLI18n::gi()->{'aGeneralForm__sku__fields__sku__values__pID'} = 'Product ID (Shop) = SKU (Marketplace)';
MLI18n::gi()->{'aGeneralForm__sku__fields__sku__values__artNr'} = 'Item number (Shop) = SKU (Marketplace)';
MLI18n::gi()->{'aGeneralForm__stats__headline'} = 'Statistics';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__label'} = 'Since ';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__desc'} = 'From how long ago should the statistics be shown?';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__0'} = '1 month ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__1'} = '2 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__2'} = '3 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__3'} = '4 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__4'} = '5 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__5'} = '6 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__6'} = '7 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__7'} = '8 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__8'} = '9 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__9'} = '10 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__10'} = '11 months ago';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__11'} = '12 months ago';
MLI18n::gi()->{'aGeneralForm__ftp__headline'} = 'FTP';
MLI18n::gi()->{'aGeneralForm__ftp__fields__host__label'} = 'FTP server';
MLI18n::gi()->{'aGeneralForm__ftp__fields__host__morefields__port__label'} = 'Port';
MLI18n::gi()->{'aGeneralForm__ftp__fields__login__label'} = 'Username';
MLI18n::gi()->{'aGeneralForm__ftp__fields__login__desc'} = 'Please enter your FTP server username';
MLI18n::gi()->{'aGeneralForm__ftp__fields__pswd__label'} = 'Password';
MLI18n::gi()->{'aGeneralForm__ftp__fields__pswd__desc'} = 'Please enter the password for your username';
MLI18n::gi()->{'aGeneralForm__orderimport__headline'} = 'Order Import';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__label'} = 'Order Timetable';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__desc'} = 'Scheduled times for orders to be imported. Presets are included for every hour. <br /><br />This setting does not apply to eBay. Whenever \'Buy\' is clicked on eBay, your Shop will be notified and the order will be imported.';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__0'} = '00:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__1'} = '01:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__2'} = '02:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__3'} = '03:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__4'} = '04:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__5'} = '05:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__6'} = '06:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__7'} = '07:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__8'} = '08:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__9'} = '09:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__10'} = '10:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__11'} = '11:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__12'} = '12:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__13'} = '13:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__14'} = '14:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__15'} = '15:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__16'} = '16:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__17'} = '17:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__18'} = '18:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__19'} = '19:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__20'} = '20:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__21'} = '21:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__22'} = '22:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__23'} = '23:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__orderinformation__label'} = 'Order Information';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__orderinformation__values__val'} = 'Save order number and marketplace name in customer comments.';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__orderinformation__desc'} = 'When this function is activated, the marketplace order number and the marketplace name will be saved in the customer comments after order import.<br />
The customer comments can be transferred to the invoice on many systems, so the customer automatically receives the information about the origin of the order.<br />
This also allows you to provide space for further statistical sales overviews.<br />
<b>Important:</b> Some ERPs do not import orders that have customer comments. Please speak to your ERP provider for any further information.';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__headline'} = 'Miscellaneous';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__label'} = 'Editor';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__desc'} = 'Editor for product descriptions, templates and promotional emails.<br /><br />
<strong>TinyMCE Editor:</strong><br />Use a html editor, ideally one which automatically corrects image paths in product descriptions. <br /><br />
<strong>Basic textfeld, expand local links:</strong><br />Use a basic textfield. This is useful if the TinyMCE editor causes unintended changes to the inserted html code (e.g. in the eBay product template).<br />
Addresses of pictures or links which don\'t start with <strong>http://</strong>,
	                <strong>javascript:</strong>, <strong>mailto:</strong> or <strong>#</strong> will be extended with the shop\'s URL. <br /><br />
<strong>Basic textfeld, migrate data directly:</strong><br />The entered text will not be changed, no addresses will be extended. ';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__values__tinyMCE'} = 'TinyMCE Editor';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__values__none'} = 'Basic textfield, expand local links';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__values__none_none'} = 'Basic textfield, migrate data directly';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__stocksyncbyorder__label'} = 'Synchro Trigger for Orders';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__stocksyncbyorder__desc'} = 'Synchronize the inventory on connected marketplaces immediately, when an order is placed in the shop? This avoids overselling nonexistent stock.<br /><br />
<b>Please note</b>: The synchronization can take a few seconds, slowing down the ordering process.<br />';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__stocksyncbyorder__values__val'} = 'Synchronize the stock as soon as an order is placed.';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__headline'} = 'Inventory';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__fields__statusIsZero__label'} = 'Product Status';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__fields__statusIsZero__desc'} = 'Determine whether an item in your web shop should be marked "<i>inactive</i>", or if the sale on the marketplace has ended (eBay) or become inactive. <br/>
						<br/>
						In order for this function to take effect, please activate the relevant module in your marketplace under<br/>
						"<i>Synchronization of Inventory</i>" > "<i>Stock Sync to Marketplace</i>" ><br/>
						"<i>automatic synchronization with CronJob</i>".<br/>';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__fields__statusIsZero__values__true'} = 'If the product status is inactive, the stock will be set to 0';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__fields__statusIsZero__values__false'} = 'Always use current stock values';
MLI18n::gi()->{'aGeneralForm__productfields__headline'} = 'Product attributes';
MLI18n::gi()->{'aGeneralForm__productfields__fields__manufacturer__label'} = 'Manufacturer';
MLI18n::gi()->{'aGeneralForm__productfields__fields__manufacturer__desc'} = 'Manufacturer<br/><br/>
				           <b>Note:</b> The data will not be reviewed. Incorrect data can cause database problems!';
MLI18n::gi()->{'aGeneralForm__productfields__fields__mfnpartno__label'} = 'Manufacturer Model Number';
MLI18n::gi()->{'aGeneralForm__productfields__fields__mfnpartno__desc'} = 'If you use a Contrib for managing the manufacturer model numbers, please choose here the table and column where the manufacturer model number is saved. This will automatically fill out the field for manufacturer model number. <br/>
If the \'products_id\' column is under a different name, please enter an alternative description for the column with the same meaning in Alias. <br/><br/>
Note: The data will not be reviewed. Incorrect data can cause database problems!';
MLI18n::gi()->{'aGeneralForm__productfields__fields__EAN__label'} = 'EAN';
MLI18n::gi()->{'aGeneralForm__productfields__fields__EAN__desc'} = 'European Article Number<br/><br/>
				           <b>Note:</b> The data will not be reviewed. Incorrect data can cause database problems!';
