<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Tradoria_Productlist_Cell_aPreparedStatus__OK__title'} = 'Tradoria_Productlist_Cell_aPreparedStatus__OK__title';
MLI18n::gi()->{'Tradoria_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Tradoria_Productlist_Cell_aPreparedStatus__ERROR__title';
MLI18n::gi()->{'Tradoria_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Tradoria_Productlist_Cell_aPreparedStatus__OPEN__title';
MLI18n::gi()->{'Tradoria_Productlist_Filter_aPreparedStatus__OK'} = 'Tradoria_Productlist_Filter_aPreparedStatus__OK';
MLI18n::gi()->{'Tradoria_Productlist_Filter_aPreparedStatus__ERROR'} = 'Tradoria_Productlist_Filter_aPreparedStatus__ERROR';
MLI18n::gi()->{'Tradoria_Productlist_Filter_aPreparedStatus__OPEN'} = 'Tradoria_Productlist_Filter_aPreparedStatus__OPEN';
