<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_TEXT_UPDATE_SUCCESS'} = '    A atualização foi realizada com sucesso. Uma lista com as principais alterações pode ser obtida em
    <a href="{#url#}" title="Change-Log">Change-Log</a>.';
MLI18n::gi()->{'ML_TEXT_INSTALL_SUCCESS'} = 'magnalister foi instalado com sucesso.';
MLI18n::gi()->{'sModal_updatePlugin_title'} = 'O plugin do magnalister está sendo atualizado.';
MLI18n::gi()->{'sModal_updatePlugin_content'} = 'Arquivos estão sendo baixados do servidor do magnalister.';
MLI18n::gi()->{'sModal_installPlugin_title'} = 'O plugin do magnalister está sendo instalado.';
MLI18n::gi()->{'sModal_installPlugin_content'} = 'A instalação inicial do magnalister está sendo finalizada.';
MLI18n::gi()->{'sModal_afterUpdatePlugin_content'} = 'A banco de dados está sendo atualizado.';
MLI18n::gi()->{'ML_TEXT_GENERIC_SAFE_MODE'} = 'No seu sistema esta no momento ativado em safe-mode.<br/><br/>
	Para ajuste manual da atualização da  magnalister, Por favor carregue a atual versão da pagina 
	<a href="{#i18n:MAGNA_PUBLIC_SERVER#}" title="magnalister pagina">magnalister pagina</a> Baixar, e copie na pasta 
	<i>dados/</i> do arquivo   na pasta root da loja.Se  você tiver qualquer duvida contate seu administrador e peca a ele que desative o safe-mode para continuar o update da nova versão pelo botão continuar. 
	<br /><br />
	Se você desejar, podemos realizar o update por um pequeno preço de serviço (veja
	<a href="{#i18n:MAGNA_PUBLIC_SERVER#}frontend/installation_pricing.php" title="magnalister Pagina">Lista de preço</a>).';
MLI18n::gi()->{'sException_update_misc'} = 'O plugin do magnalister não pode ser atualizado automaticamente.<br/><br/>
    Para atualizar o magnalister manualmente, baixe a versão atual do <a href="{#setting:sPublicUrl#}" title="Site do magnalister">
    Site do magnalister</a> e copie o diretório <i>files</i> contido no arquivo para o diretório raiz da sua loja.
    Caso deseje, nos podemos realizar esta atualização manual mediante o pagamento de uma taxa (por favor veja
    <a href="{#setting:sPublicUrl#}frontend/installation_pricing.php" title="Site do magnalister">Lista de Preços</a>).
';
MLI18n::gi()->{'sNotUpdateable_title'} = 'A atualização falhou';
MLI18n::gi()->{'ML_ERROR_CANNOT_CONNECT_TO_SERVICE_LAYER_HEADLINE'} = 'Falha na consulta ao <i>Layer</i> de serviços do magnalister';
MLI18n::gi()->{'ML_ERROR_CANNOT_CONNECT_TO_SERVICE_LAYER_TEXT'} = 'O <i>Layer</i> de serviços do magnalister ou não está disponível ou a consulta falhou. Caso o problema persista, por favor contate o nosso suporte ( {#i18n:MAGNA_SUPPORT_URL#}).';
MLI18n::gi()->{'sMagnalisterRemoteServer'} = 'servidor magnalister';
MLI18n::gi()->{'sUpdateError_doAgain'} = '    Clique <a class="global-ajax" data-ml-global-ajax=\'{"triggerAfterSuccess":"currentUrl"}\' onclick="jqml(\'.ml-js-modalPushMessages>*\').remove();jqml(this).parent().hide();return true;" href="{#link#}">aqui</a> para tentar novamente.<br />
    Caso o problema persista, por favor contate o <a href="http://www.magnalister.com/kontakt" class="ml-js-noBlockUi" target="_blank">Serviço magnalister</a>.';
MLI18n::gi()->{'sException_update_notEnoughDiskSpace'} = 'Não há espaço suficiente disponível no disco.';
MLI18n::gi()->{'sException_update_cantCreateFolder'} = 'O diretório "{#path#}" não pode ser criado.';
MLI18n::gi()->{'sException_update_insufficientFilesCount'} = 'Ocorreu um erro durante a criação da lista de atualização.';
MLI18n::gi()->{'sException_update_wrongMethodParameter'} = 'Ocorreu um erro.';
MLI18n::gi()->{'sException_update_pathNotExists'} = 'Sem permissão de escrita no diretório "{#path#}".';
MLI18n::gi()->{'sException_update_pathNotWriteable'} = 'Sem permissão de escrita no diretório "{#path#}".';
MLI18n::gi()->{'sException_update_pathNotReadable'} = 'Não é possível ler do diretório "{#path#}".';
MLI18n::gi()->{'sException_update_cantDeleteFolder'} = 'O diretório "{#path#}" não pode ser removido.';
MLI18n::gi()->{'sException_update_cantCopyFile'} = 'O arquivo "{#srcPath#}" não pode ser copiado para "{#dstPath#}".';
MLI18n::gi()->{'sException_update_cantRenameFolder'} = 'O diretório "{#srcPath#}" não pode ser movido para "{#dstPath#}" por direitos de escrita insuficientes.';
MLI18n::gi()->{'sException_update_cantDeleteFile'} = 'O arquivo "{#path#}" não pode ser deletado.';
MLI18n::gi()->{'sException_update_pathOutsideRoot'} = 'OP caminho "{#path#}" está fora do sistema de arquivos.';


MLI18n::gi()->{'installation_content_title'} = 'magnalister is installing. What\'s next?';
MLI18n::gi()->{'installation_content_freetest_url'} = 'http://www.magnalister.com/en/try-for-free/';
MLI18n::gi()->{'installation_content_firststep'} = 'Save your PassPhrase under Global Configurations (you should have received the PassPhrase via email after registration and activation).';
MLI18n::gi()->{'installation_content_notcutomer'} = 'Not a customer yet?';
MLI18n::gi()->{'installation_content_secondstep'} = 'Choose a marketplace rider to complete the configuration. <a style="pointer-events: none;">Click the info icons in configuration to get useful hints</a>';
MLI18n::gi()->{'installation_content_thirdstep'} = 'Marketplaces have many rules. Contact our support or on-screen help if you encounter problems!';
MLI18n::gi()->{'installation_content_help'} = 'Request help';
MLI18n::gi()->{'installation_content_help_url'} = 'http://www.magnalister.com/en#support';
MLI18n::gi()->{'installation_content_fourthstep'} = 'Start selling on the world’s most important marketplaces! Please enter your PassPhrase';
