<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Check24_CheckinForm__Price'} = 'Check24_CheckinForm__Price';
MLI18n::gi()->{'Check24_CheckinForm__Amount'} = 'Check24_CheckinForm__Amount';
MLI18n::gi()->{'Check24_CheckinForm__ShippingTime'} = 'Shipping time (in days)';
MLI18n::gi()->{'Check24_CheckinForm__ShopPrice'} = 'Check24_CheckinForm__ShopPrice';
MLI18n::gi()->{'Check24_CheckinForm__SuggestedPrice'} = 'Calculated (acc. to Configuration)';
MLI18n::gi()->{'Check24_CheckinForm__HitPrice'} = 'Price Hit';
MLI18n::gi()->{'Check24_CheckinForm__AvailibleAmount'} = 'Available';
MLI18n::gi()->{'Check24_CheckinForm__SuggestedAmount'} = 'Calculated (acc. to Configuration)';
