<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'meinpaket_config_orderimport__field__orderimport.paymentmethod__label'} = 'Forma de pagamento do pedido';
MLI18n::gi()->{'meinpaket_config_orderimport__field__orderimport.paymentmethod__help'} = 'meinpaket_config_orderimport__field__orderimport.paymentmethod__help';
MLI18n::gi()->{'meinpaket_config_orderimport__field__orderimport.paymentmethod__hint'} = '';
MLI18n::gi()->{'meinpaket_config_orderimport__field__orderimport.shippingmethod__label'} = 'meinpaket_config_orderimport__field__orderimport.shippingmethod__label';
MLI18n::gi()->{'meinpaket_config_orderimport__field__orderimport.shippingmethod__help'} = 'meinpaket_config_orderimport__field__orderimport.shippingmethod__help';
MLI18n::gi()->{'meinpaket_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'meinpaket_config_orderimport__field__orderimport.paymentstatus__label'} = 'meinpaket_config_orderimport__field__orderimport.paymentstatus__label';
MLI18n::gi()->{'meinpaket_config_orderimport__field__orderimport.paymentstatus__hint'} = '';
