<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'fyndiq_config_account_title'} = 'Login Details';
MLI18n::gi()->{'fyndiq_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'fyndiq_config_account_price'} = 'Price Calculation';
MLI18n::gi()->{'fyndiq_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'fyndiq_config_account_orderimport'} = 'Order Import';
MLI18n::gi()->{'fyndiq_config_checkin_badshippingcost'} = 'Shipping cost must be a number.';
MLI18n::gi()->{'fyndiq_config_account_emailtemplate'} = 'Promotion Email Template';
MLI18n::gi()->{'fyndiq_config_account_emailtemplate_sender'} = 'Example Shop';
MLI18n::gi()->{'fyndiq_config_account_emailtemplate_sender_email'} = 'example@onlineshop.com';
MLI18n::gi()->{'fyndiq_config_account_emailtemplate_subject'} = 'Your Order from #SHOPURL#';
MLI18n::gi()->{'fyndiq_config_account_producttemplate'} = 'Product Template';
MLI18n::gi()->{'fyndiq_config_account__legend__account'} = 'Login Details';
MLI18n::gi()->{'fyndiq_config_account__legend__tabident'} = '';
MLI18n::gi()->{'fyndiq_config_account__field__tabident__label'} = '{#i18n:ML_LABEL_TAB_IDENT#}';
MLI18n::gi()->{'fyndiq_config_account__field__tabident__help'} = '{#i18n:ML_TEXT_TAB_IDENT#}';
MLI18n::gi()->{'fyndiq_config_account__field__mpusername__label'} = 'Username';
MLI18n::gi()->{'fyndiq_config_account__field__mppassword__label'} = 'Password';
MLI18n::gi()->{'fyndiq_config_account__field__mpapitoken__label'} = 'Authentication token';
MLI18n::gi()->{'fyndiq_config_account__field__mpapitoken__help'} = 'Go to the <a href="https://fyndiq.de/merchant/settings/api/" target="_blank">page</a> and click on create account. After registering your account,
            login and go to Settings -> API. Click the generate API v2 token, which will generate the token in the API-token field. Copy the
            content from the field. The username will be the same username as the merchant account previously registered on the Fyndiq
            merchant pages.';
MLI18n::gi()->{'fyndiq_config_prepare__legend__prepare'} = 'Prepare Items';
MLI18n::gi()->{'fyndiq_config_prepare__legend__upload'} = 'Upload Item: Presets';
MLI18n::gi()->{'fyndiq_config_prepare__field__prepare.status__label'} = 'Status Filter';
MLI18n::gi()->{'fyndiq_config_prepare__field__prepare.status__valuehint'} = 'fyndiq_config_prepare__field__prepare.status__valuehint';
MLI18n::gi()->{'fyndiq_config_prepare__field__lang__label'} = 'Item Description';
MLI18n::gi()->{'fyndiq_config_prepare__field__imagepath__label'} = 'fyndiq_config_prepare__field__imagepath__label';
MLI18n::gi()->{'fyndiq_config_prepare__field__identifier__label'} = 'fyndiq_config_prepare__field__identifier__label';
MLI18n::gi()->{'fyndiq_config_prepare__field__vat__label'} = 'fyndiq_config_prepare__field__vat__label';
MLI18n::gi()->{'fyndiq_config_prepare__field__vat__hint'} = '';
MLI18n::gi()->{'fyndiq_config_prepare__field__vat__matching__titlesrc'} = 'fyndiq_config_prepare__field__vat__matching__titlesrc';
MLI18n::gi()->{'fyndiq_config_prepare__field__vat__matching__titledst'} = 'fyndiq_config_prepare__field__vat__matching__titledst';
MLI18n::gi()->{'fyndiq_config_prepare__field__shippingcost__label'} = 'fyndiq_config_prepare__field__shippingcost__label';
MLI18n::gi()->{'fyndiq_config_prepare__field__checkin.status__label'} = 'Status Filter';
MLI18n::gi()->{'fyndiq_config_prepare__field__checkin.status__valuehint'} = 'fyndiq_config_prepare__field__checkin.status__valuehint';
MLI18n::gi()->{'fyndiq_config_prepare__field__checkin.quantity__label'} = 'fyndiq_config_prepare__field__checkin.quantity__label';
MLI18n::gi()->{'fyndiq_config_prepare__field__checkin.quantity__help'} = 'Please enter how much of the inventory should be available on the marketplace.<br/>
                        <br/>
You can change the individual item count directly under \'Upload\'. In this case it is recommended that you turn off automatic<br/>
synchronization under \'Synchronization of Inventory\' > \'Stock Sync to Marketplace\'.<br/>
                        <br/>
To avoid overselling, you can activate \'Transfer shop inventory minus value from the right field\'.
                        <br/>
<strong>Example:</strong> Setting the value at 2 gives &#8594; Shop inventory: 10 &#8594; Amazon inventory: 8<br/>
                        <br/>
                        <strong>Please note:</strong>If you want to set an inventory count for an item in the Marketplace to \'0\', which is already set as Inactive in the Shop, independent of the actual inventory count, please proceed as follows:<br/>
                        <ul>
                        <li>"Synchronize Inventory"> Set "Edit Shop Inventory" to "Automatic Synchronization with CronJob"</li>
                        <li>"Global Configuration" > "Product Status" > Activate setting "If product status is inactive, treat inventory count as 0"</li>
                        </ul>';
MLI18n::gi()->{'fyndiq_config_prepare__field__customshipping__keytitle'} = 'fyndiq_config_prepare__field__customshipping__keytitle';
MLI18n::gi()->{'fyndiq_config_prepare__field__customshipping__valuetitle'} = 'Shipping costs';
MLI18n::gi()->{'fyndiq_config_prepare__field__imagesize__label'} = 'Image Size';
MLI18n::gi()->{'fyndiq_config_prepare__field__imagesize__help'} = '<p>Please enter the pixel width for the image as should appear on the Marketplace. The height will be automatically matched based on the original aspect ratio.</p>
<p>The source files will be processed from the image folder {#setting:sSourceImagePath#}, and will be stored in the folder {#setting:sImagePath#} with the selected pixel width for use on the Marketplace.</p>';
MLI18n::gi()->{'fyndiq_config_prepare__field__imagesize__hint'} = 'Saved under: {#setting:sImagePath#}';
MLI18n::gi()->{'fyndiq_config_price__legend__price'} = 'Price Calculation';
MLI18n::gi()->{'fyndiq_config_price__field__price__label'} = 'Price';
MLI18n::gi()->{'fyndiq_config_price__field__price__help'} = 'Please enter a price markup or markdown, either in percentage or fixed amount. Use a minus sign (-) before the amount to denote markdown.';
MLI18n::gi()->{'fyndiq_config_price__field__price.addkind__label'} = '';
MLI18n::gi()->{'fyndiq_config_price__field__price.factor__label'} = '';
MLI18n::gi()->{'fyndiq_config_price__field__price.signal__label'} = 'Decimal Amount';
MLI18n::gi()->{'fyndiq_config_price__field__price.signal__hint'} = 'Decimal Amount';
MLI18n::gi()->{'fyndiq_config_price__field__price.signal__help'} = 'fyndiq_config_price__field__price.signal__help';
MLI18n::gi()->{'fyndiq_config_price__field__priceoptions__label'} = 'fyndiq_config_price__field__priceoptions__label';
MLI18n::gi()->{'fyndiq_config_price__field__price.group__label'} = '';
MLI18n::gi()->{'fyndiq_config_price__field__price.usespecialoffer__label'} = 'fyndiq_config_price__field__price.usespecialoffer__label';
MLI18n::gi()->{'fyndiq_config_price__field__exchangerate_update__label'} = 'fyndiq_config_price__field__exchangerate_update__label';
MLI18n::gi()->{'fyndiq_config_price__field__exchangerate_update__valuehint'} = 'fyndiq_config_price__field__exchangerate_update__valuehint';
MLI18n::gi()->{'fyndiq_config_price__field__exchangerate_update__help'} = '{#i18n:form_config_orderimport_exchangerate_update_help#}';
MLI18n::gi()->{'fyndiq_config_price__field__exchangerate_update__alert'} = '{#i18n:form_config_orderimport_exchangerate_update_alert#}';
MLI18n::gi()->{'fyndiq_config_sync__legend__sync'} = 'fyndiq_config_sync__legend__sync';
MLI18n::gi()->{'fyndiq_config_sync__field__stocksync.tomarketplace__label'} = 'fyndiq_config_sync__field__stocksync.tomarketplace__label';
MLI18n::gi()->{'fyndiq_config_sync__field__stocksync.tomarketplace__help'} = 'fyndiq_config_sync__field__stocksync.tomarketplace__help';
MLI18n::gi()->{'fyndiq_config_sync__field__stocksync.frommarketplace__label'} = 'fyndiq_config_sync__field__stocksync.frommarketplace__label';
MLI18n::gi()->{'fyndiq_config_sync__field__stocksync.frommarketplace__help'} = 'fyndiq_config_sync__field__stocksync.frommarketplace__help';
MLI18n::gi()->{'fyndiq_config_sync__field__inventorysync.price__label'} = 'fyndiq_config_sync__field__inventorysync.price__label';
MLI18n::gi()->{'fyndiq_config_sync__field__inventorysync.price__help'} = 'fyndiq_config_sync__field__inventorysync.price__help';
MLI18n::gi()->{'fyndiq_config_orderimport__legend__importactive'} = 'fyndiq_config_orderimport__legend__importactive';
MLI18n::gi()->{'fyndiq_config_orderimport__legend__mwst'} = 'fyndiq_config_orderimport__legend__mwst';
MLI18n::gi()->{'fyndiq_config_orderimport__legend__orderstatus'} = 'fyndiq_config_orderimport__legend__orderstatus';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderstatus.sync__label'} = 'fyndiq_config_orderimport__field__orderstatus.sync__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderstatus.sync__help'} = 'fyndiq_config_orderimport__field__orderstatus.sync__help';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderimport.shop__label'} = '{#i18n:form_config_orderimport_shop_lable#}';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderimport.shop__hint'} = '';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderimport.shop__help'} = '{#i18n:form_config_orderimport_shop_help#}';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderstatus.shipped__label'} = 'fyndiq_config_orderimport__field__orderstatus.shipped__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderstatus.shipped__help'} = 'fyndiq_config_orderimport__field__orderstatus.shipped__help';
MLI18n::gi()->{'fyndiq_config_orderimport__field__service__label'} = 'fyndiq_config_orderimport__field__service__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__service__help'} = 'fyndiq_config_orderimport__field__service__help';
MLI18n::gi()->{'fyndiq_config_orderimport__field__mwst.fallback__label'} = 'fyndiq_config_orderimport__field__mwst.fallback__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__mwst.fallback__hint'} = 'fyndiq_config_orderimport__field__mwst.fallback__hint';
MLI18n::gi()->{'fyndiq_config_orderimport__field__mwst.fallback__help'} = 'fyndiq_config_orderimport__field__mwst.fallback__help';
MLI18n::gi()->{'fyndiq_config_orderimport__field__importactive__label'} = 'fyndiq_config_orderimport__field__importactive__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__importactive__hint'} = '';
MLI18n::gi()->{'fyndiq_config_orderimport__field__importactive__help'} = 'fyndiq_config_orderimport__field__importactive__help';
MLI18n::gi()->{'fyndiq_config_orderimport__field__import__label'} = '';
MLI18n::gi()->{'fyndiq_config_orderimport__field__preimport.start__label'} = 'fyndiq_config_orderimport__field__preimport.start__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__preimport.start__hint'} = 'fyndiq_config_orderimport__field__preimport.start__hint';
MLI18n::gi()->{'fyndiq_config_orderimport__field__preimport.start__help'} = 'fyndiq_config_orderimport__field__preimport.start__help';
MLI18n::gi()->{'fyndiq_config_orderimport__field__customergroup__label'} = 'fyndiq_config_orderimport__field__customergroup__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__customergroup__help'} = 'fyndiq_config_orderimport__field__customergroup__help';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderstatus.open__label'} = 'fyndiq_config_orderimport__field__orderstatus.open__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__orderstatus.open__help'} = 'fyndiq_config_orderimport__field__orderstatus.open__help';
