<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameFyndiq'} = 'Fyndiq';
MLI18n::gi()->{'ML_FYNDIQ_TEXT_NO_MATCHED_PRODUCTS'} = 'No items have been prepared for Fyndiq yet. You can prepare items by selecting the "Product Matching" tab.<br>
If you miss some products you already have prepared, please check whether the products have active status, and if not, whether the configuration allows to upload inactive iems.';
MLI18n::gi()->{'fyndiq_upload_explanation'} = 'Uploaded items are usually placed within one hour on Fyndiq. After that, you can see items on your Fyndiq management page.';
MLI18n::gi()->{'fyndiq_pre_upload_popup'} = 'fyndiq_pre_upload_popup';
