<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_prepare_form__field__title__label'} = 'ebay_prepare_form__field__title__label';
MLI18n::gi()->{'ebay_prepare_form__field__title__hint'} = 'ebay_prepare_form__field__title__hint';
MLI18n::gi()->{'ebay_prepare_form__field__title__optional__checkbox__labelNegativ'} = 'ebay_prepare_form__field__title__optional__checkbox__labelNegativ';
