<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEbay'} = 'eBay';
MLI18n::gi()->{'sEbayNoInternationalShipping'} = 'sEbayNoInternationalShipping';
MLI18n::gi()->{'sEbayProductIdentifierSyncButton'} = 'sEbayProductIdentifierSyncButton';
MLI18n::gi()->{'sEbaySyncButtonDisableIfno'} = 'sEbaySyncButtonDisableIfno';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_ITEMS'} = 'Synchronisation des prix et des stocks:';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_PRODUCTDETAILUPDATES'} = 'Attributs requis par eBay :';
MLI18n::gi()->{'ML_EBAY_PLUS_ORDER'} = 'ML_EBAY_PLUS_ORDER';
MLI18n::gi()->{'ML_TEXT_WARNING'} = 'ML_TEXT_WARNING';
MLI18n::gi()->{'ML_EBAY_PLUS_ORDER_WRONG_SHIPPING'} = 'ML_EBAY_PLUS_ORDER_WRONG_SHIPPING';
