<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Ebay_listings_popup_after_addItem_content'} = 'Ebay_listings_popup_after_addItem_content';
MLI18n::gi()->{'Ebay_listings_status__pending'} = 'Ebay_listings_status__pending';
MLI18n::gi()->{'Ebay_listings_status__active'} = 'Ebay_listings_status__active';
MLI18n::gi()->{'Ebay_listings_status__pending_process'} = 'Ebay_listings_status__pending_process';
