<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameFyndiq'} = 'Fyndiq';
MLI18n::gi()->{'ML_FYNDIQ_TEXT_NO_MATCHED_PRODUCTS'} = 'ML_FYNDIQ_TEXT_NO_MATCHED_PRODUCTS';
MLI18n::gi()->{'fyndiq_upload_explanation'} = 'fyndiq_upload_explanation';
MLI18n::gi()->{'fyndiq_pre_upload_popup'} = 'fyndiq_pre_upload_popup';
