<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_config_account_title'} = 'Login Details';
MLI18n::gi()->{'hitmeister_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'hitmeister_config_account_price'} = 'Price Calculation';
MLI18n::gi()->{'hitmeister_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'hitmeister_config_account_orderimport'} = 'Order Import';
MLI18n::gi()->{'hitmeister_config_checkin_badshippingcost'} = 'Shipping cost must be a number.';
MLI18n::gi()->{'hitmeister_config_checkin_shippingmatching'} = 'hitmeister_config_checkin_shippingmatching';
MLI18n::gi()->{'hitmeister_config_checkin_manufacturerfilter'} = 'hitmeister_config_checkin_manufacturerfilter';
MLI18n::gi()->{'hitmeister_config_account__legend__account'} = 'Login Details';
MLI18n::gi()->{'hitmeister_config_account__legend__tabident'} = '';
MLI18n::gi()->{'hitmeister_config_account__field__tabident__label'} = '{#i18n:ML_LABEL_TAB_IDENT#}';
MLI18n::gi()->{'hitmeister_config_account__field__tabident__help'} = '{#i18n:ML_TEXT_TAB_IDENT#}';
MLI18n::gi()->{'hitmeister_config_account__field__clientkey__label'} = 'ClientKey';
MLI18n::gi()->{'hitmeister_config_account__field__clientkey__help'} = 'hitmeister_config_account__field__clientkey__help';
MLI18n::gi()->{'hitmeister_config_account__field__secretkey__label'} = 'SecretKey';
MLI18n::gi()->{'hitmeister_config_account__field__mpusername__label'} = 'Username';
MLI18n::gi()->{'hitmeister_config_account__field__mppassword__label'} = 'Password';
MLI18n::gi()->{'hitmeister_config_prepare__legend__prepare'} = 'Prepare Items';
MLI18n::gi()->{'hitmeister_config_prepare__legend__upload'} = 'Upload Item: Presets';
MLI18n::gi()->{'hitmeister_config_prepare__field__prepare.status__label'} = 'Status Filter';
MLI18n::gi()->{'hitmeister_config_prepare__field__prepare.status__valuehint'} = 'Only transfer active items';
MLI18n::gi()->{'hitmeister_config_prepare__field__checkin.status__label'} = 'Status Filter';
MLI18n::gi()->{'hitmeister_config_prepare__field__checkin.status__valuehint'} = 'Only transfer active items';
MLI18n::gi()->{'hitmeister_config_prepare__field__lang__label'} = 'Item Description';
MLI18n::gi()->{'hitmeister_config_prepare__field__imagepath__label'} = 'Image Path';
MLI18n::gi()->{'hitmeister_config_prepare__field__itemcondition__label'} = 'Item Condition';
MLI18n::gi()->{'hitmeister_config_prepare__field__shippingtime__label'} = 'Shippingtime';
MLI18n::gi()->{'hitmeister_config_prepare__field__shippingtime__help'} = 'hitmeister_config_prepare__field__shippingtime__help';
MLI18n::gi()->{'hitmeister_config_prepare__field__shippingtimematchingsub__label'} = 'hitmeister_config_prepare__field__shippingtimematchingsub__label';
MLI18n::gi()->{'hitmeister_config_prepare__field__shippingtimematching__label'} = '';
MLI18n::gi()->{'hitmeister_config_prepare__field__shippingtimematching__matching__titlesrc'} = 'hitmeister_config_prepare__field__shippingtimematching__matching__titlesrc';
MLI18n::gi()->{'hitmeister_config_prepare__field__shippingtimematching__matching__titledst'} = 'hitmeister_config_prepare__field__shippingtimematching__matching__titledst';
MLI18n::gi()->{'hitmeister_config_prepare__field__shippingtimematching.prefer__label'} = '';
MLI18n::gi()->{'hitmeister_config_prepare__field__shippingtimematching.prefer__valuehint'} = 'hitmeister_config_prepare__field__shippingtimematching.prefer__valuehint';
MLI18n::gi()->{'hitmeister_config_prepare__field__itemcountry__label'} = 'hitmeister_config_prepare__field__itemcountry__label';
MLI18n::gi()->{'hitmeister_config_prepare__field__itemcountry__help'} = 'hitmeister_config_prepare__field__itemcountry__help';
MLI18n::gi()->{'hitmeister_config_prepare__field__itemsperpage__label'} = 'Results';
MLI18n::gi()->{'hitmeister_config_prepare__field__itemsperpage__help'} = 'hitmeister_config_prepare__field__itemsperpage__help';
MLI18n::gi()->{'hitmeister_config_prepare__field__itemsperpage__hint'} = 'per page of multimatching';
MLI18n::gi()->{'hitmeister_config_prepare__field__checkin.quantity__label'} = 'Inventory Item Count';
MLI18n::gi()->{'hitmeister_config_prepare__field__checkin.quantity__help'} = 'Please enter how much of the inventory should be available on the marketplace.<br/>
                        <br/>
You can change the individual item count directly under \'Upload\'. In this case it is recommended that you turn off automatic<br/>
synchronization under \'Synchronization of Inventory\' > \'Stock Sync to Marketplace\'.<br/>
                        <br/>
To avoid overselling, you can activate \'Transfer shop inventory minus value from the right field\'.
                        <br/>
<strong>Example:</strong> Setting the value at 2 gives &#8594; Shop inventory: 10 &#8594; Amazon inventory: 8<br/>
                        <br/>
                        <strong>Please note:</strong>If you want to set an inventory count for an item in the Marketplace to \'0\', which is already set as Inactive in the Shop, independent of the actual inventory count, please proceed as follows:<br/>
                        <ul>
                        <li>\'Synchronize Inventory"> Set "Edit Shop Inventory" to "Automatic Synchronization with CronJob"</li>
                        <li>"Global Configuration" > "Product Status" > Activate setting "If product status is inactive, treat inventory count as 0"</li>
                        </ul>';
MLI18n::gi()->{'hitmeister_config_price__legend__price'} = 'Price Calculation';
MLI18n::gi()->{'hitmeister_config_price__field__price__label'} = 'Price';
MLI18n::gi()->{'hitmeister_config_price__field__price__help'} = 'Please enter a price markup or markdown, either in percentage or fixed amount. Use a minus sign (-) before the amount to denote markdown.';
MLI18n::gi()->{'hitmeister_config_price__field__price.addkind__label'} = '';
MLI18n::gi()->{'hitmeister_config_price__field__price.factor__label'} = '';
MLI18n::gi()->{'hitmeister_config_price__field__price.signal__label'} = 'Decimal Amount';
MLI18n::gi()->{'hitmeister_config_price__field__price.signal__hint'} = 'Decimal Amount';
MLI18n::gi()->{'hitmeister_config_price__field__price.signal__help'} = 'This textfield shows the decimal value that will appear in the item price on Hitmeister.<br/><br/>
                <strong>Example:</strong> <br />
Value in textfeld: 99 <br />
                Original price: 5.58 <br />
                Final amount: 5.99 <br /><br />
This function is useful when marking the price up or down***. <br/>
Leave this field empty if you do not wish to set any decimal amount. <br/>
The format requires a maximum of 2 numbers.';
MLI18n::gi()->{'hitmeister_config_price__field__priceoptions__label'} = 'Price Calculation';
MLI18n::gi()->{'hitmeister_config_price__field__priceoptions__help'} = '{#i18n:configform_price_field_priceoptions_help#}';
MLI18n::gi()->{'hitmeister_config_price__field__price.group__label'} = '';
MLI18n::gi()->{'hitmeister_config_price__field__price.usespecialoffer__label'} = 'Use special offer prices';
MLI18n::gi()->{'hitmeister_config_price__field__exchangerate_update__label'} = 'Exchange Rate';
MLI18n::gi()->{'hitmeister_config_price__field__exchangerate_update__valuehint'} = 'Automatically update exchange rate';
MLI18n::gi()->{'hitmeister_config_price__field__exchangerate_update__help'} = '{#i18n:form_config_orderimport_exchangerate_update_help#}';
MLI18n::gi()->{'hitmeister_config_price__field__exchangerate_update__alert'} = '{#i18n:form_config_orderimport_exchangerate_update_alert#}';
MLI18n::gi()->{'hitmeister_config_sync__legend__sync'} = 'Inventory Synchronization';
MLI18n::gi()->{'hitmeister_config_sync__field__stocksync.tomarketplace__label'} = 'Stock Sync to Marketplace';
MLI18n::gi()->{'hitmeister_config_sync__field__stocksync.tomarketplace__help'} = 'hitmeister_config_sync__field__stocksync.tomarketplace__help';
MLI18n::gi()->{'hitmeister_config_sync__field__stocksync.frommarketplace__label'} = 'Stock Sync to Marketplace';
MLI18n::gi()->{'hitmeister_config_sync__field__stocksync.frommarketplace__help'} = 'hitmeister_config_sync__field__stocksync.frommarketplace__help';
MLI18n::gi()->{'hitmeister_config_sync__field__inventorysync.price__label'} = 'Item Price';
MLI18n::gi()->{'hitmeister_config_sync__field__inventorysync.price__help'} = 'hitmeister_config_sync__field__inventorysync.price__help';
MLI18n::gi()->{'hitmeister_config_orderimport__legend__importactive'} = 'Order Import';
MLI18n::gi()->{'hitmeister_config_orderimport__legend__mwst'} = 'VAT';
MLI18n::gi()->{'hitmeister_config_orderimport__legend__orderstatus'} = 'Order Status Synchronization Between Shop and Hitmeister';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.sync__label'} = 'Status Synchronization';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.sync__help'} = 'hitmeister_config_orderimport__field__orderstatus.sync__help';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderimport.shop__label'} = '{#i18n:form_config_orderimport_shop_lable#}';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderimport.shop__hint'} = '';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderimport.shop__help'} = '{#i18n:form_config_orderimport_shop_help#}';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.shipped__label'} = 'Confirm Shipping With';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.shipped__help'} = 'hitmeister_config_orderimport__field__orderstatus.shipped__help';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.cancelled__label'} = 'Cancel Order With';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.cancelled__help'} = 'hitmeister_config_orderimport__field__orderstatus.cancelled__help';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.carrier__label'} = 'hitmeister_config_orderimport__field__orderstatus.carrier__label';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.carrier__help'} = 'hitmeister_config_orderimport__field__orderstatus.carrier__help';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.cancelreason__label'} = 'Canceling order reason';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.cancelreason__help'} = 'Reason for canceling order.';
MLI18n::gi()->{'hitmeister_config_orderimport__field__mwst.fallback__label'} = 'VAT on Non-Shop*** Items';
MLI18n::gi()->{'hitmeister_config_orderimport__field__mwst.fallback__hint'} = 'The tax rate to apply to non-Shop items on order imports, in %.';
MLI18n::gi()->{'hitmeister_config_orderimport__field__mwst.fallback__help'} = 'hitmeister_config_orderimport__field__mwst.fallback__help';
MLI18n::gi()->{'hitmeister_config_orderimport__field__importactive__label'} = 'Active Import';
MLI18n::gi()->{'hitmeister_config_orderimport__field__importactive__hint'} = '';
MLI18n::gi()->{'hitmeister_config_orderimport__field__importactive__help'} = 'hitmeister_config_orderimport__field__importactive__help';
MLI18n::gi()->{'hitmeister_config_orderimport__field__import__label'} = '';
MLI18n::gi()->{'hitmeister_config_orderimport__field__preimport.start__label'} = 'hitmeister_config_orderimport__field__preimport.start__label';
MLI18n::gi()->{'hitmeister_config_orderimport__field__preimport.start__hint'} = 'Start Date';
MLI18n::gi()->{'hitmeister_config_orderimport__field__preimport.start__help'} = 'The date from which orders will start being imported. Please note that it is not possible to set this too far in the past, as the data only remains available on Hitmeister for a few weeks.***';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.open__label'} = 'Order Status in Shop';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.open__hint'} = '';
MLI18n::gi()->{'hitmeister_config_orderimport__field__orderstatus.open__help'} = 'hitmeister_config_orderimport__field__orderstatus.open__help';
MLI18n::gi()->{'hitmeister_config_orderimport__field__customergroup__label'} = 'Customer Group';
MLI18n::gi()->{'hitmeister_config_orderimport__field__customergroup__help'} = 'The customer group that customers from new orders should be sorted into.';
