<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Hitmeister_Label_sAutoMatchSuccess'} = 'Hitmeister_Label_sAutoMatchSuccess';
MLI18n::gi()->{'HITMEISTER_BUTTON_LABEL_DELETE_COMPLETE_LOG'} = 'Gesamtes Log löschen';
MLI18n::gi()->{'hitmeister_prepare_apply'} = 'hitmeister_prepare_apply';
