<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameCdiscount'} = 'sModuleNameCdiscount';
MLI18n::gi()->{'cdiscount_label_title'} = 'cdiscount_label_title';
MLI18n::gi()->{'cdiscount_category'} = 'cdiscount_category';
MLI18n::gi()->{'cdiscount_label_item_id'} = 'cdiscount_label_item_id';
MLI18n::gi()->{'cdiscount_search_by_title'} = 'cdiscount_search_by_title';
MLI18n::gi()->{'cdiscount_search_by_ean'} = 'cdiscount_search_by_ean';
MLI18n::gi()->{'cdiscount_label_not_matched'} = 'cdiscount_label_not_matched';
MLI18n::gi()->{'cdiscount_upload_explanation'} = 'cdiscount_upload_explanation';
