<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Cdiscount_Label_sAutoMatchSuccess'} = 'Cdiscount_Label_sAutoMatchSuccess';
MLI18n::gi()->{'CDISCOUNT_BUTTON_LABEL_DELETE_COMPLETE_LOG'} = 'CDISCOUNT_BUTTON_LABEL_DELETE_COMPLETE_LOG';
MLI18n::gi()->{'cdiscount_prepare_apply'} = 'cdiscount_prepare_apply';
