<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Shopware_Productlist_Filter_sStatus'} = 'Situação';
MLI18n::gi()->{'Shopware_Productlist_Filter_sActive'} = 'ativo';
MLI18n::gi()->{'Shopware_Productlist_Filter_sInactive'} = 'inativo';
MLI18n::gi()->{'Shopware_Productlist_Filter_sManufacturer'} = 'Fabricante';
MLI18n::gi()->{'Shopware_Productlist_Filter_sManufacturerId'} = 'Número do fabricante';
MLI18n::gi()->{'Shopware_Productlist_Filter_sEan'} = 'EAN';
MLI18n::gi()->{'Shopware_Productlist_Filter_sCategory'} = 'Categoria';
