<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_type_optional_select__true'} = 'Apply';
MLI18n::gi()->{'form_type_optional_select__false'} = 'Don\'t apply';
MLI18n::gi()->{'form_type_matching_select_optional'} = 'form_type_matching_select_optional';
MLI18n::gi()->{'form_type_matching_select_all'} = 'form_type_matching_select_all';
MLI18n::gi()->{'form_type_matching_select_reset'} = 'form_type_matching_select_reset';
MLI18n::gi()->{'form_type_matching_select_manual'} = 'form_type_matching_select_manual';
MLI18n::gi()->{'form_type_matching_select_auto'} = 'form_type_matching_select_auto';
MLI18n::gi()->{'form_type_duplicate_radiogroup'} = 'form_type_duplicate_radiogroup';
MLI18n::gi()->{'form_type_matching_optional'} = 'Do not transfer';
MLI18n::gi()->{'form_text_addon_error'} = 'form_text_addon_error';
MLI18n::gi()->{'form_text_addon_success'} = 'form_text_addon_success';
MLI18n::gi()->{'form_action_default_legend'} = 'Actions';
MLI18n::gi()->{'form_action_prepare'} = 'Save';
MLI18n::gi()->{'form_action_unprepare'} = 'Cancel prepare';
MLI18n::gi()->{'form_action_save'} = 'Save';
MLI18n::gi()->{'form_action_wizard_save'} = 'Continue with "%s"';
MLI18n::gi()->{'form_action_finish_wizard_save'} = 'Finish and save';
MLI18n::gi()->{'form_action_expert'} = 'Expert settings';
MLI18n::gi()->{'form_action_reset'} = 'Reset';
MLI18n::gi()->{'form_text_choose'} = 'Choose';
