<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_config_orderimport_shop_lable'} = 'Shop Client***';
MLI18n::gi()->{'form_config_orderimport_shop_help'} = 'Determine which Client Shop orders should be sorted into.***';
MLI18n::gi()->{'form_config_orderimport_imagesize_lable'} = 'Image size';
MLI18n::gi()->{'form_config_orderimport_imagesize_help'} = '<p>Please enter the pixel width for the image as should appear on the Marketplace. The height will be automatically matched based on the original aspect ratio.</p>
<p>The source files will be processed from the image folder {#setting:sSourceImagePath#}, and will be stored in the folder {#setting:sImagePath#} with the selected pixel width for use on the Marketplace.</p>';
MLI18n::gi()->{'form_config_orderimport_imagesize_hint'} = 'Saved under: {#setting:sImagePath#}';
MLI18n::gi()->{'form_config_send_mailcontentcontailner_testmail'} = 'TESTMAIL';
