<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento_Global_Configuration_Label'} = 'Unidade de Peso';
MLI18n::gi()->{'Magento_Global_Configuration_Description'} = 'Unidade de Peso';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_help'} = 'form_config_orderimport_exchangerate_update_help';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_alert'} = 'form_config_orderimport_exchangerate_update_alert';
MLI18n::gi()->{'magentospecific_aGeneralForm__orderimport__fields__orderinformation__values__val'} = 'magentospecific_aGeneralForm__orderimport__fields__orderinformation__values__val';
MLI18n::gi()->{'magentospecific_aGeneralForm__orderimport__fields__orderinformation__desc'} = 'magentospecific_aGeneralForm__orderimport__fields__orderinformation__desc';
