<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento_Productlist_Filter_sProductType'} = 'Tipo de Produto';
MLI18n::gi()->{'Magento_Productlist_Filter_sAttributeSet'} = 'Set de Atributos';
MLI18n::gi()->{'Magento_Productlist_Filter_aSaleable__all'} = 'Filtro (itens compráveis)';
MLI18n::gi()->{'Magento_Productlist_Filter_aSaleable__onlySaleable'} = 'apenas compráveis';
