<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_type_optional_select__true'} = 'Utilizar';
MLI18n::gi()->{'form_type_optional_select__false'} = 'Não utilizar';
MLI18n::gi()->{'form_type_matching_optional'} = 'Não enviar';
MLI18n::gi()->{'form_text_addon_error'} = 'form_text_addon_error';
MLI18n::gi()->{'form_text_addon_success'} = 'form_text_addon_success';
MLI18n::gi()->{'form_action_default_legend'} = 'Ações';
MLI18n::gi()->{'form_action_prepare'} = 'Salvar dados';
MLI18n::gi()->{'form_action_unprepare'} = 'Cancelar preparação';
MLI18n::gi()->{'form_action_save'} = 'Salvar dados';
MLI18n::gi()->{'form_action_wizard_save'} = 'Continuar para "%s"';
MLI18n::gi()->{'form_action_finish_wizard_save'} = 'Terminar';
MLI18n::gi()->{'form_action_expert'} = 'Configurações Avançadas';
MLI18n::gi()->{'form_action_reset'} = 'Resetar';
MLI18n::gi()->{'form_text_choose'} = 'Selecionar';
