<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_config_orderimport_shop_lable'} = 'form_config_orderimport_shop_lable';
MLI18n::gi()->{'form_config_orderimport_shop_help'} = 'form_config_orderimport_shop_help';
MLI18n::gi()->{'form_config_orderimport_imagesize_lable'} = 'form_config_orderimport_imagesize_lable';
MLI18n::gi()->{'form_config_orderimport_imagesize_help'} = 'form_config_orderimport_imagesize_help';
MLI18n::gi()->{'form_config_orderimport_imagesize_hint'} = 'form_config_orderimport_imagesize_hint';
MLI18n::gi()->{'form_config_send_mailcontentcontailner_testmail'} = 'form_config_send_mailcontentcontailner_testmail';
