<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEbay'} = 'sModuleNameEbay';
MLI18n::gi()->{'sEbayNoInternationalShipping'} = 'sEbayNoInternationalShipping';
MLI18n::gi()->{'sEbayProductIdentifierSyncButton'} = 'sEbayProductIdentifierSyncButton';
MLI18n::gi()->{'sEbaySyncButtonDisableIfno'} = 'sEbaySyncButtonDisableIfno';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_ITEMS'} = 'ML_EBAY_N_PENDING_UPDATES_TITLE_ITEMS';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_PRODUCTDETAILUPDATES'} = 'ML_EBAY_N_PENDING_UPDATES_TITLE_PRODUCTDETAILUPDATES';
MLI18n::gi()->ML_EBAY_PLUS_ORDER = 'ML_EBAY_PLUS_ORDER';
MLI18n::gi()->ML_TEXT_WARNING = 'ML_TEXT_WARNING';
MLI18n::gi()->ML_EBAY_PLUS_ORDER_WRONG_SHIPPING = 'ML_EBAY_PLUS_ORDER_WRONG_SHIPPING';
