<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'check24_config_orderimport__field__paymentstatus__label'} = 'Situação do pagamento na loja';
MLI18n::gi()->{'check24_config_orderimport__field__paymentstatus__hint'} = '';
