<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'aGeneralForm__general__headline'} = 'Paramètres généraux';
MLI18n::gi()->{'aGeneralForm__general__fields__pass__label'} = 'PassPhrase';
MLI18n::gi()->{'aGeneralForm__general__fields__pass__desc'} = 'Vous recevrez la PassPhrase après votre inscription sur le site www.magnalister.com.';
MLI18n::gi()->{'aGeneralForm__sku__headline'} = 'Synchronisation du référencement';
MLI18n::gi()->{'aGeneralForm__sku__fields__sku__label'} = 'Liste de choix';
MLI18n::gi()->{'aGeneralForm__sku__fields__sku__desc'} = 'Lorsque vous enregistrez un nouveau produit, magnalister lui attribue automatiquement un numéro de référence: le <strong>numéro ID</strong>. Sous la rubrique &laquo; <strong>référence</strong> &raquo;, vous pouvez aussi attribuer vos propres références à vos produits. <br/><br/>

Selon votre choix, le numéro de <strong>votre référence</strong> ou le <strong>numéro ID</strong>, sera utilisé comme <strong>numéro SKU</strong> sur la place de marché, afin de pouvoir classer le produit lors de la synchronisation des stocks et des commandes.<br/><br/>

Cette fonction est  particulièrement importante pour la gestion des marchandises, car elle permet la comparaison des inventaires entre la boutique en ligne et la place de marché.<br/><br/>

<strong>Attention!</strong> La synchronisation des quantités en stock et de leurs prix dépend de ce paramètre. Si vous avez déjà téléchargé des articles, vous ne devez <strong>plus modifier<strong> ce paramètre, dans le cas contraire, <strong>les articles précédemment</strong> enregistrés ne seraient plus synchronisés.';
MLI18n::gi()->{'aGeneralForm__sku__fields__sku__values__pID'} = 'Numéro ID (de votre boutique) = SKU (Place de marché)';
MLI18n::gi()->{'aGeneralForm__sku__fields__sku__values__artNr'} = 'Numéro de votre référence (de votre boutique) = SKU (place de marché)';
MLI18n::gi()->{'aGeneralForm__stats__headline'} = 'Statistiques';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__label'} = 'Mode de journalisation';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__desc'} = 'Combien de mois doivent restituer la statistique ?';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__0'} = '1 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__1'} = '2 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__2'} = '3 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__3'} = '4 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__4'} = '5 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__5'} = '6 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__6'} = '7 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__7'} = '8 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__8'} = '9 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__9'} = '10 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__10'} = '11 mois';
MLI18n::gi()->{'aGeneralForm__stats__fields__back__values__11'} = '12 mois';
MLI18n::gi()->{'aGeneralForm__ftp__headline'} = 'FTP';
MLI18n::gi()->{'aGeneralForm__ftp__fields__host__label'} = 'Serveur FTP';
MLI18n::gi()->{'aGeneralForm__ftp__fields__host__morefields__port__label'} = 'Port';
MLI18n::gi()->{'aGeneralForm__ftp__fields__login__label'} = 'Nom d\'utilisateur';
MLI18n::gi()->{'aGeneralForm__ftp__fields__login__desc'} = 'Veuillez spécifier le nom d\'utilisateur pour votre serveur FTP.';
MLI18n::gi()->{'aGeneralForm__ftp__fields__pswd__label'} = 'Mot de passe';
MLI18n::gi()->{'aGeneralForm__ftp__fields__pswd__desc'} = 'Veuillez entrer le mot de passe pour le nom d\'utilisateur.';
MLI18n::gi()->{'aGeneralForm__orderimport__headline'} = 'Importation des commandes';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__label'} = 'Choix d\'horaire d\'importation';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__desc'} = 'Avec cette fonctionnalité, vous pouvez choisir les heures auxquelles vous souhaitez être informés des commandes. Le préréglage est horaire. <br/> <br/>

Important: eBay ne prend pas en compte cette fonctionnalité. eBay vous informe systématiquement à chaque achat et vous transmet immédiatement la commande. ';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__0'} = '00:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__1'} = '01:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__2'} = '02:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__3'} = '03:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__4'} = '04:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__5'} = '05:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__6'} = '06:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__7'} = '07:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__8'} = '08:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__9'} = '09:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__10'} = '10:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__11'} = '11:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__12'} = '12:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__13'} = '13:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__14'} = '14:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__15'} = '15:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__16'} = '16:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__17'} = '17:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__18'} = '18:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__19'} = '19:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__20'} = '20:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__21'} = '21:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__22'} = '22:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__timetable__values__23'} = '23:00';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__orderinformation__label'} = 'Information sur la commande';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__orderinformation__values__val'} = 'Enregistrez le numéro de la commande et le nom de la place de marché dans les commentaires clients.';
MLI18n::gi()->{'aGeneralForm__orderimport__fields__orderinformation__desc'} = 'Si vous activez la fonctionnalité, le numéro de la commande et le nom de la place de marché seront enregistrés dans les commentaires du client, à l\'importation des commandes.<br/>
Cette fonction est prise en charge par la plupart des programmes de boutique en ligne. Elle dépend donc de la programmation de votre boutique en ligne. 
Ces commentaires peuvent apparaître sur la facture de sorte que le client soit informé de l’origine de ses achats. <br/> <br/>

Vous pouvez également faire programmer des extensions pour obtenir plus d\'analyses statistiques sur l\'évolution du chiffre d\'affaires.<br/> <br/>

<strong>Important</strong>: <u>Certains systèmes de gestion de marchandises</u> ne tiennent pas compte des  commandes si les commentaires clients sont intégrés. Pour plus d\'informations à ce sujet, contactez s\'il vous plaît directement votre fournisseur de service.';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__headline'} = 'Divers';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__label'} = 'Rédacteur en chef';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__desc'} = 'Editeur pour les descriptions de produits, des modèles (Templates) et les courriers électroniques promotionnels.<br /><br />
	                <strong>TinyMCE Editeur:</strong><br />Utilisez un éditeur confortable, qui affiche les formats HTML et par exemple, corrige automatiquement les flèches d\'accès dans la description des articles.<br /><br />
	                <strong>Ajouter des champs de texte simples, et des liens locaux:</strong><br />Utilisez un champ de texte simple. Utile pour le remplissage lorsque l\'éditeur TinyMCE provoque des modifications indésirables des modèles spécifiés(comme par exemple dans le modèle de produit eBay).<br />
	                Les images ou liens, dont les adresses ne commencent pas par<strong>http://</strong>,
	                <strong>javascript:</strong>, <strong>mailto:</strong> ou <strong>#</strong>,
	                seront cependant transformées en adresse de boutique.<br /><br />
	                <strong>Les champs de textes simples, les données directes seront reprises:</strong><br />Il n\'y a aucune adresse acceptée dans laquelle des modifications de texte auront été effectuées.';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__values__tinyMCE'} = 'Editeur TinyMCE ';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__values__none'} = 'Ajoutez le champ de texte simple, les liens locaux';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__editor__values__none_none'} = 'Acceptez les données directement, un simple texte. ';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__stocksyncbyorder__label'} = 'Déclencheur de synchronisation<br /> lors de commandes effectuées.';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__stocksyncbyorder__desc'} = 'Est-ce que les commandes en boutique doivent être automatiquement comparées avec les stocks correspondants des places de marché?<br /><br />
							<b>Avantage</b>: Vous évitez ainsi les excès de ventes<br />
							<b>Désavantage</b>: La comparaison peut prendre quelques secondes, ce qui retarde le processus de commande.<br />';
MLI18n::gi()->{'aGeneralForm__cronTimeTable__fields__stocksyncbyorder__values__val'} = 'Synchronisez immédiatement l\'inventaire avec les places de marché, pour toute commande en boutique.';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__headline'} = 'Inventaire';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__fields__statusIsZero__label'} = 'Statut du produit';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__fields__statusIsZero__desc'} = 'Vous pouvez utiliser cette fonction pour déterminer, si les articles marqués "Inactifs" de votre boutique en ligne, doivent être <strong>inaccessibles</strong> sur une place de marché (eBay),
ou juste <strong>inactifs </strong>(sur les autres).<br/><br/>

Pour que cette fonctionnalité soit prise en compte, sélectionnez le module correspondant à la place de marché en cliquant sur :<br/><br/>

"synchronisation des inventaires" &rarr;  "Variation des stocks de la boutique" → 
"synchronisation automatique par CronJob".
';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__fields__statusIsZero__values__true'} = 'Si le statut du produit est inactif, le stock sera mis à 0.';
MLI18n::gi()->{'aGeneralForm__articleStatusInventory__fields__statusIsZero__values__false'} = 'Utilisez toujours le stock actuel';
MLI18n::gi()->{'aGeneralForm__productfields__headline'} = 'Propriétés du produit';
MLI18n::gi()->{'aGeneralForm__productfields__fields__manufacturer__label'} = 'Marque';
MLI18n::gi()->{'aGeneralForm__productfields__fields__manufacturer__desc'} = 'Choisissez l’attribut de produit qui est associé au nom du fabricant.<br/>
Vous pouvez définir les attributs de produit dans votre logiciel de e-commerce.';
MLI18n::gi()->{'aGeneralForm__productfields__fields__mfnpartno__label'} = 'Modèle';
MLI18n::gi()->{'aGeneralForm__productfields__fields__mfnpartno__desc'} = 'Choisissez l’attribut de produit dans lequel la référence de produit du fabricant est sauvegardée.<br/>
Vous pouvez définir les attributs de produit dans votre logiciel de e-commerce.';
MLI18n::gi()->{'aGeneralForm__productfields__fields__EAN__label'} = 'EAN';
MLI18n::gi()->{'aGeneralForm__productfields__fields__EAN__desc'} = '(Numéro d’article européen) <br/> <br/>
<strong>Remarque</strong>: Attention, la véracité des données n’est pas contrôlable. Une saisie incorrecte entraînerait des erreurs de fonctionnement de la banque de données!';
