<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sDateFormat'} = 'd/m/Y';
MLI18n::gi()->{'sDateTimeFormat'} = 'd/m/Y H:i:s';
MLI18n::gi()->{'ML_HEADLINE_MAIN'} = 'magnalister';
MLI18n::gi()->{'ML_ERROR_API'} = 'Ocorreu um erro durante o Layer serviço magnalister. O pedido não pôde ser processado com sucesso.';
MLI18n::gi()->{'ML_HEADLINE_WELCOME'} = 'Seja bem vindo';
MLI18n::gi()->{'ML_HEADLINE_UPDATE'} = 'Atualizações importantes';
MLI18n::gi()->{'ML_HEADLINE_MORE_MODULES'} = 'Conectores a outros Marketplaces&hellip;';
MLI18n::gi()->{'ML_HEADLINE_NOT_YET_BOOKED'} = 'O Conector ainda não esta ativado.';
MLI18n::gi()->{'ML_HEADLINE_STATS'} = 'Estatísticas';
MLI18n::gi()->{'ML_HEADLINE_SUBMIT_PRODUCTS'} = 'Transferência de dados';
MLI18n::gi()->{'ML_HEADLINE_NEWS'} = 'Novidades';
MLI18n::gi()->{'ML_LABEL_CATEGORY_TOP'} = 'Topo';
MLI18n::gi()->{'ML_LABEL_CHOICE'} = 'Seleção';
MLI18n::gi()->{'ML_LABEL_CHOOSE'} = 'Selecionar';
MLI18n::gi()->{'ML_LABEL_TITLE'} = 'Título';
MLI18n::gi()->{'ML_LABEL_SHOP_TITLE'} = 'Título da loja';
MLI18n::gi()->{'ML_LABEL_SELECT_ALL_PRODUCTS'} = 'Adicionar todos os produtos';
MLI18n::gi()->{'ML_LABEL_SELECT_ALL_PRODUCTS_OF_CATEGORY'} = 'Adicionar todos os produtos dessa categoria';
MLI18n::gi()->{'ML_LABEL_DESELECT_ALL_PRODUCTS'} = 'Remover todos os produtos';
MLI18n::gi()->{'ML_LABEL_DESELECT_ALL_PRODUCTS_OF_CATEGORY'} = 'Remover todos os produtos dessa categoria';
MLI18n::gi()->{'ML_LABEL_SELECT_PRODUCT'} = 'Adicionar produto';
MLI18n::gi()->{'ML_LABEL_DESELECT_PRODUCT'} = 'Remover produto';
MLI18n::gi()->{'ML_LABEL_NO_PRODUCTS_SELECTABLE'} = 'Nenhum produtos selecionável';
MLI18n::gi()->{'ML_LABEL_SORT_ASCENDING'} = 'Ordenar ascendente';
MLI18n::gi()->{'ML_LABEL_SORT_DESCENDING'} = 'Ordem decrescente';
MLI18n::gi()->{'ML_LABEL_CATEGORIES_PRODUCTS'} = 'Categoria / Artigo';
MLI18n::gi()->{'ML_LABEL_SHOP_PRICE'} = 'Preço na Loja';
MLI18n::gi()->{'ML_LABEL_DATA_PREPARED'} = 'Dados já editados';
MLI18n::gi()->{'ML_LABEL_SHOP_PRICE_NETTO'} = 'Preço na Loja (líquido)';
MLI18n::gi()->{'ML_LABEL_SHOP_PRICE_BRUTTO'} = 'Preço na Loja (bruto)';
MLI18n::gi()->{'ML_LABEL_BRUTTO'} = 'Bruto';
MLI18n::gi()->{'ML_LABEL_NETTO'} = 'Líquido';
MLI18n::gi()->{'ML_LABEL_CATEGORY'} = 'Categoria';
MLI18n::gi()->{'ML_LABEL_PRODUCT'} = 'Produto';
MLI18n::gi()->{'ML_LABEL_EMPTY'} = 'Vazio';
MLI18n::gi()->{'ML_LABEL_ACTION'} = 'Ação';
MLI18n::gi()->{'ML_LABEL_ACTIONS'} = 'Ações';
MLI18n::gi()->{'ML_LABEL_INFO'} = 'Informação';
MLI18n::gi()->{'ML_LABEL_CATEGORY_PATH'} = 'Caminho da categoria';
MLI18n::gi()->{'ML_LABEL_PRODUCT_NAME'} = 'Nome do Produto';
MLI18n::gi()->{'ML_LABEL_PRODUCTS_ID'} = 'ID do produto';
MLI18n::gi()->{'ML_LABEL_LABEL'} = 'Descrição ';
MLI18n::gi()->{'ML_LABEL_EDIT'} = 'Editar';
MLI18n::gi()->{'ML_LABEL_AMOUNT_SELECTED_PRODUCTS'} = 'Número de produtos selecionados:';
MLI18n::gi()->{'ML_LABEL_AMOUNT_PRODUCTS'} = 'Número de produtos';
MLI18n::gi()->{'ML_LABEL_TEMPLATE'} = 'Pré-seleção';
MLI18n::gi()->{'ML_LABEL_TEMPLATE_X_SAVED'} = 'A pré-seleção %s foi salva.';
MLI18n::gi()->{'ML_LABEL_TEMPLATE_EXISTS'} = 'Esta pré-seleção já existe. Por favor, indique um nome diferente.';
MLI18n::gi()->{'ML_LABEL_TITLE_FOR_TEMPLATE'} = 'Por favor, digite um nome para a pré-seleção.';
MLI18n::gi()->{'ML_LABEL_TEMPLATE_X_OVERWRITTEN'} = 'A pré-seleção foi sobrescrita.';
MLI18n::gi()->{'ML_LABEL_TITLE_MAY_NOT_BE_EMPTY'} = 'O título não pode ficar vazio. Por favor adicione um titulo válido.';
MLI18n::gi()->{'ML_LABEL_CANT_SAVE_TEMPLATE_BC_NO_PROD'} = 'A pré-seleção na pôde ser salva, pois pelo menos um produto em uma categoria deve estar presente.';
MLI18n::gi()->{'ML_LABEL_OVERWRITE_OLD_TEMPLATE'} = 'Substituir pré-seleção antiga:';
MLI18n::gi()->{'ML_LABEL_TEMPLATE_TITLE'} = 'Titulo da Pré-Seleção:';
MLI18n::gi()->{'ML_LABEL_TEMPLATE_SAVE_AS_NEW'} = 'Salvar como nova pré-seleção:';
MLI18n::gi()->{'ML_LABEL_NO_TEMPLATES_YET'} = 'Ainda não existe nenhuma pré-seleção.';
MLI18n::gi()->{'ML_LABEL_USE_TEMPLATE'} = 'Utilizar pré-seleção';
MLI18n::gi()->{'ML_LABEL_QUANTITY'} = 'Quantidade';
MLI18n::gi()->{'ML_LABEL_QUANTITY_AVAILABLE'} = 'Quantidade disponível';
MLI18n::gi()->{'ML_LABEL_NEW_QUANTITY'} = 'Nova quantidade';
MLI18n::gi()->{'ML_LABEL_OLD_QUANTITY'} = 'Quantidade Antiga';
MLI18n::gi()->{'ML_LABEL_ATTENTION'} = 'Atenção';
MLI18n::gi()->{'ML_LABEL_LISTINGS_USED_THIS_MONTH'} = 'Uploads/importações utilizadas neste mês';
MLI18n::gi()->{'ML_LABEL_LISTINGS_UPGRADE_HEADLINE'} = 'Upgrade?';
MLI18n::gi()->{'ML_LABEL_RATE'} = 'Tarifa';
MLI18n::gi()->{'ML_LABEL_NOTE'} = 'Atenção';
MLI18n::gi()->{'ML_LABEL_UNKNOWN'} = 'desconhecido';
MLI18n::gi()->{'ML_LABEL_CURRENT_PAGE'} = 'Página Atual';
MLI18n::gi()->{'ML_LABEL_PAGE'} = 'Página';
MLI18n::gi()->{'ML_LABEL_INFORMATION'} = 'Informação';
MLI18n::gi()->{'ML_LABEL_SAVED'} = 'salvo';
MLI18n::gi()->{'ML_LABEL_INFOS'} = 'Informações';
MLI18n::gi()->{'ML_LABEL_SEARCH'} = 'Procura';
MLI18n::gi()->{'ML_LABEL_PRODUCTS'} = 'Produtos';
MLI18n::gi()->{'ML_LABEL_SAVED_SUCCESSFULLY'} = 'Salvo com sucesso';
MLI18n::gi()->{'ML_LABEL_COPYLEFT'} = 'Copyright &copy; 2010 - 2015 RedGecko GmbH. Todos os direitos reservados.';
MLI18n::gi()->{'ML_LABEL_SOLD_OUT'} = 'esgotado';
MLI18n::gi()->{'ML_LABEL_ARTICLE_NUMBER'} = 'Numero do artigo';
MLI18n::gi()->{'ML_LABEL_DETAILS'} = 'Detalhes';
MLI18n::gi()->{'ML_LABEL_DETAILS_FOR'} = 'Detalhes de';
MLI18n::gi()->{'ML_LABEL_PRODUCTS_IMAGES'} = 'Fotos do produto';
MLI18n::gi()->{'ML_LABEL_PAYMENT_METHOD'} = 'Método de pagamento';
MLI18n::gi()->{'ML_LABEL_ACCOUNTING_OWNER'} = 'Nome titular da conta bancaria';
MLI18n::gi()->{'ML_LABEL_ACCOUNTING_NUMBER'} = 'Numero da conta';
MLI18n::gi()->{'ML_LABEL_ACCOUNTING_BLZ'} = 'Código do Banco';
MLI18n::gi()->{'ML_LABEL_ACCOUNTING_NAME'} = 'Instituição de crédito';
MLI18n::gi()->{'ML_LABEL_ORDER_TOTAL_COD_FEE'} = 'Taxa para pagamento na entrega';
MLI18n::gi()->{'ML_LABEL_ORDER_TOTAL_COUPON'} = 'Cupons';
MLI18n::gi()->{'ML_LABEL_ORDER_TOTAL_DISCOUNT'} = 'Desconto';
MLI18n::gi()->{'ML_LABEL_ORDER_TOTAL_COUNTRY_CHARGE'} = 'Sobretaxa por país';
MLI18n::gi()->{'ML_LABEL_IN_QUEUE'} = 'Na fila';
MLI18n::gi()->{'ML_LABEL_REFRESH'} = 'Utilizar valores da configuração';
MLI18n::gi()->{'ML_LABEL_STEP'} = 'passo';
MLI18n::gi()->{'ML_LABEL_ALL'} = 'Todos';
MLI18n::gi()->{'ML_LABEL_NO_DATA'} = 'Nenhum dado';
MLI18n::gi()->{'ML_LABEL_ART_NR'} = 'Numero do artigo';
MLI18n::gi()->{'ML_LABEL_ART_NR_SHORT'} = 'Nr. Art.';
MLI18n::gi()->{'ML_LABEL_OLD'} = 'Antigo';
MLI18n::gi()->{'ML_LABEL_NEW'} = 'Novo';
MLI18n::gi()->{'ML_LABEL_INVALID'} = 'inválido';
MLI18n::gi()->{'ML_LABEL_NO_SEARCH_RESULTS'} = 'Nenhum resultado de busca';
MLI18n::gi()->{'ML_LABEL_PRODUCTS_WITH_INVALID_MODELNR'} = 'Produto com número faltante ou número duplicado';
MLI18n::gi()->{'ML_LABEL_NOT_SET'} = 'não atribuído';
MLI18n::gi()->{'ML_LABEL_PRODUCT_ID'} = 'ID do Produto';
MLI18n::gi()->{'ML_LABEL_TAB_IDENT'} = 'Nome da aba (opcional)';
MLI18n::gi()->{'ML_LABEL_SKU'} = 'SKU';
MLI18n::gi()->{'ML_LABEL_EAN'} = 'EAN';
MLI18n::gi()->{'ML_LABEL_BRAND'} = 'Marca';
MLI18n::gi()->{'ML_LABEL_SUBCATEGORY'} = 'Subcategoria';
MLI18n::gi()->{'ML_LABEL_MAINCATEGORY'} = 'Categoria principal';
MLI18n::gi()->{'ML_LABEL_TRACKINGCODE'} = 'Código de rastreamento';
MLI18n::gi()->{'ML_LABEL_CARRIER'} = 'Transportador';
MLI18n::gi()->{'ML_LABEL_CARRIER_NONE'} = 'nenhum transportador informado';
MLI18n::gi()->{'ML_LABEL_ORDER_ID'} = 'Numero do pedido';
MLI18n::gi()->{'ML_LABEL_SHIPPING_DATE'} = 'Data do envio';
MLI18n::gi()->{'ML_LABEL_ESTIMATED_ARRIVAL_DATE'} = 'Data de entrega estimada';
MLI18n::gi()->{'ML_LABEL_DONT_USE'} = 'Não usar';
MLI18n::gi()->{'ML_LABEL_SELECT_TABLE_FIRST'} = 'Por favor escolha primeiro uma tabela';
MLI18n::gi()->{'ML_LABEL_HISTORY'} = 'Histórico';
MLI18n::gi()->{'ML_LABEL_PROMISE_DATE'} = 'Envio até';
MLI18n::gi()->{'ML_LABEL_ORDER_CANCELLED'} = 'Pedido cancelado em';
MLI18n::gi()->{'ML_LABEL_SELECTED_CATEGORIES'} = 'Categorias selecionadas';
MLI18n::gi()->{'ML_LABEL_MATCH_CATEGORIES'} = 'Corresponder categorias';
MLI18n::gi()->{'ML_LABEL_USE_STANDARD'} = 'Usar o padrão';
MLI18n::gi()->{'ML_LABEL_TAX_STANDARD'} = 'Padrão';
MLI18n::gi()->{'ML_LABEL_TAX_REDUCED'} = 'Reduzido';
MLI18n::gi()->{'ML_LABEL_TAX_FREE'} = 'Sem impostos';
MLI18n::gi()->{'ML_LABEL_UPDATE'} = 'Realizar atualização';
MLI18n::gi()->{'ML_LABEL_IMPORT_ORDERS'} = 'Importar pedidos';
MLI18n::gi()->{'ML_LABEL_SYNC_INVENTORY'} = 'Sincronizar preço e estoque';
MLI18n::gi()->{'ML_LABEL_SYNC_INVENTORY_LOG'} = 'Iniciar protocolo: sincronização de inventário Loja &rarr; Mercado ';
MLI18n::gi()->{'ML_LABEL_SYNC_CONTINUE_MODE'} = ' em modo de continuação';
MLI18n::gi()->{'ML_LABEL_SYNC_ORDERSTATUS'} = 'Sincronizar situação de pedido';
MLI18n::gi()->{'ML_LABEL_LISTINGSBASED'} = 'Comissão';
MLI18n::gi()->{'ML_LABEL_PARENT'} = 'Artigo pai';
MLI18n::gi()->{'ML_LABEL_MARKETPLACE_ORDER_ID'} = 'Numero do pedido no Marketplace';
MLI18n::gi()->{'ML_LABEL_MARKETPLACE_PAYMENT_METHOD'} = 'Método de pagamento';
MLI18n::gi()->{'ML_LABEL_MARKETPLACE_SHIPPING_METHOD'} = 'Método de envio';
MLI18n::gi()->{'ML_LABEL_MARKETPLACE_SHIPPING_TIME'} = 'Tempo de envio';
MLI18n::gi()->{'ML_LABEL_MARKETPLACE_SHIPPING_TIME_VALUE'} = 'Nos próximos %s dias';
MLI18n::gi()->{'ML_LABEL_SKU_NOT_IN_SHOP'} = 'Um Artigo com este SKU não pode (mais) ser encontrado na loja';
MLI18n::gi()->{'ML_LABEL_GENERIC_SETTINGS'} = 'Configuração Geral';
MLI18n::gi()->{'ML_LABEL_DO_NOT_CHANGE'} = 'Não alterar';
MLI18n::gi()->{'ML_LABEL_SHIPPING_TIME_SHOP'} = 'Prazo de entrega da loja';
MLI18n::gi()->{'ML_LABEL_INCL'} = 'inclusive';
MLI18n::gi()->{'ML_LABEL_MISSING_DATA'} = 'Dados faltantes';
MLI18n::gi()->{'ML_LABEL_UNCHECK_SELECTION'} = 'Cancelar seleção';
MLI18n::gi()->{'ML_LABEL_CUSTOMERSID'} = 'ID do cliente';
MLI18n::gi()->{'ML_OPTION_EMPTY'} = 'Sem informação';
MLI18n::gi()->{'ML_OPTION_DELETED_ARTICLES_ENUM_DEFAULT'} = 'Mostrar todos';
MLI18n::gi()->{'ML_OPTION_DELETED_ARTICLES_ENUM_'} = 'Não mostrar %s';
MLI18n::gi()->{'ML_OPTION_DELETED_ARTICLES_ENUM_EMPTY'} = 'Visualizar oque esta existente no %s';
MLI18n::gi()->{'ML_OPTION_DELETED_ARTICLES_ENUM_SYNC'} = 'Terminar estoque sincronização .';
MLI18n::gi()->{'ML_OPTION_DELETED_ARTICLES_ENUM_BUTTON'} = 'Encerrar através do deletar';
MLI18n::gi()->{'ML_OPTION_DELETED_ARTICLES_ENUM_EXPIRED'} = 'Terminar através do processo';
MLI18n::gi()->{'ML_LABEL_STATS_ORDERS_PER_MARKETPLACE_PERCENT'} = 'Pedidos por Mercado (porcentual)';
MLI18n::gi()->{'ML_LABEL_STATS_PERCENT_OF_ORDERS'} = '% dos pedidos ';
MLI18n::gi()->{'ML_LABEL_STATS_ORDERS_PER_MARKETPLACE'} = 'Pedidos por Mercado';
MLI18n::gi()->{'ML_LABEL_STATS_ORDERS'} = 'Pedidos';
MLI18n::gi()->{'ML_LABEL_DELIVERY_METHOD'} = 'Métodos de Envio';
MLI18n::gi()->{'ML_BUTTON_LABEL_OK'} = 'OK';
MLI18n::gi()->{'ML_BUTTON_LABEL_ACCEPT'} = 'ML_BUTTON_LABEL_ACCEPT';
MLI18n::gi()->{'ML_BUTTON_LABEL_CANCEL'} = 'ML_BUTTON_LABEL_CANCEL';
MLI18n::gi()->{'ML_BUTTON_LABEL_ABORT'} = 'Cancelar';
MLI18n::gi()->{'ML_BUTTON_LABEL_GO'} = 'Avançar';
MLI18n::gi()->{'ML_BUTTON_LABEL_BACK'} = 'Voltar';
MLI18n::gi()->{'ML_BUTTON_LABEL_SAVE_DATA'} = 'Salvar dados';
MLI18n::gi()->{'ML_BUTTON_LABEL_SAVE_AND_NEXT'} = 'Salvar e Avançar ';
MLI18n::gi()->{'ML_BUTTON_LABEL_RESET'} = 'Resetar';
MLI18n::gi()->{'ML_BUTTON_LABEL_SUMMARY'} = 'Enviar seleção: resumo';
MLI18n::gi()->{'ML_BUTTON_LABEL_DELETE'} = 'Apagar';
MLI18n::gi()->{'ML_BUTTON_LABEL_DELETE_ENTIRE_PROTOCOL'} = 'Apagar todo o protocolo';
MLI18n::gi()->{'sMarketplace_BUTTON_LABEL_DELETE_COMPLETE_LOG'} = 'sMarketplace_BUTTON_LABEL_DELETE_COMPLETE_LOG';
MLI18n::gi()->{'ML_BUTTON_LABEL_REFRESH'} = 'Atualizar';
MLI18n::gi()->{'ML_BUTTON_LABEL_BACK_TO_TEMPLATEADMIN'} = 'Voltar ao gerenciador de modelos';
MLI18n::gi()->{'ML_BUTTON_LABEL_BACK_TO_CHECKIN'} = 'Voltar';
MLI18n::gi()->{'ML_BUTTON_LABEL_ADMINISTRATE_TEMPLATES'} = 'Gerenciar modelo';
MLI18n::gi()->{'ML_BUTTON_LABEL_CHECKIN_ADD'} = 'Enviar artigos agora / modificar';
MLI18n::gi()->{'ML_BUTTON_LABEL_CHECKIN_PURGE'} = 'Substituir inventário completo';
MLI18n::gi()->{'ML_BUTTON_LABEL_RETRY'} = 'Tentar enviar novamente';
MLI18n::gi()->{'ML_BUTTON_LABEL_YES'} = 'Sim';
MLI18n::gi()->{'ML_BUTTON_LABEL_NO'} = 'Não';
MLI18n::gi()->{'ML_BUTTON_RESTORE_DEFAULTS'} = 'Restaurar padrão';
MLI18n::gi()->{'ML_BUTTON_RELOAD_INVENTORY'} = 'Atualizar a visualização do inventário';
MLI18n::gi()->{'ML_BUTTON_REFRESH_STOCK'} = 'Atualizar estoque para todos';
MLI18n::gi()->{'ML_BUTTON_LABEL_EXPERTVIEW'} = 'Configurações Avançadas';
MLI18n::gi()->{'ML_BUTTON_LABEL_REVERT'} = 'Reverter a preparação ';
MLI18n::gi()->{'ML_HINT_NO_PRODUCTS_SELECTED'} = 'Você deve escolher ao menos um produto antes de poder executar esta ação.';
MLI18n::gi()->{'ML_HINT_HEADLINE_EXCEEDING_INCLUSIVE_LISTINGS'} = 'Limite de Envios / Importações excedido';
MLI18n::gi()->{'ML_HINT_HEADLINE_CONFIRM_PURGE'} = 'Substituir inventário completo?';
MLI18n::gi()->{'ML_TEXT_MAKE_YOUR_CHOISE'} = 'Por favor escolha a seu Marketplace acima.';
MLI18n::gi()->{'ML_TEXT_PLEASE_WAIT'} = 'Por favor aguarde&hellip;';
MLI18n::gi()->{'ML_TEXT_FILLOUT_CONFIG_FORM'} = 'Por favor preencha todos campos.';
MLI18n::gi()->{'ML_TEXT_NEW_VERSION'} = 'Uma nova versão do (%s)magnalisters esta pronto para baixar.
	para fazer a atualização do magnalister, click#aqui#.<br/>
	<b>Importante:</b>Por favor faca um backup da sua loja  antes the continuar com a atualização(Arquivos e banco de dados).';
MLI18n::gi()->{'ML_TEXT_NEW_VERSION_SAFE_MODE'} = 'Uma nova versão do (%s)magnalisters esta disponivel para baixar.<br/><br/>
	{#i18n:ML_TEXT_GENERIC_SAFE_MODE#}<br/><br/>
<b>Importante:</b>Por favor fac  um backup da sua loja  antes the continuar com a atualização(Arquivos e banco de dados).';
MLI18n::gi()->{'ML_TEXT_IMPORTANT_UPDATE'} = 'Uma nova atualização(%s)magnalisters esta disponível para baixar.
Esta atualização não e compatível com versões anteriores, Portanto
atualize para a última versão! Para atualizar o magnalister
<b>Importante:</b>Por favor faca um backup da sua loja  antes the continuar com a atualização(Arquivos e banco de dados)';
MLI18n::gi()->{'ML_TEXT_IMPORTANT_UPDATE_SAFE_MODE'} = 'Uma nova atualização(%s)magnalisters esta disponível para baixar.
	Esta atualização não e compatível com versões anteriores, Portanto
atualize para a última versão!<br/><br/>
{#i18n:ML_TEXT_GENERIC_SAFE_MODE#}<br/><br/>
<b>Importante:</b>Por favor faca um backup da sua loja  antes the continuar com a atualização(Arquivos e banco de dados).';
MLI18n::gi()->{'ML_TEXT_UPDATE_SHOP_CHANGES'} = 'ML_TEXT_UPDATE_SHOP_CHANGES';
MLI18n::gi()->{'ML_TEXT_LISTING_EXCEEDED'} = 'Você excedeu seu limite Uploads/Importação mensal.<br/>
Você tem a alternativa de aumentar fluxo de Uploads/Importação no plano de tarifa na pagina<a target="_blank" href="{#i18n:MAGNA_PUBLIC_SERVER#}frontend/login.php/rateupgrade:%d" title="Tarif-Upgrade">Tarifa-Upgrade</a>
Com uma nova tarifa será possível fazer mais Uploads/Importação.';
MLI18n::gi()->{'ML_TEXT_LISTING_ALMOST_EMPTY'} = 'Você tem somente %s%% Uploads/Importação restante neste mês .<br/>
Você tem a alternativa de aumentar fluxo de Uploads/Importação no plano de tarifa na pagina<a target="_blank" href="{#i18n:MAGNA_PUBLIC_SERVER#}frontend/login.php/rateupgrade:%d" title="Tarif-Upgrade">Tarifa-Upgrade</a>
Com uma nova tarifa será possível fazer mais Uploads/Importação.';
MLI18n::gi()->{'ML_TEXT_LISTING_GOING_TO_EXCEED'} = '<p>Você já esta passado seu limite de cota mensal de Uploads/importação.assim você será cobrado uma taxa de  pelo limite passado, o preço dessa taxa pode ser visualizada na pagina<a target="_blank" href="{#i18n:MAGNA_PUBLIC_SERVER#}frontend/rate.php" title="Preis&uuml;bersicht">aqui</a>remover.</p>  
Você tem a alternativa de aumentar fluxo de Uploads/Importação no plano de tarifa na pagina<a target="_blank" href="{#i18n:MAGNA_PUBLIC_SERVER#}frontend/login.php/rateupgrade:%d" title="Tarif-Upgrade">Tarifa-Upgrade</a>
Com uma nova tarifa será possível fazer mais Uploads/Importação.';
MLI18n::gi()->{'ML_TEXT_CURRENT_MODULE_NOT_BOOKED'} = 'ML_TEXT_CURRENT_MODULE_NOT_BOOKED';
MLI18n::gi()->{'ML_TEXT_MORE_MODULES'} = '<p>Você não contratou conexões adicionais ou não existem mais Marketplaces disponíveis para conexão.</p>
<p>Para a contratação de conexões a mais Marketplaces, faça o login <a href="{#setting:sPublicUrl#}frontend/login.php" title="Login de Clientes"
      class="ml-js-noBlockUi" target=_blank">aqui</a>, selecione "Minhas Lojas" e solicite Marketplaces adicionais através do
      botão "Editar".</p>
<p>Se desejar uma conexão inexistente em nosso programa, por favor nos envie uma mensagem &ndash; somos gratos por todos os seus 
      comentários e sugestões:<br />
      <a href="{#setting:sPublicUrl#}support" title="Suporte" class="ml-js-noBlockUi" target="_blank">{#setting:sPublicUrl#}suporte</a></p>';
MLI18n::gi()->{'ML_TEXT_BUTTON_CHECKIN_ADD'} = 'Quando você clica em <span class="button">{#i18n:ML_BUTTON_LABEL_CHECKIN_ADD#}</span>,
os artigos enviados são acrescidos ao arquivo CSV. Caso estes produtos já existam neste arquivo, os mesmos são atualizados / substituídos.';
MLI18n::gi()->{'ML_TEXT_BUTTON_CHECKIN_PURGE'} = 'Quando você clica em <span class="button">{#i18n:ML_BUTTON_LABEL_CHECKIN_PURGE#}</span>,
	o arquivo CSV antigo é apagado e um novo contendo apenas os artigos enviados gerado. ';
MLI18n::gi()->{'ML_TEXT_CONFIG_SAVED_SUCCESSFULLY'} = 'A configuração foi salva com sucesso.';
MLI18n::gi()->{'ML_TEXT_CONFIG_SAVED_SEMI_SUCCESSFULLY'} = 'Algumas alterações não puderam ser salvas, por conterem erros.
Por favor corrija todos os valores que possuem descrições de erro na cor vermelha no lado esquerdo.<br />
Os valores antigos forma restaurados nestes locais.  
';
MLI18n::gi()->{'ML_TEXT_TEMPLATE_INFO'} = 'Nas pré-seleções são salvos uma seleção de produtos com diferentes valores, que posteriormente podem ser parcialmente alterados antes do processo de envio.';
MLI18n::gi()->{'ML_TEXT_CONFIRM_PURGE'} = '<strong>Atenção:</strong> Você está prestes a substituir o inventário completo. 
    Este procedimento primeiramente apaga o inventário <strong>completo</strong> do seu Marketplace e a seguir o substitui pelos artigos aqui selecionados.<br/><br/>
	Você deseja mesmo continuar?';
MLI18n::gi()->{'ML_TEXT_TAB_IDENT'} = 'Define o nome da aba para este Marketplace, para poder diferencia-lo melhor das outras abas (opcional).';
MLI18n::gi()->{'ML_TEXT_FTP_CORRECT'} = 'Dados do FTP checados e salvos!';
MLI18n::gi()->{'ML_TEXT_ORDERS_IMPORTED'} = 'Pedidos foram importados';
MLI18n::gi()->{'ML_TEXT_CONFIRM_SKU_CHANGE_TITLE'} = 'Atenção';
MLI18n::gi()->{'ML_TEXT_CONFIRM_SKU_CHANGE_TEXT'} = 'Esteja ciente de que esta função  no processamento no gerenciamento  de mercadorias,pode sofre  impacto sobre o equilíbrio da loja e do inventários do mercado. <br> Se, posteriormente, depois de já ter transferido o artigo com uma das duas configurações, você vai corromper os intervalos de números, assim
pode-o  ter uma conexão corrompida entre magnalister, e sua loja e outros  mercados.';
MLI18n::gi()->{'ML_NOTICE_PLACE_PASSPHRASE'} = 'ML_NOTICE_PLACE_PASSPHRASE';
MLI18n::gi()->{'ML_NOTICE_SUBMIT_PRODUCTS'} = 'Este processo pode levar alguns minutos dependendo do numero de produtos!
Por favor não atualize o navegador  
';
MLI18n::gi()->{'ML_STATUS_SUBMIT_PRODUCTS'} = '{1} anteriormente {2} transferido. {3} total.';
MLI18n::gi()->{'ML_STATUS_SUBMIT_PRODUCTS_SUMMARY'} = '{1} de {2} Artigo foi transferido.';
MLI18n::gi()->{'ML_STATUS_FILTER_SYNC_ITEM'} = 'Sincronização com o servidor da Magnalister';
MLI18n::gi()->{'ML_STATUS_FILTER_SYNC_CONTENT'} = 'Por favor tenha paciência ';
MLI18n::gi()->{'ML_STATUS_FILTER_SYNC_SUCCESS'} = 'ML_STATUS_FILTER_SYNC_SUCCESS';
MLI18n::gi()->{'ML_ERROR_LABEL'} = 'Erro';
MLI18n::gi()->{'ML_ERROR_UNKNOWN'} = 'Erro desconhecido';
MLI18n::gi()->{'ML_ERROR_LABEL_API_FUNCTION'} = 'Função API';
MLI18n::gi()->{'ML_ERROR_LABEL_API_CONNECTION_PROBLEM'} = 'ML_ERROR_LABEL_API_CONNECTION_PROBLEM';
MLI18n::gi()->{'ML_ERROR_LABEL_LEVEL'} = 'estagio';
MLI18n::gi()->{'ML_ERROR_LABEL_TYPE'} = 'tipo';
MLI18n::gi()->{'ML_ERROR_LABEL_SUBSYSTEM'} = 'Subsistema';
MLI18n::gi()->{'ML_ERROR_LABEL_MESSAGE'} = 'Notificação';
MLI18n::gi()->{'ML_ERROR_ACCESS_DENIED_TO_SERVICE_LAYER_TEXT'} = 'Você não tem direitos para usar serviços  magnalister-Layer .
Por favor entre em contato com nosso suporte
{#i18n:MAGNA_SUPPORT_URL#}.';
MLI18n::gi()->{'ML_ERROR_AMAZON_WRONG_SELLER_CENTRAL_LOGIN'} = 'As credenciais do mercado Amazon-Seller não estão corretas: 
    O servidor da magnalister não pode se conectar com essas credencias.
   Por favor revise sua credenciais e configuração,sem as credenciais você não poderá inserir produtos e tambem visualizar status do produto.';
MLI18n::gi()->{'ML_ERROR_NO_JAVASCRIPT'} = '<h2>sem JavaScript</h2>
	<p>Para usar a ferramenta magnalister- e necessário instalar o plugin JavaScript no navegador.</p>
	<p>Versões de navegadores recomendados <ul>
		<li>Firefox</li>
		<li>Safari</li>
		<li>Google Chrome</li>
	</ul></p>';
MLI18n::gi()->{'ML_ERROR_OLD_BROWSER'} = '<h2>Zu alter Browser</h2>
	<p> Para usar a ferramenta magnalister- e necessário um  navegador atualizado como descrito pelo Webstandards .</p>
	<p> Versões de navegadores recomendados</p>
	<ul>
		<li>Firefox</li>
		<li>Safari</li>
		<li>Google Chrome</li>
	</ul>';
MLI18n::gi()->{'ML_ERROR_INVALID_NUMBER'} = 'Nenhum numero valido';
MLI18n::gi()->{'ML_ERROR_WRONG_DEFAULT_CURRENCY'} = 'Você esta inserindo um produto no portal de vendas ,que a moeda ja e existente.
	Sua moeda standard e %2$s!<br/>
	Por isso você não poderá inserir produtos no portal de vendas. Por favor troque sua standard moeda para resolver esse problema.';
MLI18n::gi()->{'ML_ERROR_LISTINGS_USED_UNKOWN'} = 'Anúncios anteriores  não pôde ser recuperados devido a um erro.';
MLI18n::gi()->{'ML_SUCCESS_CS_CHECKIN_ALL'} = 'Produto inserindo com sucesso';
MLI18n::gi()->{'ML_ERROR_CS_CHECKIN_FEW'} = 'Ocorreram erros durante o processo de configuração. Ele só poderia ser definidos de %d a %d itens.';
MLI18n::gi()->{'ML_ERROR_CS_CHECKIN_NONE'} = 'Ocorreram erros durante o processo de configuração. De %d itens não puderam ser definidas.';
MLI18n::gi()->{'ML_ERROR_UNAUTHED'} = 'Sua loja não pode se autenticar erro no Layer da magdalista
Por favor revise se suas credenciais e Shop-URL(Cliente login na magnalister)estão corretos.';
MLI18n::gi()->{'ML_ERROR_SUBMIT_PRODUCTS'} = 'Na transferência do produto para magnalister-Service-Layer foi encontrado erros. 
	 Por favor tente mais tarde.
Se o erro persisti por favor entre em contato com nosso suporte
{#i18n:MAGNA_SUPPORT_URL#}.';
MLI18n::gi()->{'ML_ERROR_MISSING_CURRENCY'} = 'A moeda do mercado (% s) que você selecionou na configuração que e referente da
Moeda desta loja (% s). Na divisões das tabelas armazena a moeda do mercado não está incluída. Enquanto for este o caso,
não pode usar o mercado.';
MLI18n::gi()->{'ML_ERROR_INVALID_PASSWORD'} = 'Senha incorreta. Por favor, verifique seus dados.
 Por favor, não copiar  de um texto, mas escrever a senha para excluir fontes de erro.';
MLI18n::gi()->{'ML_ERROR_MISSING_PRODUCTS_EAN'} = ' Sua loja não pode salvar o EANS na informação do produto, A inserir um novo produto no portal da Amazon e necessário
o uso do EANS , Se deseja usar funcionalidade em sua loja, Por favor consulte nosso suporte  magnalister para ajudá-lo com a instalação. Suporte: "MAGNA_SUPPORT_URL ... ';
MLI18n::gi()->{'ML_ERROR_COULD_NOT_LOAD_LOCAL_CLIENTVERSION'} = 'Não e  possível carregar o arquivo Cliente-Versão do servidor';
MLI18n::gi()->{'ML_ERROR_FTP_CANNOT_CONNECT'} = 'Não e possível estabelecer uma conexão com o servidor com essas credenciais, Por favor revise as suas credenciais do FTP
Se o erro persisti por favor entre em contato com nosso suporte técnico na pagina {#i18n:MAGNA_SUPPORT_URL#}.';
MLI18n::gi()->{'ML_ERROR_FTP_PATH_DOES_NOT_MATCH'} = 'Não e possível estabelecer uma conexão com o servidor, entretanto pode ser um erro com diretrizes na pasta da loja, por favor revise as diretrizes da pasta da loja.
Se o erro persisti por favor entre em contato com nosso suporte técnico na pagina {#i18n:MAGNA_SUPPORT_URL#}.';
MLI18n::gi()->{'ML_ERROR_FTP_PERMISSION_DENIED'} = 'Não e possível estabelecer uma conexão com o servidor do FTP, entretanto o usuário do FTP não tem direito de leitura.
Por favor acione um usuário com diretrizes de escrita na pasta.
Se o erro persisti por favor entre em contato com nosso suporte técnico na pagina {#i18n:MAGNA_SUPPORT_URL#}.';
MLI18n::gi()->{'ML_ERROR_FTP_INCOMPLETE_DATA'} = 'As credenciais do FTP esta correta, Entretanto Updates não são necessários.
Se tiver alguma duvida por favor contacte nosso suporte técnico na pagina {#i18n:MAGNA_SUPPORT_URL#}.';
MLI18n::gi()->{'ML_ERROR_FTP_NOT_WORKY_CAUSE_OF_RETARDED_PHPCONFIG'} = 'O servido do FTP não pode salvar os dados por causa do Servidor esta inativo.
Os updates automáticos somente estão disponíveis por causa do Safe Mode  isto somente no modulo FTP-Cliente.
Por favor contacte seu administrador do Hosting para desativar o safe-mode do servidor.
Se tiver alguma duvida por favor contacte nosso suporte técnico na pagina {#i18n:MAGNA_SUPPORT_URL#}.';
MLI18n::gi()->{'ML_ERROR_MARKETPLACE_TIMEOUT'} = 'No momento o conector para este mercado esta inativo, se esse problema persistir por 8um longo período. 
Por favor entre em contato com nosso suporte técnico na pagina {#i18n:MAGNA_SUPPORT_URL#}.';
MLI18n::gi()->{'ML_ERROR_NO_CATEGORIES_FOUND'} = 'Nenhuma categoria encontrada ';
MLI18n::gi()->{'ML_ERROR_CREATING_REQUEST'} = 'Existe um erro em gerar os dados a serem carregados.';
MLI18n::gi()->{'ML_ERROR_NO_SHIPPINGTIME_MATCHING'} = 'O Tempo de envio não e suportado com essa loja';
MLI18n::gi()->{'ML_ERROR_GD_LIB_MISSING'} = 'O GD2 biblioteca não esta instalado. isto necessita de uma imagem pequena para mostrar na estatística';
MLI18n::gi()->{'ML_CONFIG_NOT_INT'} = 'nenhum numero digito';
MLI18n::gi()->{'ML_CONFIG_NOT_FLOAT'} = 'Nenhum numero';
MLI18n::gi()->{'ML_CONFIG_NOT_EMPTY'} = 'Não pode ficar vazio';
MLI18n::gi()->{'ML_CONFIG_MUST_CONTAIN'} = 'Deve conter';
MLI18n::gi()->{'ML_CONFIG_INVALID_CHARS'} = 'contem caractere invalido';
MLI18n::gi()->{'ML_CONFIG_FIELD_EMPTY_OR_MISSING'} = 'ML_CONFIG_FIELD_EMPTY_OR_MISSING';
MLI18n::gi()->{'ML_GENERIC_PREPARE'} = 'Produtos preparados ';
MLI18n::gi()->{'ML_GENERIC_CHECKIN'} = 'Upload';
MLI18n::gi()->{'ML_GENERIC_CONFIGURATION'} = 'Configuração ';
MLI18n::gi()->{'ML_GENERIC_INVENTORY'} = 'Inventário';
MLI18n::gi()->{'ML_GENERIC_DELETED'} = 'Apagado';
MLI18n::gi()->{'ML_GENERIC_FAILED'} = 'Erros';
MLI18n::gi()->{'ML_GENERIC_ERRORLOG'} = 'Notificações de erros';
MLI18n::gi()->{'ML_GENERIC_PRODUCTDETAILS'} = 'Detalhes do produto';
MLI18n::gi()->{'ML_GENERIC_IMAGES'} = 'Imagem';
MLI18n::gi()->{'ML_GENERIC_CONDITION'} = 'Estado';
MLI18n::gi()->{'ML_GENERIC_CONDITION_NOTE'} = 'ML_GENERIC_CONDITION_NOTE';
MLI18n::gi()->{'ML_GENERIC_SHIPPING'} = 'Envio';
MLI18n::gi()->{'ML_GENERIC_PRICE'} = 'Preço';
MLI18n::gi()->{'ML_GENERIC_NO_IMAGE'} = 'Nenhuma imagem';
MLI18n::gi()->{'ML_GENERIC_PRODUCTDESCRIPTION'} = 'Descrição do produto';
MLI18n::gi()->{'ML_GENERIC_MY_PRODUCTDESCRIPTION'} = 'Minha descrição do produto';
MLI18n::gi()->{'ML_GENERIC_CHECKINDATE'} = 'Data de inserção';
MLI18n::gi()->{'ML_GENERIC_DELETEDDATE'} = 'Data de deletado';
MLI18n::gi()->{'ML_GENERIC_COMMISSIONDATE'} = 'Data de contratação ';
MLI18n::gi()->{'ML_GENERIC_STATUS'} = 'Status';
MLI18n::gi()->{'ML_GENERIC_ERROR_CODE'} = 'ML_GENERIC_ERROR_CODE';
MLI18n::gi()->{'ML_GENERIC_ERROR_MESSAGES'} = 'Notificação de erro';
MLI18n::gi()->{'ML_GENERIC_ERROR_DETAILS'} = 'Detalhes do erro';
MLI18n::gi()->{'ML_GENERIC_NO_ERRORS_YET'} = 'Nenhum erro apresentado';
MLI18n::gi()->{'ML_GENERIC_BOOKED'} = 'Anotado';
MLI18n::gi()->{'ML_GENERIC_COULD_NOT_DELETE'} = 'Não pode ser deletado';
MLI18n::gi()->{'ML_GENERIC_NO_DELETED_ITEMS_IN_TIMEFRAME'} = 'No momento nenhum artigo ';
MLI18n::gi()->{'ML_GENERIC_NO_DELETED_ITEMS_YET'} = 'Nenhum artigo apagado até este momento.';
MLI18n::gi()->{'ML_GENERIC_LISTINGS'} = 'Inventário';
MLI18n::gi()->{'ML_GENERIC_LOWEST_PRICE'} = 'Preço alvo';
MLI18n::gi()->{'ML_GENERIC_OLD_PRICE'} = 'Preço antigo';
MLI18n::gi()->{'ML_GENERIC_NO_INVENTORY'} = 'O inventário esta vazio neste momento.';
MLI18n::gi()->{'ML_GENERIC_EAN'} = 'EAN';
MLI18n::gi()->{'ML_GENERIC_MANUFACTURER'} = 'Artigo do fabricante';
MLI18n::gi()->{'ML_GENERIC_MANUFACTURER_NAME'} = 'Artigo do fabricante';
MLI18n::gi()->{'ML_GENERIC_MANUFACTURER_PARTNO'} = 'Numero do modelo';
MLI18n::gi()->{'ML_GENERIC_MODEL_NUMBER'} = 'Numero do artigo';
MLI18n::gi()->{'ML_GENERIC_WEIGHT'} = 'Peso';
MLI18n::gi()->{'ML_GENERIC_SHIPPING_COST'} = 'Custo de envio';
MLI18n::gi()->{'ML_GENERIC_SHIPPING_COST_ADDITIONAL'} = 'Preço recomendado de envio';
MLI18n::gi()->{'ML_GENERIC_SHIPPING_COST_IN_CURRENCY'} = '{#i18n:ML_GENERIC_SHIPPING_COST#} em %s';
MLI18n::gi()->{'ML_GENERIC_SHIPPING_TIME'} = 'Data de envio';
MLI18n::gi()->{'ML_GENERIC_TESTMAIL_SENT'} = 'Email test foi enviado';
MLI18n::gi()->{'ML_GENERIC_NO_TESTMAIL_SENT'} = 'Erro de envio de Email, Por favor corrija os campos do Email';
MLI18n::gi()->{'ML_GENERIC_TESTMAIL_SENT_FAIL'} = 'Erro de envio de Email, Por favor corrija os campos do email';
MLI18n::gi()->{'ML_GENERIC_LASTSYNC'} = 'ML_GENERIC_LASTSYNC';
MLI18n::gi()->{'ML_GENERIC_AUTOMATIC_ORDER'} = 'Este e um da magnalister automatizando os pedidos já inseridos do seu mercado ';
MLI18n::gi()->{'ML_GENERIC_AUTOMATIC_ORDER_MP'} = 'magnalister-processando (%s)';
MLI18n::gi()->{'ML_GENERIC_AUTOMATIC_ORDER_MP_SHORT'} = 'magnalister-executando (%s)';
MLI18n::gi()->{'ML_GENERIC_ORDER_THROUGH_COMPARISON_SHOPPING'} = 'O cliente encontrou sua loja através do mecanismo de maquina de busca do portal (%s)';
MLI18n::gi()->{'ML_GENERIC_STATUS_LOGIN_SAVED'} = 'As credenciais foi transferidas com sucesso no servidor da magnalister ';
MLI18n::gi()->{'ML_GENERIC_STATUS_LOGIN_SAVEERROR'} = 'As credenciais não  foram transferidas com sucesso no servidor da magnalister ';
MLI18n::gi()->{'ML_GENERIC_DELETE_LISTINGS'} = 'Você gostaria de marcar os produtos depois eliminar-lhos? ';
MLI18n::gi()->{'ML_GENERIC_DELETE_ERROR_MESSAGES'} = 'Você quer que as mensagens de erro destacados sejam eliminadas permanentemente?';
MLI18n::gi()->{'ML_GENERIC_CONFIRM_DELETE_ENTIRE_ERROR_PROTOCOL'} = 'ML_GENERIC_CONFIRM_DELETE_ENTIRE_ERROR_PROTOCOL';
MLI18n::gi()->{'ML_GENERIC_ERROR_WRONG_CURRENCY'} = 'A moeda do mercado(%s)decide qual moeda standard nesta loja será mostrada(%s).
O preço será convertido da moeda escolhida na loja,o fator da soma pode ser configurada em moeda configuração';
MLI18n::gi()->{'ML_GENERIC_ERROR_CURRENCY_NOT_IN_SHOP'} = 'A moeda do mercado selecionada (% s) não existe nesta loja.
Por favor especificar a moeda em sua loja, isso pode ser configurado neste mercado.';
MLI18n::gi()->{'ML_GENERIC_ERROR_UNABLE_TO_LOAD_PREPARE_DATA'} = 'Os dados já configurados do produto não pode ser carregados, isso não poderia ter acontecido, por favor entre em contato com nosso suporte  técnico ';
MLI18n::gi()->{'ML_GENERIC_TEXT_NO_PREPARED_PRODUCTS'} = 'No momento nenhum produto configurado. Antes de fazer o upload, Você tem que ir abaixo Abas "Configurar Produto"."Categoria do produto correspondente"editar<br>
Se você não tenha encontrado ,e este já estão configurado , por favor revise se estes estão inativos.';
MLI18n::gi()->{'ML_GENERIC_ERROR_PRODUCTS_WITHOUT_MODEL_EXIST'} = 'Erro produto sem ou com numero de artigo duplicado já inserido, estes produto não pode ser transferidos:
Você encontra corrigir essa configuração abaixo em "Sincronização número símbolo" e em essa opção "numero do artigo"
escolha e clique na pagina <a href="#LINK#"><b>aqui</b></a> para automatizar o numero do artigo para correção!<br/> 
outra alternativa você poderá editar o numero símbolo na configuração do produto ID.';
MLI18n::gi()->{'ML_GENERIC_LABEL_ORIGIN'} = 'ML_GENERIC_LABEL_ORIGIN';
MLI18n::gi()->{'ML_AMAZON_PRODUCT_PREPARE'} = 'Produto já configurado';
MLI18n::gi()->{'ML_AMAZON_PRODUCT_MATCHING'} = 'Produto já configurado';
MLI18n::gi()->{'ML_AMAZON_NEW_ITMES'} = 'Inserir um novo produto';
MLI18n::gi()->{'ML_AMAZON_CONDITION_DESCRIPTION'} = 'Status da descrição ';
MLI18n::gi()->{'ML_AMAZON_X_CHARS_LEFT'} = 'Caracteres restantes ainda ';
MLI18n::gi()->{'ML_AMAZON_PRODUCTGROUP'} = 'Grupo do produto';
MLI18n::gi()->{'ML_AMAZON_CATEGORY'} = 'Categoria do Amazon';
MLI18n::gi()->{'ML_AMAZON_NEW_SEARCH_QUERY'} = 'Nova procura';
MLI18n::gi()->{'ML_AMAZON_ENTER_ASIN_DIRECTLY'} = 'ASIN  insira direto';
MLI18n::gi()->{'ML_AMAZON_LABEL_AMAZON_PRICE'} = 'Meu preço do Amazon (bruto)';
MLI18n::gi()->{'ML_AMAZON_LABEL_AMAZON_PRICE_SHORT'} = 'Meu preço do Amazon';
MLI18n::gi()->{'ML_AMAZON_LABEL_OLD_AMAZON_PRICE_SHORT'} = 'Meu preço antigo do Amazon';
MLI18n::gi()->{'ML_AMAZON_LABEL_MATCHED'} = 'preparado';
MLI18n::gi()->{'ML_AMAZON_LABEL_MATCH'} = 'configurar';
MLI18n::gi()->{'ML_AMAZON_LABEL_MANUAL_MATCHING'} = 'Igualar  manualmente';
MLI18n::gi()->{'ML_AMAZON_LABEL_AUTOMATIC_MATCHING'} = 'Igualar  automático';
MLI18n::gi()->{'ML_AMAZON_BUTTON_MATCHING_DELETE'} = 'Abolir a que corresponde';
MLI18n::gi()->{'ML_AMAZON_LABEL_BATCHID'} = 'BatchID';
MLI18n::gi()->{'ML_AMAZON_LABEL_PRODUCT_IN_AMAZON'} = 'Sua promoção na Amazon';
MLI18n::gi()->{'ML_AMAZON_LABEL_ADD_WAIT'} = 'Pendente';
MLI18n::gi()->{'ML_AMAZON_LABEL_ADD_DONE'} = 'Conclua pedidos';
MLI18n::gi()->{'ML_AMAZON_LABEL_ADD_FAIL'} = 'Erro Conclua pedidos';
MLI18n::gi()->{'ML_AMAZON_LABEL_EDIT_WAIT'} = 'Artigo será atualizado';
MLI18n::gi()->{'ML_AMAZON_LABEL_DELETE_WAIT'} = 'Marcar como deletado';
MLI18n::gi()->{'ML_AMAZON_LABEL_DELETE_DONE'} = 'delete os resultados já encerrados';
MLI18n::gi()->{'ML_AMAZON_LABEL_DELETE_FAIL'} = 'Delete os resultados de erros';
MLI18n::gi()->{'ML_AMAZON_LABEL_IN_INVENTORY'} = 'Inventário atualizado';
MLI18n::gi()->{'ML_AMAZON_LABEL_LAST_REPORT'} = 'Ultima notificação do Amazon';
MLI18n::gi()->{'ML_AMAZON_LABEL_LAST_INVENTORY_CHANGE'} = 'Ultima edição no inventário ';
MLI18n::gi()->{'ML_AMAZON_LABEL_NO_INVENTORY'} = 'No momento não há nenhuma notificação no inventário do Amazon';
MLI18n::gi()->{'ML_AMAZON_LABEL_SIMILAR_PRODUCTS'} = 'Promoção identifica com da Amazon ';
MLI18n::gi()->{'ML_AMAZON_LABEL_SAME_PRODUCTS'} = 'Promoção identifica com da Amazon';
MLI18n::gi()->{'ML_AMAZON_LABEL_TITLE'} = 'Titulo do Amazon';
MLI18n::gi()->{'ML_AMAZON_LABEL_PRODUCT_AT_AMAZON'} = 'Produto no Amazon';
MLI18n::gi()->{'ML_AMAZON_LABEL_ONLY_NOT_MATCHED'} = 'Não esta referente';
MLI18n::gi()->{'ML_AMAZON_LABEL_MISSING_FIELDS'} = 'Erro no campo';
MLI18n::gi()->{'ML_AMAZON_LABEL_INCOMPLETE'} = 'Não definido';
MLI18n::gi()->{'ML_AMAZON_LABEL_PREPARE_KIND'} = 'Art definido';
MLI18n::gi()->{'ML_AMAZON_LABEL_PREPARE_IS_MATCHED'} = 'Definido';
MLI18n::gi()->{'ML_AMAZON_LABEL_PREPARE_IS_APPLIED'} = 'Inserir novo produto';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_EMPTY'} = 'Nenhum artigo com numero de EAN encontrado, Amazon determina registrar um novo produto com numero de EAN para Artigos variantes. ';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_SINGLE'} = 'Registros da configuração';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_MULTI'} = 'Multiplicativo Dash configuração';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_SELECT_MAIN_SUB_CAT_FIRST'} = 'Por favor escolha uma categoria ou uma subcategoria';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_SELECT_MAIN_CAT_FIRST'} = 'Por favor escolha sempre uma categoria principal';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_BROWSENODE_NOT_SELECTED'} = 'Não esta valida';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_PLEASE_SELECT'} = 'Por favor escolha';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_REQUIRED_ATTRIBUTES'} = 'Obrigatórios atributos';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_BROWSENODES'} = 'Nodes de navegadores';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_BULLETPOINTS'} = 'Pontos bullet';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_KEYWORDS'} = 'Todas palavras chaves';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_ADDITIONAL_DETAILS'} = 'Mais detalhes (recomendados)';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_NOT_PREPARED'} = 'Não esta configurado';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_PREPARE_COMPLETE'} = 'Definido';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_PREPARE_INCOMPLETE'} = 'Não esta definido';
MLI18n::gi()->{'ML_AMAZON_LABEL_APPLY_ATTRIBUTES'} = 'ML_AMAZON_LABEL_APPLY_ATTRIBUTES';
MLI18n::gi()->{'ML_AMAZON_LABEL_ADDITIONAL_DATA'} = 'Mais dados';
MLI18n::gi()->{'ML_AMAZON_LABEL_LEADTIME_TO_SHIP'} = 'Tempo de processo';
MLI18n::gi()->{'ML_AMAZON_CATEGORY_MATCHED_NONE'} = 'Nenhum definido';
MLI18n::gi()->{'ML_AMAZON_CATEGORY_MATCHED_FALUTY'} = 'Nenhum definido com sucesso';
MLI18n::gi()->{'ML_AMAZON_CATEGORY_MATCHED_ALL'} = 'Todos configurado com sucesso';
MLI18n::gi()->{'ML_AMAZON_CATEGORY_MATCHED_INCOMPLETE'} = 'Não esta completo';
MLI18n::gi()->{'ML_AMAZON_ITEMS_PREPARED'} = 'Dados estão completos';
MLI18n::gi()->{'ML_AMAZON_ITEMS_NOT_PREPARED'} = 'Dados não estão completos';
MLI18n::gi()->{'ML_AMAZON_BUTTON_PREPARE'} = 'Registro não esta completo';
MLI18n::gi()->{'ML_AMAZON_BUTTON_SELECTED'} = 'Registro escolhido';
MLI18n::gi()->{'ML_AMAZON_BUTTON_APPLY_DELETE'} = 'aplicativo cancelada';
MLI18n::gi()->{'ML_AMAZON_PRODUCT_MATHCED_NO'} = 'Nao esta completo';
MLI18n::gi()->{'ML_AMAZON_PRODUCT_MATCHED_FAULTY'} = 'Não esta completo com sucesso';
MLI18n::gi()->{'ML_AMAZON_PRODUCT_MATCHED_OK'} = 'Completo com sucesso';
MLI18n::gi()->{'ML_AMAZON_TEXT_REMATCH'} = 'O produto escolhido já foi duplicado. Para inserir um novo  Multi-comparar e para duplicar este e necessário antes na opção &quot;{#i18n:ML_LABEL_ALL#}&quot;perto do botão &quot;{#i18n:ML_AMAZON_LABEL_MANUAL_MATCHING#}&quot; escolher  a função  deste';
MLI18n::gi()->{'ML_AMAZON_TEXT_CHECKIN_DELAY'} = 'Por favor Atenção esse processo pode levar ate 2 horas para ser realizado com as configurações da Amazon';
MLI18n::gi()->{'ML_AMAZON_TEXT_REFRESH_REQUEST_SEND'} = 'Sua atualização de consulta foi mandada, Por favor paciência ate Amazon retorne uma notificação status';
MLI18n::gi()->{'ML_AMAZON_TEXT_NO_MATCHED_PRODUCTS'} = 'Nenhum  produto no momento  configurado com a Amazon, Antes que você faca um upload do produto, você deve editar o produto na aba "Editar Produto"
Se Você tiver perdido artigo ponto que você já editou então, por favor  verifique se eles estão possivelmente definido como inativo e também e se tiver definido a configuração conformidade. 
';
MLI18n::gi()->{'ML_AMAZON_TEXT_MANUALLY_MATCHING_DESC'} = 'O artigo do shop escolhido pelo checkbox será checado pelo ASIN, EAN e titulo serão comparado  com artigo dos artigos da Amazon.<br/ ><br/ >
Você vai receber um resultado detalhado como busca de sucesso ou não encontrado e você poderá individualmente fazer a escolha, como deve ser combinado com o resultados. <br/>
Manualmente  é muito preciso, mas também demorado.';
MLI18n::gi()->{'ML_AMAZON_TEXT_AUTOMATIC_MATCHING_DESC'} = 'O Artigo escolhido pela loja será  automaticamente processado :
O artigo será comparado com o símbolos e números inseridos do EAN  com o artigo já existente com numero de  EAN do Amazon    
Requisito é a manutenção dos números EAN para cada artigo

';
MLI18n::gi()->{'ML_AMAZON_TEXT_AUTOMATIC_MATCHING_CONFIRM'} = 'Por favor, note que o automático correspondente exclusivamente na comparação do número EAN
ocorre no Artigo da Amazon pode ser correspondido, no que temos imagens de um produto de qualidade inferior ou descrições. Portanto que correspondente a um resultado pior do que <br/.> correspondentes manuais <br/>
Portanto RedGecko GmbH não assume qualquer responsabilidade pela exatidão dos produtos correspondentes.

';
MLI18n::gi()->{'ML_AMAZON_TEXT_MATCHING_NO_ITEMS_SELECTED'} = 'Você não selecionou nenhum artigo.';
MLI18n::gi()->{'ML_AMAZON_TEXT_AUTOMATIC_MATCHING_SUMMARY'} = '%d Artigo foi comparado com sucesso. <br/ ><br/ >
	%d Artigo não pode ser comparado.<br />
	entre %d mais resultados.';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_REQUIERD_FIELDS'} = '<b>Atenção:</b> estes campos com <span class="bull">&bull;</span> opção de marca devem ser preenchidos';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_MANUFACTURER_NAME'} = 'Fabricante do produto';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_BRAND'} = 'Marca ou Fabricante do produtos ';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_MANUFACTURER_PARTNO'} = 'Descreva um modelo de fabricante para um produto';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_PRODUCTS_IMAGES'} = 'Máximo 9 imagens por produto';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_BULLETPOINTS'} = 'Chave-fabricante do artigo(por exemplo &quot;folheado a ouro colar; , &quot;pedras preciosas e com designer&quot;)
<br /><br /> esses detalhes serao atribuidos a maquina de busca e devem ser separados com coma ea descricao deve ser somente 500 caracteres. 

';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_PRODUCTDESCRIPTION'} = 'Máximo permitido 2000 caracteres. caracteres e label em no próprio HTML e permitido , mais este caracteres já são contados para isso ';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_KEYWORDS'} = '"Sera usado na busca(por exemplo," ouro "," Diamante "," Designer ") <br /> <br />
Estes dados são extraídos  palavras-chave meta  que devem ser separados por vírgulas. <br />
Máximo de 50 caracteres. 
';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_DATA_INCOMPLETE'} = 'Alguns campos obrigatórios não foram preenchidos. por favor corrija estes clicando sobre aba ".
ML_AMAZON_BUTTON_PREPARE.';
MLI18n::gi()->{'ML_AMAZON_TEXT_APPLY_REQUIERD_EAN'} = 'Não é relevante se é EAN depositado sobre as variantes';
MLI18n::gi()->{'ML_AMAZON_ERROR_WRONG_CURRENCY'} = 'A moeda dos Marcado Amazon (% s) que você selecionou na configuração diferente da
Moeda desta loja (% s). O preço é automaticamente convertido para a moeda relevante. O fator de conversão é as configurações de moeda serão tomadas.';
MLI18n::gi()->{'ML_AMAZON_ERROR_APPLY_CANNOT_FETCH_SUBCATS'} = 'Não pode carregar a Subcategoria';
MLI18n::gi()->{'ML_AMAZON_ERROR_CURRENCY_NOT_IN_SHOP'} = 'Moeda de mercado selecionado (% s) não existe nesta loja.
 Por favor especificar uma moeda em sua loja para ajustasse com o mercado Amazon.';
MLI18n::gi()->{'ML_AMAZON_ERROR_ORDERSYNC_FAILED'} = 'Os pedidos  não pode ser sincronizado. Consulte o log de ​​erro Amazon para mais detalhes.';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_SKU'} = 'ID artigo';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_TITLE'} = 'Nome do artigo';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_ID'} = 'ML_COMPARISON_SHOPPING_FIELD_SKU';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_NAME'} = 'ML_COMPARISON_SHOPPING_FIELD_ITEM_TITLE';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_PRICE'} = 'Preço';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_CURRENCY'} = 'Moeda';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_DESCRIPTION'} = 'Descrição do artigo';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_DESCRIPTION'} = 'ML_COMPARISON_SHOPPING_FIELD_DESCRIPTION';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_URL'} = 'URL do artigo';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_MANUFACTURER_NAME'} = 'Fabricante do artigo';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_MODEL_NUMBER'} = 'Numero do artigo';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_EAN'} = 'EAN';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_IMAGE1'} = 'Imagem-URL';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_IMAGE_URL'} = '{#i18n:ML_COMPARISON_SHOPPING_FIELD_IMAGE1#}';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_SHIPPING_PRICE'} = 'Custo de envio';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_SHIPPING_TIME'} = 'Processo de envio';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_WEIGHT'} = 'Peso to envio';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_TAX'} = 'Tributação';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_QUANTITY'} = 'Estoque';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_QUANTITY_HOVER'} = 'deve ser maior que 0';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_STOCK_QTY'} = '{#i18n:ML_COMPARISON_SHOPPING_FIELD_QUANTITY#}';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_ITEM_STOCK_QTY_HOVER'} = '{#i18n:ML_COMPARISON_SHOPPING_FIELD_QUANTITY_HOVER#}';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_DAPARTO_USAGE'} = 'usando(KBA)';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_FIELD_DAPARTO_USAGE_HOVER'} = 'numero indentico EAN';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_LABEL_MISSING_FIELDS'} = 'Erro no campo';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_LABEL_LUMP'} = ' not for Brasil';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_LABEL_ARTICLE_SHIPPING_COSTS'} = 'Custo de envio do artigo';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_LABEL_PATH_TO_CSV_TABLE'} = 'caminho para seu arquivo CSV-tabela';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_TEXT_NO_CSV_TABLE_YET'} = 'Nenhuma tabela CSV criado: Por favor, forneça um primeiro artigo. Depois de encontrar o caminho CSV aqui.';
MLI18n::gi()->{'ML_CSHOPPING_TEXT_RECONCILIATION_OF_INVENTORY'} = 'O processamento do inventário e na maquina de busca de preços (geralmente leva max. 24h).
Variações de curto prazo são possíveis.';
MLI18n::gi()->{'ML_CSHOPPING_TEXT_FIRST_CHECKIN'} = 'Seu artigo foi enviada com sucesso.
Por favor como última etapa,  Por favor envie o caminho de sua nova tabela CSV  e ainda a% 1 $ s para garantir que os produtos são ativados quando:
<br/>
<span class="tt">% 2 $ s </ span>
<br/>
Você vai encontrar o caminho a qualquer momento, sob a% 1 $ s registo → "Configuração".
Como você transmitir o caminho, você vai aprender diretamente com% 1 $ s';
MLI18n::gi()->{'ML_COMPARISON_SHOPPING_ERROR_INCOMPLETE_DATA'} = ' Erro na configuração. Os produtos a seguir não pode ser definido porque faltam informações.
Você pode editar o artigo diretamente, clicando sobre o nome do produto. ';
MLI18n::gi()->{'ML_GUENSTIGER_SAME_PRODUCT_THERE'} = 'Este artigo no Mercado guenstiger.de';
MLI18n::gi()->{'ML_GETDEAL_SAME_PRODUCT_THERE'} = 'Este artigo no Mercado getdeal.de ';
MLI18n::gi()->{'ML_IDEALO_SAME_PRODUCT_THERE'} = 'Este artigo no Mercado idealo.de ';
MLI18n::gi()->{'ML_PREISSUCHMASCHINE_SAME_PRODUCT_THERE'} = 'Este artigo no Mercado  preissuchmaschnine.de  ';
MLI18n::gi()->{'ML_KELKOO_SAME_PRODUCT_THERE'} = 'Este artigo no Mercado kelkoo.de ';
MLI18n::gi()->{'ML_YATEGO_SAME_PRODUCT_THERE'} = 'Este artigo no Mercado yatego ';
MLI18n::gi()->{'ML_YATEGO_CATEGORY_MATCHING'} = 'Comparação categoria';
MLI18n::gi()->{'ML_YATEGO_LABEL_SHOP_CATEGORIES'} = 'Categoria da loja';
MLI18n::gi()->{'ML_YATEGO_LABEL_YATEGO_CATEGORIES'} = ' Categoria da Yatego';
MLI18n::gi()->{'ML_YATEGO_LABEL_SELECTED_SHOP_CAT'} = 'Categorias escolhidas da loja';
MLI18n::gi()->{'ML_YATEGO_LABEL_SELECTED_YATEGO_CATS'} = 'Categorias escolhidas da Yatego';
MLI18n::gi()->{'ML_YATEGO_LABEL_ORDER_ID'} = 'Numero do pedido Yatego';
MLI18n::gi()->{'ML_YATEGO_LABEL_PURGE_CATEGORIES'} = 'ML_YATEGO_LABEL_PURGE_CATEGORIES';
MLI18n::gi()->{'ML_YATEGO_LABEL_INVALID_CATEGORIES'} = 'ML_YATEGO_LABEL_INVALID_CATEGORIES';
MLI18n::gi()->{'ML_YATEGO_LABEL_YATEGO_PRICE'} = 'ML_YATEGO_LABEL_YATEGO_PRICE';
MLI18n::gi()->{'ML_YATEGO_MESSAGE_NOT_YET_SAVED'} = 'ML_YATEGO_MESSAGE_NOT_YET_SAVED';
MLI18n::gi()->{'ML_YATEGO_MESSAGE_SELECT_SHOP_CAT_FIRST'} = 'ML_YATEGO_MESSAGE_SELECT_SHOP_CAT_FIRST';
MLI18n::gi()->{'ML_YATEGO_MESSAGE_SAVE_SELECT_SHOP_CAT_FIRST'} = 'ML_YATEGO_MESSAGE_SAVE_SELECT_SHOP_CAT_FIRST';
MLI18n::gi()->{'ML_YATEGO_MESSAGE_MATCHING_SAVED'} = 'ML_YATEGO_MESSAGE_MATCHING_SAVED';
MLI18n::gi()->{'ML_YATEGO_MESSAGE_ONLY_ONE_SUBCAT'} = 'ML_YATEGO_MESSAGE_ONLY_ONE_SUBCAT';
MLI18n::gi()->{'ML_YATEGO_ERROR_WHILE_SAVING'} = 'ML_YATEGO_ERROR_WHILE_SAVING';
MLI18n::gi()->{'ML_YATEGO_ERROR_SAVING_INVALID_YATEGO_CATS'} = 'ML_YATEGO_ERROR_SAVING_INVALID_YATEGO_CATS';
MLI18n::gi()->{'ML_YATEGO_ERROR_SAVING_INVALID_SHOP_CAT'} = 'ML_YATEGO_ERROR_SAVING_INVALID_SHOP_CAT';
MLI18n::gi()->{'ML_YATEGO_ERROR_SAVING_INVALID_YATEGO_CATS_ALL'} = 'ML_YATEGO_ERROR_SAVING_INVALID_YATEGO_CATS_ALL';
MLI18n::gi()->{'ML_YATEGO_ERROR_REQUEST_INVALID'} = 'ML_YATEGO_ERROR_REQUEST_INVALID';
MLI18n::gi()->{'ML_YAGETO_ERROR_CANNOT_DL_CATEGORIES'} = 'ML_YAGETO_ERROR_CANNOT_DL_CATEGORIES';
MLI18n::gi()->{'ML_YAGETO_ERROR_CATEGORIES_NOT_IMPORTED_YET'} = 'ML_YAGETO_ERROR_CATEGORIES_NOT_IMPORTED_YET';
MLI18n::gi()->{'ML_YAGETO_ERROR_ACCESS_DENIED'} = 'ML_YAGETO_ERROR_ACCESS_DENIED';
MLI18n::gi()->{'ML_YAGETO_TEXT_SPECIAL_FILTER'} = 'ML_YAGETO_TEXT_SPECIAL_FILTER';
MLI18n::gi()->{'ML_YATEGO_HINT_HEADLINE_PURGE_CATEGORIES'} = 'ML_YATEGO_HINT_HEADLINE_PURGE_CATEGORIES';
MLI18n::gi()->{'ML_YATEGO_TEXT_PURGE_CATEGORIES'} = 'ML_YATEGO_TEXT_PURGE_CATEGORIES';
MLI18n::gi()->{'ML_YATEGO_TEXT_DELETED_INVALID_CATEGORY_MATCHINGS'} = 'ML_YATEGO_TEXT_DELETED_INVALID_CATEGORY_MATCHINGS';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_1'} = '1 dia';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_3'} = '3 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_5'} = '5 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_7'} = '7 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_10'} = '10 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_14'} = '14 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_28'} = '28 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_30'} = '30 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_60'} = '60 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_DAYS_120'} = '120 dias';
MLI18n::gi()->{'ML_EBAY_LABEL_LISTINGDURATION_GTC'} = 'Sem limite';
MLI18n::gi()->{'ML_LABEL_EBAY_LISTINGTIME'} = 'Publicado em';
MLI18n::gi()->{'ML_LABEL_EBAY_LISTINGTIME_FROM'} = 'ML_LABEL_EBAY_LISTINGTIME_FROM';
MLI18n::gi()->{'ML_LABEL_EBAY_LISTINGTIME_TILL'} = 'ML_LABEL_EBAY_LISTINGTIME_TILL';
MLI18n::gi()->{'ML_EBAY_CONDITION_NEW'} = 'Novo';
MLI18n::gi()->{'ML_EBAY_CONDITION_NEW_OTHER'} = 'Novo / Diversos (s.Descrição do artigo)';
MLI18n::gi()->{'ML_EBAY_CONDITION_NEW_WITH_DEFECTS'} = 'Novo com erro';
MLI18n::gi()->{'ML_EBAY_CONDITION_MANUF_REFURBISHED'} = 'Do fabricante renovado ';
MLI18n::gi()->{'ML_EBAY_CONDITION_SELLER_REFURBISHED'} = 'Do Vendedor renovado';
MLI18n::gi()->{'ML_EBAY_CONDITION_USED'} = 'Usado';
MLI18n::gi()->{'ML_EBAY_CONDITION_VERY_GOOD'} = 'Usado como novo';
MLI18n::gi()->{'ML_EBAY_CONDITION_GOOD'} = 'Usado bom estado';
MLI18n::gi()->{'ML_EBAY_CONDITION_ACCEPTABLE'} = 'Usado mais aceitável ';
MLI18n::gi()->{'ML_EBAY_CONDITION_FOR_PARTS_OR_NOT_WORKING'} = 'Como defeitos ';
MLI18n::gi()->{'ML_EBAY_LABEL_NO_INTL_SHIPPING'} = 'Nenhum envio em outro pais';
MLI18n::gi()->{'ML_EBAY_LABEL_USE_SUBTITLE_YES_NO'} = 'Subtítulo a transferir ';
MLI18n::gi()->{'ML_EBAY_LABEL_USE_GALLERY_YES_NO'} = 'Imagen-galeria a transferir';
MLI18n::gi()->{'ML_EBAY_LABEL_ATTRIBUTES_FOR'} = 'Atributo para';
MLI18n::gi()->{'ML_LABEL_EBAY_PRIMARY_CATEGORY'} = 'Categoria primaria';
MLI18n::gi()->{'ML_LABEL_EBAY_SECONDARY_CATEGORY'} = 'Categoria secundária';
MLI18n::gi()->{'ML_LABEL_EBAY_STORE_CATEGORY'} = 'Categoria do mercado Ebay';
MLI18n::gi()->{'ML_LABEL_EBAY_ITEM_ID'} = ' Numero de Ofertas Ebay ';
MLI18n::gi()->{'ML_LABEL_EBAY_TITLE'} = 'Titulo Ebay';
MLI18n::gi()->{'ML_PRICE_SHOP_PRICE_EBAY'} = 'Preço Loja / eBay';
MLI18n::gi()->{'ML_STOCK_SHOP_STOCK_EBAY'} = 'Estoque loja / eBay';
MLI18n::gi()->{'ML_LAST_SYNC'} = 'Ultimo saldo ';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_ESTIMATED_TIME_M'} = 'ML_EBAY_N_PENDING_UPDATES_ESTIMATED_TIME_M';
MLI18n::gi()->{'ML_LABEL_EBAY_DELETION_REASON'} = 'Deletado atravez';
MLI18n::gi()->{'ML_SYNCHRONIZATION'} = 'Equilíbrio do Estoque';
MLI18n::gi()->{'ML_DELETION_BUTTON'} = 'Delete botão';
MLI18n::gi()->{'ML_NOT_BY_ML'} = 'Externo(não ml)';
MLI18n::gi()->{'ML_EBAY_TEXT_NO_MATCHED_PRODUCTS'} = 'Não há produtos foram preparados para eBay. Antes que você pode fazer upload de produtos aqui, você deve editar os "produtos" preparar com este guia. <br>
        Se falhar no artigo ponto que você já preparou, verifique se eles são possivelmente definido para inativo e você tiver definido a configuração em conformidade.';
MLI18n::gi()->{'ML_EBAY_LABEL_PREPARE'} = 'Preparação';
MLI18n::gi()->{'ML_EBAY_LABEL_PREPARED'} = 'Artigo configurado';
MLI18n::gi()->{'ML_EBAY_BUTTON_PREPARE'} = 'Configuração ';
MLI18n::gi()->{'ML_EBAY_BUTTON_UNPREPARE'} = 'Configuração completa';
MLI18n::gi()->{'ML_EBAY_BUTTON_RESET_DESCRIPTION'} = 'Configuração completa';
MLI18n::gi()->{'ML_EBAY_LABEL_ONLY_NOT_PREPARED'} = 'Somente artigos que ainda não estão configurados';
MLI18n::gi()->{'ML_EBAY_CATEGORY_PREPARED_NONE'} = 'A categoria já reservada não tem artigos configurados ';
MLI18n::gi()->{'ML_EBAY_CATEGORY_PREPARED_FAULTY'} = 'A categoria inclui alguns itens cuja a configuração  falhou';
MLI18n::gi()->{'ML_EBAY_CATEGORY_PREPARED_INCOMPLETE'} = 'Esta categoria contém alguns produtos configurados';
MLI18n::gi()->{'ML_EBAY_CATEGORY_PREPARED_ALL'} = 'Esta categoria contém somente produtos configurados';
MLI18n::gi()->{'ML_EBAY_PRODUCT_MATCHED_NO'} = 'O produto não foi configurado';
MLI18n::gi()->{'ML_EBAY_PRODUCT_PREPARED_FAULTY'} = 'A configuração do produto falhou até agora';
MLI18n::gi()->{'ML_EBAY_PRODUCT_PREPARED_OK'} = 'O produto esta corretamente configurado agora pode ser inserido';
MLI18n::gi()->{'ML_EBAY_LISTING_TYPE'} = 'Tipo de arremate ';
MLI18n::gi()->{'ML_EBAY_DURATION'} = 'Limite do arremate';
MLI18n::gi()->{'ML_EBAY_DURATION_SHORT'} = 'Tempo decorrido';
MLI18n::gi()->{'ML_EBAY_PAYMENT_METHODS'} = 'Tipos de pagamento';
MLI18n::gi()->{'ML_EBAY_PAYMENT_METHODS_OFFERED'} = 'Ofertas de tipos de pagamento';
MLI18n::gi()->{'ML_EBAY_ITEM_CONDITION'} = 'Condições';
MLI18n::gi()->{'ML_EBAY_ITEM_CONDITION_INFO'} = 'Condição do item (exibido na maioria das categorias no eBay)';
MLI18n::gi()->{'ML_EBAY_GALLERY_PICTURES'} = 'Galeria de imagens';
MLI18n::gi()->{'ML_EBAY_ENABLE_GALLERY_PICTURES'} = ' Ativar galeria de imagens (no Ebay custa a inserir imagens) ';
MLI18n::gi()->{'ML_EBAY_LABEL_EBAY_PRICE'} = 'Preço Ebay';
MLI18n::gi()->{'ML_EBAY_BUYITNOW'} = 'Compra imediata';
MLI18n::gi()->{'ML_EBAY_LABEL_SELECT_CATEGORY'} = 'Escolher categoria';
MLI18n::gi()->{'ML_EBAY_LABEL_SHIPPING_COSTS'} = 'Custo de envio';
MLI18n::gi()->{'ML_EBAY_LABEL_EACH_ONE_MORE'} = 'Outros Artigos';
MLI18n::gi()->{'ML_EBAY_LISTINGTYPE_CHINESE'} = 'Arremate(chinês)';
MLI18n::gi()->{'ML_EBAY_LISTINGTYPE_FIXEDPRICEITEM'} = 'Preço básico';
MLI18n::gi()->{'ML_EBAY_LISTINGTYPE_STORESFIXEDPRICE'} = 'Preço básico(Ebay loja)';
MLI18n::gi()->{'ML_EBAY_PRODUCT_DETAILS'} = 'Detalhes do artigo';
MLI18n::gi()->{'ML_EBAY_MAX_80_CHARS'} = 'Titulo máximo 80 caracteres<br/>permitido espaço:<br />#BASEPRICE# -preço básico ';
MLI18n::gi()->{'ML_EBAY_SUBTITLE'} = 'Subtítulo';
MLI18n::gi()->{'ML_EBAY_SUBTITLE_MAX_55_CHARS'} = 'Subtítulo máximo 55 caracteres.';
MLI18n::gi()->{'ML_EBAY_CAUSES_COSTS'} = 'Com custo';
MLI18n::gi()->{'ML_EBAY_PICTURE'} = 'Ebay-imagen';
MLI18n::gi()->{'ML_EBAY_MAIN_PICTURE_COMPLETE_URL'} = 'Imagem principal(completo URL)';
MLI18n::gi()->{'ML_EBAY_MAIN_GALLERY_PICTURE_CAUSES_COSTS'} = 'Galeria de imagem(custo)';
MLI18n::gi()->{'ML_EBAY_DESCRIPTION'} = 'Descrição';
MLI18n::gi()->{'ML_EBAY_PRODUCTS_DESCRIPTION'} = 'Descrição do produto';
MLI18n::gi()->{'ML_EBAY_PLACEHOLDERS'} = 'Espaço disponível ';
MLI18n::gi()->{'ML_EBAY_ITEM_NAME_TITLE'} = 'Nome do produto';
MLI18n::gi()->{'ML_EBAY_ARTNO'} = 'Numero do artigo';
MLI18n::gi()->{'ML_EBAY_PRODUCTS_ID'} = 'ID do produto';
MLI18n::gi()->{'ML_EBAY_PRICE'} = 'Preço';
MLI18n::gi()->{'ML_EBAY_PRICE_FOR_EBAY_SHORT'} = 'Preço para Ebay';
MLI18n::gi()->{'ML_EBAY_CALCULATED'} = 'Calculado';
MLI18n::gi()->{'ML_EBAY_PRICE_CALCULATED'} = 'Preço calculado<small>(gem. Konfig)</small>';
MLI18n::gi()->{'ML_EBAY_PRICE_FOR_EBAY'} = 'Preço para Ebay';
MLI18n::gi()->{'ML_EBAY_YOUR_PRICE_IF_OTHER'} = 'Seu preço do Ebay';
MLI18n::gi()->{'ML_EBAY_FREEZE_PRICE_TOOLTIP'} = 'Azul = congelamento de preços (de modo que não é ajustado automaticamente quando as mudanças na loja)"';
MLI18n::gi()->{'ML_EBAY_FREEZE_PRICE'} = 'Congelamento de preços (sem sincronização)';
MLI18n::gi()->{'ML_EBAY_PRICE_FROZEN_TOOLTIP'} = 'O preço vai ser cotado a configuração preço congelado';
MLI18n::gi()->{'ML_EBAY_PRICE_CALCULATED_TOOLTIP'} = 'O preço será na configuração ajustado ';
MLI18n::gi()->{'ML_EBAY_BUYITNOW_PRICE'} = 'Compra imediata';
MLI18n::gi()->{'ML_EBAY_YOUR_CHINESE_PRICE'} = 'Seu preço inicio';
MLI18n::gi()->{'ML_EBAY_YOUR_FIXED_PRICE'} = 'Seu Ebay preço';
MLI18n::gi()->{'ML_EBAY_PRICE_PER_VPE'} = 'Preço por empacotamento';
MLI18n::gi()->{'ML_EBAY_SHORTDESCRIPTION_FROM_SHOP'} = 'Descrição curta da loja';
MLI18n::gi()->{'ML_EBAY_DESCRIPTION_FROM_SHOP'} = 'Descrição da loja';
MLI18n::gi()->{'ML_EBAY_FIRST_PIC'} = 'Primeira imagem do produto';
MLI18n::gi()->{'ML_EBAY_MORE_PICS'} = 'Imagem do produto segundo lugar; Imagen3 com # # # # Picture4 etc podem ser  mais fotos, tantos como na loja disponível.';
MLI18n::gi()->{'ML_EBAY_AUCTION_SETTINGS'} = 'Arremate configuração';
MLI18n::gi()->{'ML_EBAY_SITE'} = 'Mercado Ebay o qual você configura';
MLI18n::gi()->{'ML_EBAY_PRIVATE_LISTING_SHORT'} = 'Lista privada';
MLI18n::gi()->{'ML_EBAY_PRIVATE_LISTING_YES_NO'} = 'Comprador/Lista de arremate não estará disponível';
MLI18n::gi()->{'ML_EBAY_PRIVATE_LISTING'} = 'Quando ativado, o comprador não poderá visualizar a arremate lista por terceiros';
MLI18n::gi()->{'ML_EBAY_BESTPRICE_SHORT'} = 'Preço sugerido';
MLI18n::gi()->{'ML_EBAY_BESTPRICE_YES_NO'} = '\'Preço sugerido\'ativar (somente artigos sem variação)';
MLI18n::gi()->{'ML_EBAY_BESTPRICE'} = 'Quando ativo,pode o comprador pode sugerir o próprio preço';
MLI18n::gi()->{'ML_EBAY_START_TIME_SHORT'} = 'Tempo de inicio<br />(Se já adicionado)';
MLI18n::gi()->{'ML_EBAY_START_TIME'} = 'Normalmente, um item do eBay está ativo imediatamente após o envio. Mas, se você preencher este campo, até o horário de início (taxa extra).';
MLI18n::gi()->{'ML_HITCOUNTER_SHORT'} = 'Visitantes contador';
MLI18n::gi()->{'ML_EBAY_NO_HITCOUNTER'} = 'nenhum';
MLI18n::gi()->{'ML_EBAY_BASIC_HITCOUNTER'} = 'Fácil';
MLI18n::gi()->{'ML_EBAY_RETRO_HITCOUNTER'} = 'Retro-Style';
MLI18n::gi()->{'ML_EBAY_HIDDEN_HITCOUNTER'} = 'Escondido';
MLI18n::gi()->{'ML_EBAY_NOTE_VARIATIONS_ENABLED'} = '<div class="successBox"><b>Atenção</b>:para essa categoria será desejável fazer o carregamento, (Konfig-Einstellung).</div>';
MLI18n::gi()->{'ML_EBAY_NOTE_VARIATIONS_DISABLED'} = '<div Class="errorBox"> <b class="error"> Nota </ b>: esta categoria eBay não fornece variantes, ele será carregado somente o item root </ div>';
MLI18n::gi()->{'ML_EBAY_PRICE_FOR_EBAY_LONG'} = 'Preço por artigo inserido no Ebay';
MLI18n::gi()->{'ML_EBAY_CATEGORY'} = 'Categoria do Ebay';
MLI18n::gi()->{'ML_EBAY_CATEGORY_DESC'} = 'As categorias do Ebay';
MLI18n::gi()->{'ML_EBAY_PRIMARY_CATEGORY'} = 'Categoria primaria';
MLI18n::gi()->{'ML_EBAY_SECONDARY_CATEGORY'} = 'Categoria secundária';
MLI18n::gi()->{'ML_EBAY_STORE_CATEGORY'} = 'Categoria Ebay';
MLI18n::gi()->{'ML_EBAY_SECONDARY_STORE_CATEGORY'} = 'Categoria secundária na loja';
MLI18n::gi()->{'ML_EBAY_CHOOSE'} = 'Escolher';
MLI18n::gi()->{'ML_EBAY_DELETE'} = 'Deletar';
MLI18n::gi()->{'ML_EBAY_SHIPPING_DOMESTIC'} = 'Envio no Brasil';
MLI18n::gi()->{'ML_EBAY_SHIPPING_DOMESTIC_DESC'} = 'Oferta de Envio no Brasil';
MLI18n::gi()->{'ML_EBAY_SHIPPING_INTL_OPTIONAL'} = 'Envio no exterior';
MLI18n::gi()->{'ML_EBAY_SHIPPING_INTL_DESC'} = 'Oferta de Envio no exterior ';
MLI18n::gi()->{'ML_EBAY_SHIPPING_PROFILE'} = 'Desconto combinado com envio';
MLI18n::gi()->{'ML_EBAY_SHIPPING_DISCOUNT'} = 'Regulamento para envio e preço em oferta ';
MLI18n::gi()->{'ML_EBAY_LABEL_EBAYERROR'} = 'Ebay Erro';
MLI18n::gi()->{'ML_EBAY_LABEL_CHANGE_SITE'} = 'Ebay Mercado site editar';
MLI18n::gi()->{'ML_EBAY_TEXT_CHANGE_SITE'} = 'Você selecionou um site eBay diferente. Isso afeta mais opções porque os sites nacionais e o eBay oferecem diferentes moedas e formas de pagamento e envio. Devo salvar essas configurações?';
MLI18n::gi()->{'ML_EBAY_LABEL_PROD_INFOS'} = 'Produto informação ativar';
MLI18n::gi()->{'ML_EBAY_TEXT_SET_PROD_INFOS'} = 'As informações do produto poderá ser ativados somente quando o numero do EAN ser inserido,Gostaria de ativar o EAN função?';
MLI18n::gi()->{'ML_EBAY_TEXT_REQUEST_TOKEN'} = 'Preencha Ebay token';
MLI18n::gi()->{'ML_ERROR_EBAY_WRONG_TOKEN'} = 'Ebay token falso por favor revise seu token.';
MLI18n::gi()->{'ML_EBAY_ERROR_CREATE_TOKEN_LINK_HEADLINE'} = 'Token link não pode ser criado ';
MLI18n::gi()->{'ML_EBAY_ERROR_CREATE_TOKEN_LINK_TEXT'} = 'Não estabeleceu conexão com o mercado Ebay. Por favor tente novamente.<br><br>
Se o erro ocorre novamente por favor entre em contato com magnalister- suporte técnico.';
MLI18n::gi()->{'ML_EBAY_TEXT_TOKEN_NOT_AVAILABLE_YET'} = 'Nenhum Token encontrado , por favor solicite um novo Token do Ebay';
MLI18n::gi()->{'ML_EBAY_TEXT_TOKEN_INVALID'} = 'O token do Ebay nao e valido ou falso, por favor solicite um novo Token do Ebay ';
MLI18n::gi()->{'ML_EBAY_TEXT_TOKEN_EXPIRES_AT'} = 'O é Token valido até %s';
MLI18n::gi()->{'ML_EBAY_BUTTON_TOKEN_NEW'} = 'Solicitar ou alterar Token';
MLI18n::gi()->{'ML_EBAY_SUBMIT_ADD_TEXT_ZERO_STOCK_ITEMS_REMOVED'} = 'Artigos com estoque 0 (zero) foram desconsiderados.';
MLI18n::gi()->{'ML_EBAY_ORDER_PAID'} = 'processo magnalister:\\npagamento no eBay registrado.';
MLI18n::gi()->{'ML_COUNTRY_AUSTRALIA'} = 'Austrália ';
MLI18n::gi()->{'ML_COUNTRY_AUSTRIA'} = 'Áustria';
MLI18n::gi()->{'ML_COUNTRY_BELGIUM_DUTCH'} = 'Bélgica (holandês)';
MLI18n::gi()->{'ML_COUNTRY_BELGIUM_FRENCH'} = 'Bélgica (francês)';
MLI18n::gi()->{'ML_COUNTRY_CANADA'} = 'Canada';
MLI18n::gi()->{'ML_COUNTRY_CANADA_FRENCH'} = 'Canadá (francês)';
MLI18n::gi()->{'ML_COUNTRY_CHINA'} = 'China';
MLI18n::gi()->{'ML_COUNTRY_FRANCE'} = 'Franca';
MLI18n::gi()->{'ML_COUNTRY_GERMANY'} = 'Alemanha';
MLI18n::gi()->{'ML_COUNTRY_HONGKONG'} = 'Hongkong';
MLI18n::gi()->{'ML_COUNTRY_INDIA'} = 'India';
MLI18n::gi()->{'ML_COUNTRY_IRELAND'} = 'Irlanda';
MLI18n::gi()->{'ML_COUNTRY_ITALY'} = 'Itália';
MLI18n::gi()->{'ML_COUNTRY_MALAYSIA'} = 'Malásia';
MLI18n::gi()->{'ML_COUNTRY_NETHERLANDS'} = 'Holanda';
MLI18n::gi()->{'ML_COUNTRY_PHILIPPINES'} = 'Filipinas';
MLI18n::gi()->{'ML_COUNTRY_POLAND'} = 'Polônia';
MLI18n::gi()->{'ML_COUNTRY_SINGAPORE'} = 'Singapura';
MLI18n::gi()->{'ML_COUNTRY_SPAIN'} = 'Espanha';
MLI18n::gi()->{'ML_COUNTRY_SWEDEN'} = 'Suécia';
MLI18n::gi()->{'ML_COUNTRY_SWITZERLAND'} = 'Suíça';
MLI18n::gi()->{'ML_COUNTRY_TAIWAN'} = 'Taiwan';
MLI18n::gi()->{'ML_COUNTRY_UK'} = 'Reino Unido';
MLI18n::gi()->{'ML_COUNTRY_USA'} = 'Estados Unidos';
MLI18n::gi()->{'ML_EBAY_SITE_MOTORS'} = 'Ebay motores';
MLI18n::gi()->{'ML_HITMEISTER_SAME_PRODUCT_THERE'} = 'ML_HITMEISTER_SAME_PRODUCT_THERE';
MLI18n::gi()->{'ML_HITMEISTER_LABEL_HITMEISTER_PRICE'} = 'ML_HITMEISTER_LABEL_HITMEISTER_PRICE';
MLI18n::gi()->{'ML_HITMEISTER_LABEL_ORDER_ID'} = 'ML_HITMEISTER_LABEL_ORDER_ID';
MLI18n::gi()->{'ML_MEINPAKET_CATEGORY_MATCHING'} = 'ML_MEINPAKET_CATEGORY_MATCHING';
MLI18n::gi()->{'ML_MEINPAKET_LABEL_CATMATCH_NOT_PREPARED'} = 'ML_MEINPAKET_LABEL_CATMATCH_NOT_PREPARED';
MLI18n::gi()->{'ML_MEINPAKET_LABEL_CATMATCH_PREPARE_COMPLETE'} = 'ML_MEINPAKET_LABEL_CATMATCH_PREPARE_COMPLETE';
MLI18n::gi()->{'ML_MEINPAKET_LABEL_CATMATCH_PREPARE_INCOMPLETE'} = 'ML_MEINPAKET_LABEL_CATMATCH_PREPARE_INCOMPLETE';
MLI18n::gi()->{'ML_MEINPAKET_CATEGORYMATCHING_ASSIGN_MP_CAT'} = 'ML_MEINPAKET_CATEGORYMATCHING_ASSIGN_MP_CAT';
MLI18n::gi()->{'ML_MEINPAKET_CATEGORYMATCHING_ASSIGN_SHOP_CAT'} = 'ML_MEINPAKET_CATEGORYMATCHING_ASSIGN_SHOP_CAT';
MLI18n::gi()->{'ML_MEINPAKET_LABEL_CATEGORY'} = 'ML_MEINPAKET_LABEL_CATEGORY';
MLI18n::gi()->{'ML_MEINPAKET_LABEL_PREPARED'} = 'ML_MEINPAKET_LABEL_PREPARED';
MLI18n::gi()->{'ML_MEINPAKET_LABEL_MP_PRICE_SHORT'} = 'ML_MEINPAKET_LABEL_MP_PRICE_SHORT';
MLI18n::gi()->{'ML_MEINPAKET_LABEL_MEINPAKETID'} = 'ML_MEINPAKET_LABEL_MEINPAKETID';
MLI18n::gi()->{'ML_MEINPAKET_LABEL_ORDER_ID'} = 'ML_MEINPAKET_LABEL_ORDER_ID';
MLI18n::gi()->{'ML_MEINPAKET_ERROR_ACCESS_DENIED'} = 'ML_MEINPAKET_ERROR_ACCESS_DENIED';
MLI18n::gi()->{'ML_MAGNACOMPAT_CATEGORYMATCHING_ASSIGN_MP_CAT'} = 'Atribuir categoria Marketplace';
MLI18n::gi()->{'ML_MAGNACOMPAT_LABEL_CATEGORY'} = 'Categoria Marketplace';
MLI18n::gi()->{'ML_MAGNACOMPAT_LABEL_PREPARED'} = 'Preparado';
MLI18n::gi()->{'ML_MAGNACOMPAT_LABEL_MP_PRICE_SHORT'} = 'Preço no meu Marketplace';
MLI18n::gi()->{'ML_MAGNACOMPAT_LABEL_MP_ITEMID'} = 'ID do Marketplace';
MLI18n::gi()->{'ML_MAGNACOMPAT_ERROR_ACCESS_DENIED'} = 'Os dados de acesso ao %s parecem estar incorretos.
           O servidor do magnalister não consegue estabelecer uma conexão com os dados de acesso.
           Por favor verifique os dados inseridos na configuração e, caso necessário, corrija-os. ';
MLI18n::gi()->{'ML_LAARY_ERROR_NO_REGION_SELECTED'} = 'ML_LAARY_ERROR_NO_REGION_SELECTED';
MLI18n::gi()->{'ML_INTERNAL_EMPTY_RESPONSE'} = 'Resposta do servidor do magnalister sem conteúdo. Por favor contate o nosso suporte.';
MLI18n::gi()->{'ML_INTERNAL_INVALID_RESPONSE'} = 'Resposta inválida do servidor do magnalister. Por favor contate o nosso suporte.';
MLI18n::gi()->{'ML_INTERNAL_API_CALL_UNSUCCESSFULL'} = 'Sem resposta da interface magnalister. Por favor contate o nosso suporte.';
MLI18n::gi()->{'ML_INTERNAL_API_TIMEOUT'} = 'O tempo de execução permitido para esta função foi excedido. Por favor tente novamente em alguns minutos.';
MLI18n::gi()->{'ML_RATE_FREETRIAL'} = 'Período de teste';
MLI18n::gi()->{'ML_RATE_BUSINESS2'} = 'Business 2';
MLI18n::gi()->{'ML_RATE_BUSINESS12'} = 'Business 12';
MLI18n::gi()->{'ML_RATE_ULTIMATE2'} = 'Ultimate 2';
MLI18n::gi()->{'ML_RATE_ULTIMATE12'} = 'Ultimate 12';
MLI18n::gi()->{'ML_RATE_FLAT2'} = 'Flat 2';
MLI18n::gi()->{'ML_RATE_FLAT12'} = 'Flat 12';
MLI18n::gi()->{'ML_RATE_SWITCH'} = '%s &ndash; válida até %s. Após isto alteração para a tarifa solicitada %s.';
MLI18n::gi()->{'ML_RATE_END'} = 'ML_RATE_END';
MLI18n::gi()->{'ML_RATE_CONTINUE'} = '%s';
MLI18n::gi()->{'ML_TOPTEN_MANAGE'} = 'gerenciar';
MLI18n::gi()->{'ML_TOPTEN_MANAGE_HEAD'} = 'Gerenciar seleção rápida de categorias';
MLI18n::gi()->{'ML_TOPTEN_INIT_HEAD'} = 'Inicializar';
MLI18n::gi()->{'ML_TOPTEN_INIT_DESC'} = 'Para preencher uma seleção rápida de categorias vazia com artigos já preparados, por favor clique no botão "Inicializar"';
MLI18n::gi()->{'ML_TOPTEN_INIT_INFO'} = 'Seleção rápida de categorias foi inicializada';
MLI18n::gi()->{'ML_TOPTEN_DELETE_HEAD'} = 'Apagar';
MLI18n::gi()->{'ML_TOPTEN_DELETE_DESC'} = 'Selecione múltiplos itens mantendo a tecla CTRL pressionada.';
MLI18n::gi()->{'ML_TOPTEN_DELETE_INFO'} = 'Seleção rápida de categoria foi apagada.';
MLI18n::gi()->{'ML_TOPTEN_TEXT'} = 'Seleção rápida de categorias';
MLI18n::gi()->{'ML_DAWANDA_TEXT_NO_MATCHED_PRODUCTS'} = 'ML_DAWANDA_TEXT_NO_MATCHED_PRODUCTS';
MLI18n::gi()->{'ML_MERCADOLIVRE_TEXT_NO_MATCHED_PRODUCTS'} = 'Nenhum produto foi ainda preparado para o MercadoLivre. Antes de poder enviar produtos, estes precisam ser preparados no Tópico (<i>Tab</i>) "Preparar Produtos".<br/>
Caso produtos que tenham sido preparados estejam faltando aqui, por favor verifique se estes não estão definidos como inativos e a configuração correspondente ajustada de acordo.';
MLI18n::gi()->{'ML_CHECK24_TEXT_NO_MATCHED_PRODUCTS'} = 'ML_CHECK24_TEXT_NO_MATCHED_PRODUCTS';
MLI18n::gi()->{'ML_TRADORIA_TEXT_NO_MATCHED_PRODUCTS'} = 'ML_TRADORIA_TEXT_NO_MATCHED_PRODUCTS';
MLI18n::gi()->{'ML_RICARDO_TEXT_NO_MATCHED_PRODUCTS'} = 'ML_RICARDO_TEXT_NO_MATCHED_PRODUCTS';
MLI18n::gi()->{'ML_RICARDO_LABEL_LAST_REPORT'} = 'Ultima notificação do Ricardo';
MLI18n::gi()->{'ML_RICARDO_TEXT_CHECKIN_DELAY'} = 'Por favor Atenção esse processo pode levar ate 2 horas para ser realizado com as configurações da Ricardo';
MLI18n::gi()->{'ML_RICARDO_PRODUCTS_NOT_SYNCRONIZED'} = 'ML_RICARDO_PRODUCTS_NOT_SYNCRONIZED';
