<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_config_orderimport_shop_lable'} = 'Mandataire de boutique';
MLI18n::gi()->{'form_config_orderimport_shop_help'} = 'Veuillez définir pour quel magasin la commande devra être affectée.';
MLI18n::gi()->{'form_config_orderimport_imagesize_lable'} = 'Taille d\'image';
MLI18n::gi()->{'form_config_orderimport_imagesize_help'} = 'Donnez ici la largeur en pixel, que votre image doit avoir sur votre page. La hauteur sera automatiquement ajustée. <br>
Vos images originales se trouvent dans le dossier image sous l’adresse : <i>shop-root/media/image</i>. Après ajustage,  elles sont versées dans le dossier : <i>shop-root/media/image/magnalister</i>, et sont prêtes à être utilisées par les places de marché.';
MLI18n::gi()->{'form_config_orderimport_imagesize_hint'} = 'Enregistrée sous l\'onglet: {#setting:sImagePath#}';
MLI18n::gi()->{'form_config_send_mailcontentcontailner_testmail'} = 'Aperçu';
