<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__OK__title'} = 'Fyndiq_Productlist_Cell_aPreparedStatus__OK__title';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Fyndiq_Productlist_Cell_aPreparedStatus__ERROR__title';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Fyndiq_Productlist_Cell_aPreparedStatus__OPEN__title';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__OK'} = 'Fyndiq_Productlist_Filter_aPreparedStatus__OK';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__ERROR'} = 'Fyndiq_Productlist_Filter_aPreparedStatus__ERROR';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__OPEN'} = 'Fyndiq_Productlist_Filter_aPreparedStatus__OPEN';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedType__Chinese'} = 'Fyndiq_Productlist_Cell_aPreparedType__Chinese';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fyndiq_Productlist_Cell_aPreparedType__FixedPriceItem';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fyndiq_Productlist_Cell_aPreparedType__StoresFixedPrice';
MLI18n::gi()->{'Fyndiq_Productlist_Header_sPreparedType'} = 'Fyndiq_Productlist_Header_sPreparedType';
