<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento_Productlist_Filter_sProductType'} = 'Type de produit';
MLI18n::gi()->{'Magento_Productlist_Filter_sAttributeSet'} = 'Ensemble d\'attributs';
MLI18n::gi()->{'Magento_Productlist_Filter_aSaleable__all'} = 'Filtre : article achetable';
MLI18n::gi()->{'Magento_Productlist_Filter_aSaleable__onlySaleable'} = 'seulement en vente';
