<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'cdiscount_config_account_title'} = 'Login Details';
MLI18n::gi()->{'cdiscount_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'cdiscount_config_account_price'} = 'Price Calculation';
MLI18n::gi()->{'cdiscount_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'cdiscount_config_account_orderimport'} = 'Order Import';
MLI18n::gi()->{'cdiscount_config_account_producttemplate'} = 'Product Template';
MLI18n::gi()->{'cdiscount_config_checkin_badshippingcost'} = 'Shipping cost must be a number.';
MLI18n::gi()->{'cdiscount_config_checkin_shippingmatching'} = 'cdiscount_config_checkin_shippingmatching';
MLI18n::gi()->{'cdiscount_config_checkin_manufacturerfilter'} = 'cdiscount_config_checkin_manufacturerfilter';
MLI18n::gi()->{'cdiscount_config_account_emailtemplate'} = 'Promotion Email Template';
MLI18n::gi()->{'cdiscount_config_account_emailtemplate_sender'} = 'Example Shop';
MLI18n::gi()->{'cdiscount_config_account_emailtemplate_sender_email'} = 'example@onlineshop.com';
MLI18n::gi()->{'cdiscount_config_account_emailtemplate_subject'} = 'Your Order from #SHOPURL#';
MLI18n::gi()->{'cdiscount_config_account_emailtemplate_content'} = '<style>
        <!--body { font: 12px sans-serif; }
        table.ordersummary { width: 100%; border: 1px solid #e8e8e8; }
        table.ordersummary td { padding: 3px 5px; }
        table.ordersummary thead td { background: #cfcfcf; color: #000; font-weight: bold; text-align: center; }
        table.ordersummary thead td.name { text-align: left; }
        table.ordersummary tbody tr.even td { background: #e8e8e8; color: #000; }
        table.ordersummary tbody tr.odd td { background: #f8f8f8; color: #000; }
        table.ordersummary td.price, table.ordersummary td.fprice { text-align: right; white-space: nowrap; }
        table.ordersummary tbody td.qty { text-align: center; }-->
    </style>
    <p>Hello #FIRSTNAME# #LASTNAME#,</p>
    <p>Thank you for your order! The following items were ordered via #MARKETPLACE#:</p>
    #ORDERSUMMARY#
    <p>Shipping costs are included.</p>
    <p>You\\\'ll find more great offers in our shop at <strong>#SHOPURL#</strong>.</p>
    <p>&nbsp;</p>
    <p>Sincerely,</p>
    <p>Your Online Shop Team</p>';
MLI18n::gi()->{'cdiscount_config_account__legend__account'} = 'Login Details';
MLI18n::gi()->{'cdiscount_config_account__legend__tabident'} = '';
MLI18n::gi()->{'cdiscount_config_account__field__tabident__label'} = '{#i18n:ML_LABEL_TAB_IDENT#}';
MLI18n::gi()->{'cdiscount_config_account__field__tabident__help'} = '{#i18n:ML_TEXT_TAB_IDENT#}';
MLI18n::gi()->{'cdiscount_config_account__field__mpusername__label'} = 'Username';
MLI18n::gi()->{'cdiscount_config_account__field__mppassword__label'} = 'Password';
MLI18n::gi()->{'cdiscount_config_prepare__legend__prepare'} = 'Prepare Items';
MLI18n::gi()->{'cdiscount_config_prepare__legend__upload'} = 'cdiscount_config_prepare__legend__upload';
MLI18n::gi()->{'cdiscount_config_prepare__field__prepare.status__label'} = 'cdiscount_config_prepare__field__prepare.status__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__prepare.status__valuehint'} = 'cdiscount_config_prepare__field__prepare.status__valuehint';
MLI18n::gi()->{'cdiscount_config_prepare__field__checkin.status__label'} = 'cdiscount_config_prepare__field__checkin.status__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__checkin.status__valuehint'} = 'cdiscount_config_prepare__field__checkin.status__valuehint';
MLI18n::gi()->{'cdiscount_config_prepare__field__lang__label'} = 'cdiscount_config_prepare__field__lang__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__imagepath__label'} = 'cdiscount_config_prepare__field__imagepath__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__itemcondition__label'} = 'cdiscount_config_prepare__field__itemcondition__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shipping_time__label'} = 'cdiscount_config_prepare__field__shipping_time__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shipping_time_standard__label'} = 'cdiscount_config_prepare__field__shipping_time_standard__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shipping_time_tracked__label'} = 'cdiscount_config_prepare__field__shipping_time_tracked__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shipping_time_registered__label'} = 'cdiscount_config_prepare__field__shipping_time_registered__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shippingtimemin__label'} = 'cdiscount_config_prepare__field__shippingtimemin__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shippingtimemax__label'} = 'cdiscount_config_prepare__field__shippingtimemax__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shippingfeestandard__label'} = 'cdiscount_config_prepare__field__shippingfeestandard__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shippingfeeextrastandard__label'} = 'cdiscount_config_prepare__field__shippingfeeextrastandard__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shippingfeetracked__label'} = 'cdiscount_config_prepare__field__shippingfeetracked__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shippingfeeextratracked__label'} = 'cdiscount_config_prepare__field__shippingfeeextratracked__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shippingfeeregistered__label'} = 'cdiscount_config_prepare__field__shippingfeeregistered__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__shippingfeeextraregistered__label'} = 'cdiscount_config_prepare__field__shippingfeeextraregistered__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__itemcountry__label'} = 'cdiscount_config_prepare__field__itemcountry__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__itemcountry__help'} = 'cdiscount_config_prepare__field__itemcountry__help';
MLI18n::gi()->{'cdiscount_config_prepare__field__itemsperpage__label'} = 'cdiscount_config_prepare__field__itemsperpage__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__itemsperpage__help'} = 'cdiscount_config_prepare__field__itemsperpage__help';
MLI18n::gi()->{'cdiscount_config_prepare__field__itemsperpage__hint'} = 'cdiscount_config_prepare__field__itemsperpage__hint';
MLI18n::gi()->{'cdiscount_config_prepare__field__checkin.quantity__label'} = 'cdiscount_config_prepare__field__checkin.quantity__label';
MLI18n::gi()->{'cdiscount_config_prepare__field__checkin.quantity__help'} = 'cdiscount_config_prepare__field__checkin.quantity__help';
MLI18n::gi()->{'cdiscount_config_price__legend__price'} = 'cdiscount_config_price__legend__price';
MLI18n::gi()->{'cdiscount_config_price__field__usevariations__label'} = 'cdiscount_config_price__field__usevariations__label';
MLI18n::gi()->{'cdiscount_config_price__field__usevariations__help'} = 'cdiscount_config_price__field__usevariations__help';
MLI18n::gi()->{'cdiscount_config_price__field__usevariations__valuehint'} = 'cdiscount_config_price__field__usevariations__valuehint';
MLI18n::gi()->{'cdiscount_config_price__field__price__label'} = 'cdiscount_config_price__field__price__label';
MLI18n::gi()->{'cdiscount_config_price__field__price__help'} = 'Please enter a price markup or markdown, either in percentage or fixed amount. Use a minus sign (-) before the amount to denote markdown.';
MLI18n::gi()->{'cdiscount_config_price__field__price.addkind__label'} = '';
MLI18n::gi()->{'cdiscount_config_price__field__price.factor__label'} = '';
MLI18n::gi()->{'cdiscount_config_price__field__price.signal__label'} = 'cdiscount_config_price__field__price.signal__label';
MLI18n::gi()->{'cdiscount_config_price__field__price.signal__hint'} = 'cdiscount_config_price__field__price.signal__hint';
MLI18n::gi()->{'cdiscount_config_price__field__price.signal__help'} = 'cdiscount_config_price__field__price.signal__help';
MLI18n::gi()->{'cdiscount_config_price__field__priceoptions__label'} = 'cdiscount_config_price__field__priceoptions__label';
MLI18n::gi()->{'cdiscount_config_price__field__price.group__label'} = '';
MLI18n::gi()->{'cdiscount_config_price__field__price.usespecialoffer__label'} = 'cdiscount_config_price__field__price.usespecialoffer__label';
MLI18n::gi()->{'cdiscount_config_price__field__exchangerate_update__label'} = 'cdiscount_config_price__field__exchangerate_update__label';
MLI18n::gi()->{'cdiscount_config_price__field__exchangerate_update__valuehint'} = 'cdiscount_config_price__field__exchangerate_update__valuehint';
MLI18n::gi()->{'cdiscount_config_price__field__exchangerate_update__help'} = '{#i18n:form_config_orderimport_exchangerate_update_help#}';
MLI18n::gi()->{'cdiscount_config_price__field__exchangerate_update__alert'} = '{#i18n:form_config_orderimport_exchangerate_update_alert#}';
MLI18n::gi()->{'cdiscount_config_sync__legend__sync'} = 'cdiscount_config_sync__legend__sync';
MLI18n::gi()->{'cdiscount_config_sync__field__stocksync.tomarketplace__label'} = 'cdiscount_config_sync__field__stocksync.tomarketplace__label';
MLI18n::gi()->{'cdiscount_config_sync__field__stocksync.tomarketplace__help'} = 'cdiscount_config_sync__field__stocksync.tomarketplace__help';
MLI18n::gi()->{'cdiscount_config_sync__field__stocksync.frommarketplace__label'} = 'cdiscount_config_sync__field__stocksync.frommarketplace__label';
MLI18n::gi()->{'cdiscount_config_sync__field__stocksync.frommarketplace__help'} = 'cdiscount_config_sync__field__stocksync.frommarketplace__help';
MLI18n::gi()->{'cdiscount_config_sync__field__inventorysync.price__label'} = 'cdiscount_config_sync__field__inventorysync.price__label';
MLI18n::gi()->{'cdiscount_config_sync__field__inventorysync.price__help'} = 'cdiscount_config_sync__field__inventorysync.price__help';
MLI18n::gi()->{'cdiscount_config_orderimport__legend__importactive'} = 'cdiscount_config_orderimport__legend__importactive';
MLI18n::gi()->{'cdiscount_config_orderimport__legend__mwst'} = 'cdiscount_config_orderimport__legend__mwst';
MLI18n::gi()->{'cdiscount_config_orderimport__legend__orderstatus'} = 'cdiscount_config_orderimport__legend__orderstatus';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.sync__label'} = 'cdiscount_config_orderimport__field__orderstatus.sync__label';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.sync__help'} = 'cdiscount_config_orderimport__field__orderstatus.sync__help';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shop__label'} = '{#i18n:form_config_orderimport_shop_lable#}';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shop__hint'} = '';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shop__help'} = '{#i18n:form_config_orderimport_shop_help#}';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.shipped__label'} = 'cdiscount_config_orderimport__field__orderstatus.shipped__label';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.shipped__help'} = 'cdiscount_config_orderimport__field__orderstatus.shipped__help';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.cancelled__label'} = 'cdiscount_config_orderimport__field__orderstatus.cancelled__label';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.cancelled__help'} = 'cdiscount_config_orderimport__field__orderstatus.cancelled__help';
MLI18n::gi()->{'cdiscount_config_orderimport__field__mwst.fallback__label'} = 'cdiscount_config_orderimport__field__mwst.fallback__label';
MLI18n::gi()->{'cdiscount_config_orderimport__field__mwst.fallback__hint'} = 'cdiscount_config_orderimport__field__mwst.fallback__hint';
MLI18n::gi()->{'cdiscount_config_orderimport__field__mwst.fallback__help'} = 'cdiscount_config_orderimport__field__mwst.fallback__help';
MLI18n::gi()->{'cdiscount_config_orderimport__field__importactive__label'} = 'cdiscount_config_orderimport__field__importactive__label';
MLI18n::gi()->{'cdiscount_config_orderimport__field__importactive__hint'} = '';
MLI18n::gi()->{'cdiscount_config_orderimport__field__importactive__help'} = 'cdiscount_config_orderimport__field__importactive__help';
MLI18n::gi()->{'cdiscount_config_orderimport__field__import__label'} = '';
MLI18n::gi()->{'cdiscount_config_orderimport__field__preimport.start__label'} = 'cdiscount_config_orderimport__field__preimport.start__label';
MLI18n::gi()->{'cdiscount_config_orderimport__field__preimport.start__hint'} = 'cdiscount_config_orderimport__field__preimport.start__hint';
MLI18n::gi()->{'cdiscount_config_orderimport__field__preimport.start__help'} = 'cdiscount_config_orderimport__field__preimport.start__help';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.open__label'} = 'cdiscount_config_orderimport__field__orderstatus.open__label';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.open__hint'} = '';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderstatus.open__help'} = 'cdiscount_config_orderimport__field__orderstatus.open__help';
MLI18n::gi()->{'cdiscount_config_orderimport__field__customergroup__label'} = 'cdiscount_config_orderimport__field__customergroup__label';
MLI18n::gi()->{'cdiscount_config_orderimport__field__customergroup__help'} = 'cdiscount_config_orderimport__field__customergroup__help';
MLI18n::gi()->{'cdiscount_config_emailtemplate__legend__mail'} = 'cdiscount_config_emailtemplate__legend__mail';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.send__label'} = 'cdiscount_config_emailtemplate__field__mail.send__label';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.send__help'} = 'cdiscount_config_emailtemplate__field__mail.send__help';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.originator.name__label'} = 'cdiscount_config_emailtemplate__field__mail.originator.name__label';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.originator.adress__label'} = 'cdiscount_config_emailtemplate__field__mail.originator.adress__label';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.subject__label'} = 'cdiscount_config_emailtemplate__field__mail.subject__label';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.content__label'} = 'cdiscount_config_emailtemplate__field__mail.content__label';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.content__hint'} = 'cdiscount_config_emailtemplate__field__mail.content__hint';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.copy__label'} = 'cdiscount_config_emailtemplate__field__mail.copy__label';
MLI18n::gi()->{'cdiscount_config_emailtemplate__field__mail.copy__help'} = 'cdiscount_config_emailtemplate__field__mail.copy__help';
