<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'cdiscount_inventory_listing_quantity'} = 'cdiscount_inventory_listing_quantity';
MLI18n::gi()->{'cdiscount_inventory_listing_status'} = 'cdiscount_inventory_listing_status';
MLI18n::gi()->{'cdiscount_inventory_listing_status_new'} = 'cdiscount_inventory_listing_status_new';
MLI18n::gi()->{'cdiscount_inventory_listing_status_update'} = 'cdiscount_inventory_listing_status_update';
MLI18n::gi()->{'cdiscount_inventory_listing_status_waiting'} = 'cdiscount_inventory_listing_status_waiting';
MLI18n::gi()->{'cdiscount_inventory_listing_status_waiting_update'} = 'cdiscount_inventory_listing_status_waiting_update';
MLI18n::gi()->{'cdiscount_inventory_listing_status_active'} = 'cdiscount_inventory_listing_status_active';
