<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameRicardo'} = 'sModuleNameRicardo';
MLI18n::gi()->{'ricardo_articles_fee'} = 'ricardo_articles_fee';
MLI18n::gi()->{'ricardo_articles_fee_process'} = 'ricardo_articles_fee_process';
MLI18n::gi()->{'ricardo_inventory_listing_lastSyncTime'} = 'ricardo_inventory_listing_lastSyncTime';
MLI18n::gi()->{'ricardo_inventory_listing_itemId'} = 'ricardo_inventory_listing_itemId';
MLI18n::gi()->{'ricardo_inventory_listing_marketplaceTitle'} = 'ricardo_inventory_listing_marketplaceTitle';
MLI18n::gi()->{'ricardo_inventory_listing_auction_has_bids'} = 'ricardo_inventory_listing_auction_has_bids';
MLI18n::gi()->{'ricardo_inventory_listing_auction_has_bids_tooltip'} = 'ricardo_inventory_listing_auction_has_bids_tooltip';
