<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameRicardo'} = 'Ricardo';
MLI18n::gi()->{'ricardo_articles_fee'} = 'ricardo_articles_fee';
MLI18n::gi()->{'ricardo_articles_fee_process'} = 'ricardo_articles_fee_process';
MLI18n::gi()->{'ricardo_inventory_listing_lastSyncTime'} = 'Dernière synchronisation';
MLI18n::gi()->{'ricardo_inventory_listing_itemId'} = 'Référence';
MLI18n::gi()->{'ricardo_inventory_listing_marketplaceTitle'} = 'Nom sur Ricardo';
MLI18n::gi()->{'ricardo_inventory_listing_auction_has_bids'} = 'ricardo_inventory_listing_auction_has_bids';
MLI18n::gi()->{'ricardo_inventory_listing_auction_has_bids_tooltip'} = 'ricardo_inventory_listing_auction_has_bids_tooltip';
MLI18n::gi()->{'ricardo_inventory_listing_status'} = 'ricardo_inventory_listing_status';
