<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Fyndiq_CheckinForm__Price'} = 'Fyndiq_CheckinForm__Price';
MLI18n::gi()->{'Fyndiq_CheckinForm__Amount'} = 'Fyndiq_CheckinForm__Amount';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShippingTime'} = 'Fyndiq_CheckinForm__ShippingTime';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShopPrice'} = 'Fyndiq_CheckinForm__ShopPrice';
MLI18n::gi()->{'Fyndiq_CheckinForm__SuggestedPrice'} = 'Fyndiq_CheckinForm__SuggestedPrice';
MLI18n::gi()->{'Fyndiq_CheckinForm__HitPrice'} = 'Fyndiq_CheckinForm__HitPrice';
MLI18n::gi()->{'Fyndiq_CheckinForm__AvailibleAmount'} = 'Fyndiq_CheckinForm__AvailibleAmount';
MLI18n::gi()->{'Fyndiq_CheckinForm__SuggestedAmount'} = 'Fyndiq_CheckinForm__SuggestedAmount';
MLI18n::gi()->{'Fyndiq_CheckinForm__Condition'} = 'Fyndiq_CheckinForm__Condition';
MLI18n::gi()->{'Fyndiq_CheckinForm__ListingType'} = 'Fyndiq_CheckinForm__ListingType';
MLI18n::gi()->{'Fyndiq_CheckinForm__Conditions__new'} = 'Fyndiq_CheckinForm__Conditions__new';
MLI18n::gi()->{'Fyndiq_CheckinForm__Conditions__not_specified'} = 'Fyndiq_CheckinForm__Conditions__not_specified';
MLI18n::gi()->{'Fyndiq_CheckinForm__Conditions__used'} = 'Fyndiq_CheckinForm__Conditions__used';
MLI18n::gi()->{'Fyndiq_CheckinForm__BuyingMode'} = 'Fyndiq_CheckinForm__BuyingMode';
MLI18n::gi()->{'Fyndiq_CheckinForm__BuyingModes__buy_it_now'} = 'Fyndiq_CheckinForm__BuyingModes__buy_it_now';
MLI18n::gi()->{'Fyndiq_CheckinForm__BuyingModes__auction'} = 'Fyndiq_CheckinForm__BuyingModes__auction';
MLI18n::gi()->{'Fyndiq_CheckinForm__BuyingModes__classified'} = 'Fyndiq_CheckinForm__BuyingModes__classified';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShippingMode'} = 'Fyndiq_CheckinForm__ShippingMode';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShippingModes__custom'} = 'Fyndiq_CheckinForm__ShippingModes__custom';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShippingModes__not_specified'} = 'Fyndiq_CheckinForm__ShippingModes__not_specified';
