<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Dawanda_CheckinForm__Price'} = 'Dawanda_CheckinForm__Price';
MLI18n::gi()->{'Dawanda_CheckinForm__Amount'} = 'Dawanda_CheckinForm__Amount';
MLI18n::gi()->{'Dawanda_CheckinForm__ShippingTime'} = 'Dawanda_CheckinForm__ShippingTime';
MLI18n::gi()->{'Dawanda_CheckinForm__ShopPrice'} = 'Dawanda_CheckinForm__ShopPrice';
MLI18n::gi()->{'Dawanda_CheckinForm__SuggestedPrice'} = 'Dawanda_CheckinForm__SuggestedPrice';
MLI18n::gi()->{'Dawanda_CheckinForm__HitPrice'} = 'Dawanda_CheckinForm__HitPrice';
MLI18n::gi()->{'Dawanda_CheckinForm__AvailibleAmount'} = 'Dawanda_CheckinForm__AvailibleAmount';
MLI18n::gi()->{'Dawanda_CheckinForm__SuggestedAmount'} = 'Dawanda_CheckinForm__SuggestedAmount';
