<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_config_general_autosync'} = 'Automatic synchronization via CronJob (recommended)';
MLI18n::gi()->{'ebay_config_general_nosync'} = 'No synchronization';
MLI18n::gi()->{'ebay_config_account_title'} = 'Login Details';
MLI18n::gi()->{'ebay_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'ebay_config_account_price'} = 'Price Calculation';
MLI18n::gi()->{'ebay_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'ebay_config_account_orderimport'} = 'Order Import';
MLI18n::gi()->{'ebay_config_account_emailtemplate'} = 'Promotion Email Template';
MLI18n::gi()->{'ebay_config_account_producttemplate'} = 'Product Template';
MLI18n::gi()->{'ebay_configform_prepare_hitcounter_values__NoHitCounter'} = 'No hit counter';
MLI18n::gi()->{'ebay_configform_prepare_hitcounter_values__BasicStyle'} = 'Basic style';
MLI18n::gi()->{'ebay_configform_prepare_hitcounter_values__RetroStyle'} = 'Retro style';
MLI18n::gi()->{'ebay_configform_prepare_hitcounter_values__HiddenStyle'} = 'Hidden';
MLI18n::gi()->{'ebay_configform_prepare_gallerytype_values__None'} = 'None';
MLI18n::gi()->{'ebay_configform_prepare_gallerytype_values__Gallery'} = 'Gallery';
MLI18n::gi()->{'ebay_configform_prepare_gallerytype_values__Plus'} = 'Plus';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__0'} = 'Same day';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__1'} = '1 day';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__2'} = '2 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__3'} = '3 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__4'} = '4 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__5'} = '5 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__6'} = '6 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__7'} = '7days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__8'} = '8 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__9'} = '9 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__10'} = '10 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__11'} = '11 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__12'} = '12 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__13'} = '13 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__14'} = '14 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__15'} = '15 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__16'} = '16 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__17'} = '17 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__18'} = '18 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__19'} = '19 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__20'} = '20 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__21'} = '21 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__22'} = '22 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__23'} = '23 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__24'} = '24 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__25'} = '25 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__26'} = '26 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__27'} = '27 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__28'} = '28 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__29'} = '29 days';
MLI18n::gi()->{'ebay_configform_prepare_dispatchtimemax_values__30'} = '30 days';
MLI18n::gi()->{'ebay_configform_price_chinese_quantityinfo'} = 'For auctions, the quantity can only be set to 1. ';
MLI18n::gi()->{'ebay_configform_account_sitenotselected'} = 'Please choose the eBay Site first';
MLI18n::gi()->{'ebay_configform_orderstatus_sync_values__auto'} = '{#i18n:ebay_config_general_autosync#}';
MLI18n::gi()->{'ebay_configform_orderstatus_sync_values__no'} = '{#i18n:ebay_config_general_nosync#}';
MLI18n::gi()->{'ebay_configform_sync_values__auto'} = '{#i18n:ebay_config_general_autosync#}';
MLI18n::gi()->{'ebay_configform_sync_values__no'} = '{#i18n:ebay_config_general_nosync#}';
MLI18n::gi()->{'ebay_configform_stocksync_values__rel'} = 'Orders reduce Shop inventory (recommended)';
MLI18n::gi()->{'ebay_configform_stocksync_values__no'} = '{#i18n:ebay_config_general_nosync#}';
MLI18n::gi()->{'ebay_configform_pricesync_values__auto'} = '{#i18n:ebay_config_general_autosync#}';
MLI18n::gi()->{'ebay_configform_pricesync_values__no'} = '{#i18n:ebay_config_general_nosync#}';
MLI18n::gi()->{'ebay_configform_sync_chinese_values__auto'} = '{#i18n:ebay_config_general_autosync#}';
MLI18n::gi()->{'ebay_configform_sync_chinese_values__abs'} = 'Orders / editing items will synchronize eBay and Shop inventory';
MLI18n::gi()->{'ebay_configform_sync_chinese_values__rel'} = 'Orders / editing items changes the eBay inventory';
MLI18n::gi()->{'ebay_configform_sync_chinese_values__onlydecr'} = 'Orders / reducing item count will reduce eBay inventory (no restocking)';
MLI18n::gi()->{'ebay_configform_sync_chinese_values__no'} = '{#i18n:ebay_config_general_nosync#}';
MLI18n::gi()->{'ebay_configform_orderimport_payment_values__textfield__title'} = 'From textfield';
MLI18n::gi()->{'ebay_configform_orderimport_payment_values__textfield__textoption'} = '1';
MLI18n::gi()->{'ebay_configform_orderimport_payment_values__matching__title'} = 'Automatic allocation';
MLI18n::gi()->{'ebay_configform_orderimport_shipping_values__textfield__title'} = 'From textfield';
MLI18n::gi()->{'ebay_configform_orderimport_shipping_values__textfield__textoption'} = '1';
MLI18n::gi()->{'ebay_configform_orderimport_shipping_values__matching__title'} = 'Automatic allocation';
MLI18n::gi()->{'ebay_config_sync_inventory_import__true'} = 'Yes';
MLI18n::gi()->{'ebay_config_sync_inventory_import__false'} = 'No';
MLI18n::gi()->{'ebay_config_account_emailtemplate_sender'} = 'Example Shop';
MLI18n::gi()->{'ebay_config_account_emailtemplate_sender_email'} = 'example@onlineshop.com';
MLI18n::gi()->{'ebay_config_account_emailtemplate_subject'} = 'Your Order from #SHOPURL#';
MLI18n::gi()->{'ebay_config_producttemplate_content'} = 'ebay_config_producttemplate_content';
MLI18n::gi()->{'ebay_config_emailtemplate_content'} = ' <style><!--
body {
    font: 12px sans-serif;
}
table.ordersummary {
	width: 100%;
	border: 1px solid #e8e8e8;
}
table.ordersummary td {
	padding: 3px 5px;
}
table.ordersummary thead td {
	background: #cfcfcf;
	color: #000;
	font-weight: bold;
	text-align: center;
}
table.ordersummary thead td.name {
	text-align: left;
}
table.ordersummary tbody tr.even td {
	background: #e8e8e8;
	color: #000;
}
table.ordersummary tbody tr.odd td {
	background: #f8f8f8;
	color: #000;
}
table.ordersummary td.price,
table.ordersummary td.fprice {
	text-align: right;
	white-space: nowrap;
}
table.ordersummary tbody td.qty {
	text-align: center;
}
--></style>
<p>Hello #FIRSTNAME# #LASTNAME#,</p>
<p>Thank you for your order! The following items were purchased via #MARKETPLACE#:</p>
#ORDERSUMMARY#
<p>Shipping costs are included.</p>
<p>&nbsp;</p>
<p>Sincerely,</p>
<p>Your Online Shop Team</p>';
MLI18n::gi()->{'ebay_config_account__legend__account'} = 'Login Details';
MLI18n::gi()->{'ebay_config_account__legend__tabident'} = '';
MLI18n::gi()->{'ebay_config_account__field__tabident__label'} = '{#i18n:ML_LABEL_TAB_IDENT#}';
MLI18n::gi()->{'ebay_config_account__field__tabident__help'} = '{#i18n:ML_TEXT_TAB_IDENT#}';
MLI18n::gi()->{'ebay_config_account__field__username__label'} = 'eBay Member Name';
MLI18n::gi()->{'ebay_config_account__field__username__help'} = 'Please enter your eBay username.';
MLI18n::gi()->{'ebay_config_account__field__username__hint'} = '';
MLI18n::gi()->{'ebay_config_account__field__password__label'} = 'eBay Password';
MLI18n::gi()->{'ebay_config_account__field__password__help'} = 'Please enter your eBay password.';
MLI18n::gi()->{'ebay_config_account__field__token__label'} = 'eBay Token';
MLI18n::gi()->{'ebay_config_account__field__token__help'} = 'To apply for a new eBay token, please click the button.<br>
If this does not open eBay in a new window, please deactivate your popup blocker.<br><br>
The token is needed to allow you to access eBay via the magnalister interface.<br>
Please follow the steps in the eBay window to apply for a token and connect your online Shop with eBay via magnalister.';
MLI18n::gi()->{'ebay_config_account__field__site__label'} = 'eBay Site';
MLI18n::gi()->{'ebay_config_account__field__site__help'} = 'For which country should your products be listed?';
MLI18n::gi()->{'ebay_config_account__field__currency__label'} = 'Currency';
MLI18n::gi()->{'ebay_config_account__field__currency__help'} = 'The currency that your eBay items will be listed under. Please choose a currency corresponding to the specific eBay site.';
MLI18n::gi()->{'ebay_config_prepare__legend__prepare'} = 'Prepare Items';
MLI18n::gi()->{'ebay_config_prepare__legend__location__title'} = 'Location';
MLI18n::gi()->{'ebay_config_prepare__legend__location__info'} = 'Please enter the location of your Shop. This will be visible as the Seller Address on eBay.';
MLI18n::gi()->{'ebay_config_prepare__legend__pictures'} = 'Image settings';
MLI18n::gi()->{'ebay_config_prepare__legend__payment'} = '<b>Settings for Payment Methods</b>';
MLI18n::gi()->{'ebay_config_prepare__legend__returnpolicy'} = '<b>Return Policy</b>';
MLI18n::gi()->{'ebay_config_prepare__legend__shipping'} = 'Shipping';
MLI18n::gi()->{'ebay_config_prepare__legend__misc'} = '<b>Miscellaneous</b>';
MLI18n::gi()->{'ebay_config_prepare__legend__upload'} = 'Item Upload Presets';
MLI18n::gi()->{'ebay_config_prepare__field__prepare.status__label'} = 'Status Filter';
MLI18n::gi()->{'ebay_config_prepare__field__prepare.status__valuehint'} = 'Only transfer active items';
MLI18n::gi()->{'ebay_config_prepare__field__postalcode__label'} = 'Postcode';
MLI18n::gi()->{'ebay_config_prepare__field__postalcode__help'} = 'Please enter the location of your Shop. This will be visible as the Seller Address on eBay. ';
MLI18n::gi()->{'ebay_config_prepare__field__location__label'} = 'City';
MLI18n::gi()->{'ebay_config_prepare__field__country__label'} = 'Country';
MLI18n::gi()->{'ebay_config_prepare__field__mwst__label'} = 'VAT';
MLI18n::gi()->{'ebay_config_prepare__field__mwst__help'} = 'VAT rate that will apply to items sold via eBay. Please only fill this out if you have a commercial seller account with eBay.';
MLI18n::gi()->{'ebay_config_prepare__field__mwst__hint'} = 'Tax rate for commercial sellers in %';
MLI18n::gi()->{'ebay_config_prepare__field__conditionid__label'} = 'Item Condition';
MLI18n::gi()->{'ebay_config_prepare__field__conditionid__help'} = 'Item Condition presets (for eBay categories that require or provide the option for this). Not every description is valid for every category; after choosing the category please ensure the Item Condition is correct. ';
MLI18n::gi()->{'ebay_config_prepare__field__lang__label'} = 'Language';
MLI18n::gi()->{'ebay_config_prepare__field__lang__help'} = 'Language for item names and descriptions. Your Shop allows names and descriptions to be given in more than one language; for uploading to eBay, one language must be selected. 
Error reports from eBay will also be made in the selected language.';
MLI18n::gi()->{'ebay_config_prepare__field__dispatchtimemax__label'} = 'Lead Time';
MLI18n::gi()->{'ebay_config_prepare__field__dispatchtimemax__help'} = 'Maximum amount of time required before the item is shipped. This will be visible on eBay.';
MLI18n::gi()->{'ebay_config_prepare__field__topten__label'} = 'Category Quick-Selection';
MLI18n::gi()->{'ebay_config_prepare__field__topten__help'} = 'Show the Quick Select Category under Prepare Items.';
MLI18n::gi()->{'ebay_config_prepare__field__gallerytype__label'} = 'Gallery images';
MLI18n::gi()->{'ebay_config_prepare__field__gallerytype__help'} = '<b>Gallery Images</b><br /><br />
                Gallery images appear in the search result list on eBay. This improves the visibility of your items, and thus also the potential selling outcome.<br /><br />
                <b>Gallery Plus</b><br /><br />
                Gallery Plus means a  pop-up window with a bigger view of the item, when the customer points with the mouse on the item within the search result list. Please note that the image size must be <b>at least 800x800 px</b>.<br /><br />
                <b>eBay Fees</b><br /><br />
                &quot;Gallery Plus&quot; is <span style="color:red">subject to fee on eBay</span> in some categories! RedGecko GmbH does not care responsibility for any eBay fees caused.<br /><br />
                <b>Further information</b><br /><br />
                Please refer to the <a href="http://pages.ebay.com/help/sell/gallery-upgrade.html" target="_blank">eBay help pages</a> for further information.';
MLI18n::gi()->{'ebay_config_prepare__field__gallerytype__hint'} = 'Gallery<br />("Plus" can be <span style="color:red">subject of fee</span> in some categories)';
MLI18n::gi()->{'ebay_config_prepare__field__gallerytype__alert__Plus__title'} = 'Please note';
MLI18n::gi()->{'ebay_config_prepare__field__gallerytype__alert__Plus__content'} = 'Gallery Plus means a  pop-up window with a bigger view of the item, when the customer points with the mouse on the item within the search result list. Please note that the image size must be <b>at least 800x800 px</b>.<br /><br />The usage of <b>Gallery Plus</b> can <span style="color:red">cause extra fees</span> in some eBay categories. See <a href="http://pages.ebay.com/help/sell/gallery-upgrade.html" target="_blank">eBay help page</a> for details.<br /><br />RedGecko GmbH is not responsible for any costs caused.';
MLI18n::gi()->{'ebay_config_prepare__field__variationdimensionforpictures__label'} = 'Picture Pack Variation dimension';
MLI18n::gi()->{'ebay_config_prepare__field__variationdimensionforpictures__help'} = 'If you have variation images stored along with your product data, the Picture Pack will submit them to eBay with the product upload.<br />
                eBay allows only one variation dimension: If you take e.g. color, the main picture on eBay&apos;s product page will change whenever the buyer chooses an other color.<br /><br />
                This setting here is the default value. You can change it in the preparation form for each product.<br />
                If you want to change it afterwards, you have to prepare and upload the product anew.';
MLI18n::gi()->{'ebay_config_prepare__field__paymentmethods__label'} = 'Payment Methods';
MLI18n::gi()->{'ebay_config_prepare__field__paymentmethods__help'} = 'Presets for payment methods (select multiple options by holding cmd/ctrl while clicking). Options are eBay defaults.';
MLI18n::gi()->{'ebay_config_prepare__field__paypal.address__label'} = 'PayPal Email Address';
MLI18n::gi()->{'ebay_config_prepare__field__paypal.address__help'} = 'The emails address provided to eBay for PayPal payments. This is required to upload eBay store items.';
MLI18n::gi()->{'ebay_config_prepare__field__paymentinstructions__label'} = 'Payment Instructions';
MLI18n::gi()->{'ebay_config_prepare__field__paymentinstructions__help'} = 'Please enter text here that should appear in the item page under \'Seller\'s Payment Instructions\'***. Maximum 500 characters (text only, no HTML). ';
MLI18n::gi()->{'ebay_config_prepare__field__shippinglocalcontainer__label'} = 'Inland Shipping';
MLI18n::gi()->{'ebay_config_prepare__field__shippinglocalcontainer__help'} = 'Please choose one or more shipping methods to set as standard. <br /><br />Enter a number under Shipping Costs (without currency specification), or "=WEIGHT" to set the shipping costs according to the item weight.
<div class="ui-dialog-titlebar ">
<span>Discount for Combination Payment and Shipping***</span>
Profile selection for shipping discount. Profiles can be set in your eBay account, under My eBay > Member Account > Settings > Shipping Settings<br /><br />
Here you can also set the rules for special shipping prices (for example, maximum shipping price per order, or free shipping if the item cost is above a certain amount).<br /><br />
<b>Please Note:</b><br />
Order imports will be subject to the rules that are chosen here (we do not receive the information on item settings from eBay).***';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternationalcontainer__label'} = 'International Shipping';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternationalcontainer__help'} = 'Please choose shipping methods to set as standard (or select none).<div class="ui-dialog-titlebar ">
<span>Discount for Combination Payment and Shipping***</span>
Profile selection for shipping discount. Profiles can be set in your eBay account, under My eBay > Member Account > Settings > Shipping Settings<br /><br />
Here you can also set the rules for special shipping prices (for example, maximum shipping price per order, or free shipping if the item cost is above a certain amount).<br /><br />
<b>Please Note:</b><br />
Order imports will be subject to the rules that are chosen here (we do not receive the information on item settings from eBay).***';
MLI18n::gi()->{'ebay_config_prepare__field__shippinglocal__cost'} = 'Shipping Costs';
MLI18n::gi()->{'ebay_config_prepare__field__shippinglocalprofile__option'} = '{#NAME#} ({#AMOUNT#} per additional item)';
MLI18n::gi()->{'ebay_config_prepare__field__shippinglocalprofile__optional__select__false'} = 'Don&apos;t use Shipping Profile';
MLI18n::gi()->{'ebay_config_prepare__field__shippinglocalprofile__optional__select__true'} = 'Use Shipping Profile';
MLI18n::gi()->{'ebay_config_prepare__field__shippinglocaldiscount__label'} = 'Use special shipping price rules';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternationaldiscount__label'} = 'Use special shipping price rules';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternational__cost'} = 'Shipping Costs';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternational__optional__select__false'} = 'Don\'t ship internationally';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternational__optional__select__true'} = 'Ship internationally';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternationalprofile__option'} = '{#NAME#} ({#AMOUNT#} per additional item)';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternationalprofile__notavailible'} = 'Only when `<i>International Shipping</i>` is activated.';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternationalprofile__optional__select__false'} = 'Don&apos;t use Shipping Profile';
MLI18n::gi()->{'ebay_config_prepare__field__shippinginternationalprofile__optional__select__true'} = 'Use Shipping Profile';
MLI18n::gi()->{'ebay_config_prepare__field__returnpolicy.returnsaccepted__label'} = 'Returns Accepted';
MLI18n::gi()->{'ebay_config_prepare__field__returnpolicy.returnswithin__label'} = 'Returns Within ';
MLI18n::gi()->{'ebay_config_prepare__field__returnpolicy.returnswithin__help'} = 'Time period within which returns will be accepted.';
MLI18n::gi()->{'ebay_config_prepare__field__returnpolicy.shippingcostpaidby__label'} = 'Return Shipping Costs';
MLI18n::gi()->{'ebay_config_prepare__field__returnpolicy.description__label'} = 'Return Policy: Further Details';
MLI18n::gi()->{'ebay_config_prepare__field__returnpolicy.description__help'} = 'Please enter here details of your return policy. Maximum 5,000 characters (text only, no HTML).';
MLI18n::gi()->{'ebay_config_prepare__field__usevariations__label'} = 'Variations';
MLI18n::gi()->{'ebay_config_prepare__field__usevariations__help'} = 'Products that are available with variations (such as size or colour) in your Shop will be transferred with these variations to eBay.<br /><br /> The Quantity setting will then apply to each individual variation.<br /><br />
<b>Example:</b> If you have 8 of an item in blue, 5 in green and 2 in black, under Quantity you have selected "Transfer Shop inventory minus value from the right field", and entered "2" in the field, the item will them be available as 6 in blue and 3 in green.<br /><br /><b>Please note:</b>It may occur that a variation you are using (such as size or colour) will also appear in the Attribute Selection for the category. In this case your variation will be used instead of the attribute.';
MLI18n::gi()->{'ebay_config_prepare__field__usevariations__valuehint'} = 'Transfer variations';
MLI18n::gi()->{'ebay_config_prepare__field__useprefilledinfo__label'} = 'Product Information';
MLI18n::gi()->{'ebay_config_prepare__field__useprefilledinfo__help'} = 'Function activated: Show the eBay product information, if found. Only applicable if EAN is used.';
MLI18n::gi()->{'ebay_config_prepare__field__useprefilledinfo__valuehint'} = 'show eBay prefilled Product information';
MLI18n::gi()->{'ebay_config_prepare__field__privatelisting__label'} = 'Private Listings';
MLI18n::gi()->{'ebay_config_prepare__field__privatelisting__help'} = 'Activate this setting to mark listings as \'Private\'. This will make your buyer/bidder list not publicly visible.';
MLI18n::gi()->{'ebay_config_prepare__field__privatelisting__valuehint'} = 'Make buyer/bidder list private';
MLI18n::gi()->{'ebay_config_prepare__field__hitcounter__label'} = 'Hit Counter';
MLI18n::gi()->{'ebay_config_prepare__field__hitcounter__help'} = 'Presets for hit counter for listings.';
MLI18n::gi()->{'ebay_config_prepare__field__imagesize__label'} = 'Image Size';
MLI18n::gi()->{'ebay_config_prepare__field__imagesize__help'} = '<p>Please enter the pixel width for the image as should appear on the Marketplace. The height will be automatically matched based on the original aspect ratio.</p>
<p>The source files will be processed from the image folder {#setting:sSourceImagePath#}, and will be stored in the folder {#setting:sImagePath#} with the selected pixel width for use on the Marketplace.</p>';
MLI18n::gi()->{'ebay_config_prepare__field__imagesize__hint'} = 'Saved under: {#setting:sImagePath#}';
MLI18n::gi()->{'ebay_config_prepare__field__picturepack__label'} = 'Picture Pack';
MLI18n::gi()->{'ebay_config_prepare__field__picturepack__help'} = '                <b>Picture Pack</b><br /><br />
                By activation of the feature &quot;Picture Pack&quot;, you can submit up to 12 pictures for each item. The buyer can view the images in a bigger size and zoom parts of the picture. No special settings on your eBay accounts required.<br /><br />
                <b>Variation Images</b><br /><br />
                If you have variation pictures for an item, they can also be transferred to eBay (up to 12 images per variation).<br /><br />
                <b>Note</b><br /><br />
                magnalister can only process the data your shop system provides. If you shop system doesn&apos;t support variation images, this feature isn&apos;t available in magnalister.<br /><br />
                <b>&quot;Supersized pictures&quot; and und &quot;Zoom&quot;</b><br /><br />
                Please use pictures of a sufficient size to talke advantage of the features &quot;Supersized pictures&quot; and und &quot;Zoom&quot;. If a picture is too small (less than <b>1000px</b> on the longest side), it will be used, but you will see a warning in the Error Log view of magnalister.<br /><br />
                <b>Usage of https addresses for pictures (safe URL&apos;s)</b><br /><br />
                eBay doesn&apos;t allow safe URL&apos;s for pictures, if given directly as address in the item data. Our Picture Pack uses the eBay Picture Service to store pictures, so that safe URL&apos;s are supported.<br /><br />
                <b>Processing duration</b><br /><br />
                With the Picture Pack, pictures are first uploaded to eBay, and then attached to the respective item. This can take 2-5 seconds per image, depending on the image size.<br /><br />
                To have a reasonable processing speed on the shop part, the data are buffered on the magnalister server. Possible error messages from eBay can be seen in magnalister&apos;s Error Log, only when the upload to eBay is completed.<br /><br />
                <b>Update of Pictures on eBay</b><br /><br />
                With the Picture Pack, you need just to change the picture in your shop and upload the Item again to make the change visible on eBay.<br />
                Without it, a picture on eBay changes only if you change the URL of the picture (and then upload the Item).<br /><br />
                <b>Possible fees in eBay part</b><br /><br />
                The usage of Picture Pack is free for the eBay sites Germany and Austria. For other countries, please refer to the eBay help pages or the eBay support of the respective country.<br /><br />
                RedGecko GmbH does not care responsibility for any eBay fees caused.';
MLI18n::gi()->{'ebay_config_prepare__field__picturepack__valuehint'} = 'activate Picture Pack';
MLI18n::gi()->{'ebay_config_prepare__field__productfield.brand__label'} = 'Brand';
MLI18n::gi()->{'ebay_config_price__legend__price'} = 'Price Calculation';
MLI18n::gi()->{'ebay_config_price__legend__fixedprice'} = '<b>Settings for Fixed Price Listings</b>';
MLI18n::gi()->{'ebay_config_price__legend__chineseprice'} = '<b>Auction Settings</b>';
MLI18n::gi()->{'ebay_config_price__field__fixed.quantity__label'} = 'Quantity';
MLI18n::gi()->{'ebay_config_price__field__fixed.quantity__help'} = 'Please enter the amount of an item that should be available on the Marketplace.<br/><br/>You can change the individual quantities under \'Upload\'. In this case it is recommended to deactivate automatic synchronization under \'Synchronize Inventory" > "Stock Sync to Marketplace". <br/><br/>
To avoid overselling, you can activate ‘Transfer shop inventory minus value from the right field’.
                        <br/>
<strong>Example:</strong> Setting the value at 2 gives &#8594; Shop inventory: 10 &#8594; eBay inventory: 8<br/>
                        <br/>
                        <strong>Please note:</strong>If you want to end an item sale on eBay, which is already set as Inactive in the Shop, independent of the actual eBay inventory count, please proceed as follows:<br/>
                        <ul>
                        <li>’Synchronize Inventory”> Set “Stock Sync to Marketplace” to “Automatic Synchronization with CronJob”</li>
                        <li>”Global Configuration” > “Product Status” > Activate setting “If product status is inactive, treat inventory count as 0”***</li>
                        </ul>';
MLI18n::gi()->{'ebay_config_price__field__maxquantity__label'} = 'Quantity Limit';
MLI18n::gi()->{'ebay_config_price__field__maxquantity__help'} = 'Here you can limit the item number that will be transferred to eBay. <br /><br /><strong>Example:</strong>Setting the Quantity to "Transfer Shop Inventory" and entering "20" in Quantity Limit will upload as many items as are available from the Shop inventory, but not more than 20. The inventory synchronization (if activated) will synchronize the eBay inventory and the Shop inventory, as long as the Shop inventory is under 20. If the Shop has more than 20 in stock, the eBay quantity will be set to 20.<br /><br />Leave this field empty or enter 0 if you do not wish to set a limit.
<br /><br /><strong>Please note:</strong>If the Quantity is set to "Flat amount (from the right field)", the limit will have no effect.';
MLI18n::gi()->{'ebay_config_price__field__fixed.price__label'} = 'Price';
MLI18n::gi()->{'ebay_config_price__field__fixed.price__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__fixed.price__help'} = 'Please enter a price markup or markdown, either in percentage or fixed amount. Use a minus sign (-) before the amount to denote markdown.';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.addkind__label'} = '';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.addkind__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.factor__label'} = '';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.factor__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.signal__label'} = 'Decimal Amount';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.signal__hint'} = 'Decimal Amount';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.signal__help'} = 'This textfield shows the decimal value that will appear in the item price on eBay.<br/><br/>
                <strong>Example:</strong> <br />
Value in textfeld: 99 <br />
                Original price: 5.58 <br />
                Final amount: 5.99 <br /><br />
This function is useful when marking the price up or down***. <br/>
Leave this field empty if you do not wish to set any decimal amount. <br/>
The format requires a maximum of 2 numbers.';
MLI18n::gi()->{'ebay_config_price__field__fixed.priceoptions__label'} = 'Price Options';
MLI18n::gi()->{'ebay_config_price__field__fixed.priceoptions__help'} = '{#i18n:configform_price_field_priceoptions_help#}';
MLI18n::gi()->{'ebay_config_price__field__fixed.priceoptions__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.group__label'} = '';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.group__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.quantity__label'} = 'Quantity';
MLI18n::gi()->{'ebay_config_price__field__chinese.price__label'} = 'Start Price';
MLI18n::gi()->{'ebay_config_price__field__chinese.price__help'} = 'Please enter a price markup or markdown, either in percentage or fixed amount. Use a minus sign (-) before the amount to denote markdown. \'Fixed Price\' means that the value entered here will be directly transferred (for example, if you want to always use a start price of 1 euro). ';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.addkind__label'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.addkind__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.factor__label'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.factor__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.signal__label'} = 'Decimal Amount';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.signal__hint'} = 'Decimal Amount';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.signal__help'} = 'This textfield shows the decimal value that will appear in the item price on eBay.<br/><br/>
                <strong>Example:</strong> <br />
Value in textfeld: 99 <br />
                Original price: 5.58 <br />
                Final amount: 5.99 <br /><br />
This function is useful when marking the price up or down***. <br/>
Leave this field empty if you do not wish to set any decimal amount. <br/>
The format requires a maximum of 2 numbers.';
MLI18n::gi()->{'ebay_config_price__field__chinese.priceoptions__label'} = 'Price Options';
MLI18n::gi()->{'ebay_config_price__field__chinese.priceoptions__help'} = '{#i18n:configform_price_field_priceoptions_help#}';
MLI18n::gi()->{'ebay_config_price__field__chinese.priceoptions__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.group__label'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.group__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price__label'} = 'Buy It Now Price';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price__help'} = 'Please enter a price markup or markdown, either in percentage or fixed amount. Use a minus sign (-) before the amount to denote markdown.<br/>
The Buy It Now price must be at least 40&#37; greater than the start price.';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price.addkind__label'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price.addkind__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price.factor__label'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price.factor__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price.signal__label'} = 'Decimal Amount';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price.signal__hint'} = 'Decimal Amount';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.price.signal__help'} = 'This textfield shows the decimal value that will appear in the item price on eBay.<br/><br/>
                <strong>Example:</strong> <br />
Value in textfeld: 99 <br />
                Original price: 5.58 <br />
                Final amount: 5.99 <br /><br />
This function is useful when marking the price up or down***. <br/>
Leave this field empty if you do not wish to set any decimal amount. <br/>
The format requires a maximum of 2 numbers.';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.priceoptions__label'} = 'Price Options';
MLI18n::gi()->{'ebay_config_price__field__chinese.buyitnow.priceoptions__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__buyitnowprice__label'} = 'Activate Buy It Now Price';
MLI18n::gi()->{'ebay_config_price__field__buyitnowprice__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__fixed.duration__label'} = 'Listing Duration';
MLI18n::gi()->{'ebay_config_price__field__fixed.duration__help'} = 'Presets for the duration of fixed-price listings. The settings can be changed under Prepare Item.';
MLI18n::gi()->{'ebay_config_price__field__ebayplus__label'} = 'eBay Plus';
MLI18n::gi()->{'ebay_config_price__field__ebayplus__valuehint'} = 'set eBay Plus when uploading Items';
MLI18n::gi()->{'ebay_config_price__field__ebayplus__help'} = 'eBay Plus is a special feature, at the moment available only for approved merchants in eBay Germany. The feature can be activated in the eBay account.<br /><br />
                           This check box defines a default setting for Item upload from magnalister. It&apos;s clickable if you have the eBay Plus feature active. It has no influence on the setting for all Items on eBay (which can be made only on the eBay website).<br /><br />
                           In case if the check box is not clickable, although you have eBay Plus activated, please save the configuration (this causes magnalister to fetch the current settings from eBay).<br /><br />
                           <b>Notes:</b><ul>
                           <li>There are further requirements for eBay Plus listings (details see <a href="http://verkaeuferportal.ebay.de/ebay-plus" target="_blank">eBay seller&apos;s site</a> (in German)). We don&apos;t get any feedback from eBay, whether these requirements are met, you have to care for it.</li>
                           <li>If you use eBay Plus, please activate order update (in Order Synchronisation) or use the function &quot;Import only &apos;Paid&apos;-marked orders&quot; (in Orders Import). The eBay Plus mark for orders doesn&apos;t appear in the initial order message we get from eBay, but later, as soon as the buyer has chosen the payment and shipping service.</li>
                           <li>It may happen that an eBay Plus order has a shipping service which is not allowed for eBay Plus. In that case, a warning is shown in the order detail view.</li></ul>';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.usespecialoffer__label'} = 'Use special offer prices';
MLI18n::gi()->{'ebay_config_price__field__fixed.price.usespecialoffer__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.usespecialoffer__label'} = 'Use special offer prices';
MLI18n::gi()->{'ebay_config_price__field__chinese.price.usespecialoffer__hint'} = '';
MLI18n::gi()->{'ebay_config_price__field__chinese.duration__label'} = 'Duration of Auction';
MLI18n::gi()->{'ebay_config_price__field__chinese.duration__help'} = 'Presets for the duration of the auction. The settings can be changed under Prepare Item.';
MLI18n::gi()->{'ebay_config_price__field__bestofferenabled__label'} = 'Best Offer';
MLI18n::gi()->{'ebay_config_price__field__bestofferenabled__help'} = 'Activate this function to allow buyers to suggest their own best price for items.<br /><br />
This setting is only valid for \'basic\' items (no variations). If variations are present, this setting will not apply.';
MLI18n::gi()->{'ebay_config_price__field__bestofferenabled__valuehint'} = 'Activate Best Offer (only applies to items without variations)';
MLI18n::gi()->{'ebay_config_price__field__exchangerate_update__label'} = 'Exchange Rate';
MLI18n::gi()->{'ebay_config_price__field__exchangerate_update__valuehint'} = 'Automatically update exchange rate';
MLI18n::gi()->{'ebay_config_price__field__exchangerate_update__help'} = '{#i18n:form_config_orderimport_exchangerate_update_help#}';
MLI18n::gi()->{'ebay_config_price__field__exchangerate_update__alert'} = '{#i18n:form_config_orderimport_exchangerate_update_alert#}';
MLI18n::gi()->{'ebay_config_sync__legend__syncchinese'} = '<b>Auction Settings</b>';
MLI18n::gi()->{'ebay_config_sync__legend__sync__title'} = 'Inventory Synchronization';
MLI18n::gi()->{'ebay_config_sync__legend__sync__info'} = 'Determine which product attributes from your Shop should be automatically updated on eBay.<br /><br /><b>Settings for Fixed-Price Listings</b>';
MLI18n::gi()->{'ebay_config_sync__field__synczerostock__label'} = 'OutOfStock';
MLI18n::gi()->{'ebay_config_sync__field__synczerostock__help'} = 'OutOfStock Help';
MLI18n::gi()->{'ebay_config_sync__field__synczerostock__valuehint'} = 'Activate OutOfStock';
MLI18n::gi()->{'ebay_config_sync__field__syncrelisting__label'} = 'ReList';
MLI18n::gi()->{'ebay_config_sync__field__syncrelisting__help'} = 'ReList Help';
MLI18n::gi()->{'ebay_config_sync__field__syncrelisting__valuehint'} = 'Activate ReList';
MLI18n::gi()->{'ebay_config_sync__field__syncproperties__label'} = 'EAN, MPN & Manufacuter Sync';
MLI18n::gi()->{'ebay_config_sync__field__syncproperties__help'} = 'If you activate the EAN &amp; MPN Synchronisation, you can transfer the corresponding values by one click (using the new synchronisation button left from the order import button) to eBay.<br />
<br />
                           This will also synchronise items not listed on magnalister. The eBay inventory count will be given by the item number, as long as it is identical on both eBay and your web shop (compare at &ldquo;magnalister&rdquo; > &ldquo;eBay&rdquo; > &ldquo;Inventory&rdquo;). The very first synchronisation of this can take up to 24 hours.<br />
                           <br />
                           For <b>Variations</b>, the EAN of the master item is used, if no EAN for the variation is found in the shop database (the most shop systems of the OsCommerce family can&apos;t handle variation EAN&apos;s). If there&apos;s no EAN for the master item, and not all the variations have EAN&apos;s, one of the existing EAN&apos;s will be used also for the remaining variations of the item. If you have the &quot;EAN &amp; MPN Synchronisation&quot; AddOn booked, the values are completed also during the &quot;normal&quot; Price- and Stock Synchronization.<br />
                           <br />
                           *In the EAN field you can also enter the ISBN or UPC. magnalister will automatically recognise which identification number you have provided.<br /><br />
                           <b>Important</b> for osCommerce: Install EAN expansion<br />
                           osCommerce has by default no field for EAN. Please contact us for details, how to extend the shop database and forms, so that the EAN can be handled.<br /><br />
                           <b>Tips:</b><br />
                           eBay allows you to transfer placeholder numbers for EAN and MPN instead of the real number. Products with these placeholder numbers will be ranked lower on eBay, meaning they won&rsquo;t be found as easily.<br />
                           <br />
                           magnalister transfers these eBay placeholder numbers for items where no EAN or MPN have been found, in order to allow you to make changes to existing items.<br />';
MLI18n::gi()->{'ebay_config_sync__field__syncproperties__valuehint'} = 'Activate EAN, MPN & Manufacuter Sync';
MLI18n::gi()->{'ebay_config_sync__field__stocksync.tomarketplace__label'} = 'Stock Sync to Marketplace';
MLI18n::gi()->{'ebay_config_sync__field__stocksync.tomarketplace__hint'} = '';
MLI18n::gi()->{'ebay_config_sync__field__stocksync.tomarketplace__help'} = '<dl>
            <dt>Automatic Synchronization via CronJob (recommended)</dt>
                    <dd>Current eBay stock will be synchronized with shop stock every 4 hours, beginning at 0.00am (with ***, depending on configuration).<br>Values will be transferred from the database, including the changes that occur through an ERP or similar.<br><br>
Manual comparison can be activated by clicking the corresponding button in the magnalister header (left of the shopping cart).<br><br>
Additionally, you can activate the stock comparison through CronJon (flat tariff*** - maximum every 4 hours) with the link:<br>
            <i>{#setting:sSyncInventoryUrl#}</i><br>
Some CronJob requests may be blocked, if they are made through customers not on the flat tariff*** or if the request is made more than once every 4 hours. 
</dd>
                            <dt>Editing orders / items will synchronize eBay and shop stock. </dt>
                                    <dd>If the Shop inventory is changed because of an order or editing an item, the current shop inventory will then be transferred to eBay.<br>
Changes made only to the database, for example, through an ERP, <b>will not</b> be recorded and transferred!</dd>
                            <dt>Editing orders / items changes the eBay inventory.</dt>
                                    <dd>For example, if a Shop item is purchased twice, the eBay inventory will be reduced by 2.<br />
  If the item amount is changed in the shop under ‘Edit Item’, the difference from the previous amount will be added or subtracted.<br>
                                        Changes made only to the database, for example, through an ERP, <b>will not</b> be recorded and transferred!</dd>
                    </dl>
                    <b>Note:</b> The settings in ‘Configuration’, ‘Adjusting Procedure’ and ‘Inventory Item Count’ will be taken into account.';
MLI18n::gi()->{'ebay_config_sync__field__stocksync.frommarketplace__label'} = 'Stock Sync from Marketplace';
MLI18n::gi()->{'ebay_config_sync__field__stocksync.frommarketplace__hint'} = '';
MLI18n::gi()->{'ebay_config_sync__field__stocksync.frommarketplace__help'} = 'If, for example, an item is purchased 3 times on eBay, the Shop inventory will be reduced by 3.<br /><br />
<strong>Important:</strong>This function will only work if you have Order Imports activated!';
MLI18n::gi()->{'ebay_config_sync__field__inventorysync.price__label'} = 'Item Price';
MLI18n::gi()->{'ebay_config_sync__field__inventorysync.price__hint'} = '';
MLI18n::gi()->{'ebay_config_sync__field__inventorysync.price__help'} = '<dl>
            <dt>Automatic Synchronization via CronJob (recommended)</dt>
                    <dd>The function ‘Automatic Synchronization’ synchronizes the eBay price with the Shop price every 4 hours, beginning at 0.00am (with ***, depending on configuration).<br>Values will be transferred from the database, including the changes that occur through an ERP or similar.<br><br>
Manual comparison can be activated by clicking the corresponding button in the magnalister header (left of the shopping cart).<br><br>
Additionally, you can activate the stock comparison through CronJon (flat tariff*** - maximum every 4 hours) with the link:<br>
            <i>{#setting:sSyncInventoryUrl#}</i><br>
Some CronJob requests may be blocked, if they are made through customers not on the flat tariff*** or if the request is made more than once every 4 hours. 
</dd>
                            <dt>Editing orders / items will synchronize eBay and Shop price. </dt>
                                    <dd>If the Shop price is changed when editing an item, the current Shop price will then be transferred to eBay.<br>
Changes made only to the database, for example, through an ERP, <b>will not</b> be recorded and transferred!</dd>
                            <dt>Editing items changes the eBay price.</dt>
                                    <dd>If the item price is changed in the Shop under ‘Edit Item’, the current item price will be transferred to eBay.<br>
                                        Changes made only to the database, for example, through an ERP, <b>will not</b> be recorded and transferred!</dd>
                    </dl>
                    <b>Note:</b> The settings in ‘Configuration’, ‘Adjusting Procedure’ and ‘Inventory Item Count’ will be taken into account.
';
MLI18n::gi()->{'ebay_config_sync__field__inventory.import__label'} = 'Synchronize Non-Shop Items***';
MLI18n::gi()->{'ebay_config_sync__field__inventory.import__help'} = 'Synchronize items that are not set up on magnalister?<br/><br/>When this function is activated, every item offered through your eBay account will be uploaded to the magnalister database each night. These will be visible in the plugin under \'Listings\'.<br/><br/>
The price and inventory synchronization also applies to these items, as long as the SKU on eBay matches the item number in the Shop. <br/><br/>To ensure this functions correctly, please set \'Item Number (Shop) = SKU (Marketplace)\' under Global Configurations > Synchronize Number Range***.<br/>Please note that if you change this number range, this will need to be matched again to the Marketplace, to ensure synchronization occurs correctly.<br/>This function is currently not available for non-Shop items*** with variations set up.';
MLI18n::gi()->{'ebay_config_sync__field__chinese.stocksync.tomarketplace__label'} = 'Stock Sync to Marketplace';
MLI18n::gi()->{'ebay_config_sync__field__chinese.stocksync.tomarketplace__help'} = '<dl>
                                <dt>Automatic synchronisation by CronJob (recommended)</dt>
                                    <dd>The function "Automatic Synchronisation by CronJob" checks the shop stock every 4 hours, and deletes eBay Auctions for Items which are no longer available in the shop.<br /><br />
                                        By this procedure, the database values are checked for changes. The new data will be submitted, also when the changes had been set
                                        by an inventory management system.<br><br>
                                        You can manually synchronize stock changes, by clicking the assigned button in the magnalister-header, next left to the ant-logo.<br><br>
                                        Additionally, you can synchronize stock changes, by setting a own cronjob to your following shop-link:<br>
                                        <i>http://www.YourShop.com/magnaCallback.php?do=SyncInventory</i><br><br>
                                        Setting an own cronjob is permitted for customers within the service plan "Flat", only.<br><br>
                                        Own cronjob-calls, exceeding a quarter of an hour, or calls from customers, who are not within the service plan "Flat", will be blocked.                                             
                                <dt>Order / stock quantity reduction</dt>
                                    <dd>If the stock is decreased to 0 by an Order in the shop, or by by editing the item in shop, the resp. eBay auction is deleted.
                                    <br>Changes within the database only (e.g. by an inventory management system), will <b>not</b> be captured and submitted!</dd>
                            </dl><br>
                            <b>Notice:</b> <ul><li>As soon as Bids have been made for an Auction, it cannot be deleted.</li></ul>';
MLI18n::gi()->{'ebay_config_sync__field__chinese.stocksync.frommarketplace__label'} = 'Stock Sync from Marketplace';
MLI18n::gi()->{'ebay_config_sync__field__chinese.stocksync.frommarketplace__help'} = 'For example, if an item is purchased three times on eBay, the Shop inventory will be reduced by 3.';
MLI18n::gi()->{'ebay_config_sync__field__chinese.inventorysync.price__label'} = 'Item Price';
MLI18n::gi()->{'ebay_config_sync__field__chinese.inventorysync.price__help'} = '<dl>
                                <dt>Automatic Synchronisation by CronJob</dt>
                                    <dd>The function "Automatic Synchronisation by CronJob" equalizes the current _#_platformName_#_-price with the shop-price every 4 hours (starts at 0 pm).<br /><br />
                                        By this procedure, the database values are checked for changes. The new data will be submitted, also when the changes had been set
                                        by an inventory management system.<br/><br/>
                                        You can manually synchronize price changes, by clicking the assigned button in the magnalister-header, next left to the ant-logo.<br/><br/>
                                        Additionally, you can synchronize price changes, by setting a own cronjob to your following shop-link:<br/>
                                        <i>http://www.YourShop.com/magnaCallback.php?do=SyncInventory</i><br/><br/>
                                        Setting an own cronjob is permitted for customers within the service plan "Flat", only.<br/><br/>
                                        Own cronjob-calls, exceeding a quarter of an hour, or calls from customers, who are not within the service plan "Flat", will be blocked.                                             
                            </dl><br/>
                            <b>Notices:</b><ul><li>Settings in "Configuration" &rarr; "Price Calculation" will be provided.</li>
                            <li>As soon as Bids have been made for an Auction, no changes are alowed.</li></ul>';
MLI18n::gi()->{'ebay_config_orderimport__legend__importactive'} = 'Order Import';
MLI18n::gi()->{'ebay_config_orderimport__legend__mwst'} = 'VAT';
MLI18n::gi()->{'ebay_config_orderimport__legend__orderupdate__title'} = 'Order Status Synchronization';
MLI18n::gi()->{'ebay_config_orderimport__legend__orderupdate__info'} = '';
MLI18n::gi()->{'ebay_config_orderimport__legend__orderstatus'} = 'Order Status Synchronization between Shop and eBay';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.sync__label'} = 'Status Synchronization';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.sync__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.sync__help'} = '<dl>
                    <dt>Automatic Synchronization via CronJob (recommended)</dt>
                    <dd>
                        The function ‘Automatic Synchronization with CronJob’ transfers the current Sent Status to eBay every 2 hours.<br/>
                        The status values from the database will be checked and transferred, including when the changes are only made to the database, for example, with an ERP. <br/><br/>
To do a manual comparison, which allows you to edit the order directly in the web shop, set the desired status there and then click ‘refresh’.<br/>
                       Click the button in the magnalister header (left of the shopping cart) to transfer the status immediately.<br/><br/>
Additionally you can activate the Order Status Comparison through CronJob (flat tariff*** - maximum every 4 hours) with the link: <br/><br/>
    <i>{#setting:sSyncOrderStatusUrl#}</i><br/><br/>
Some CronJob requests may be blocked, if they are made through customers not on the flat tariff*** or if the request is made more than once every 4 hours. </dd><dt>Syncronization via Web Shop</dt><dd>This function allows you to transfer the order status directly and exclusively through the order in the Web Shop (not via connected ERPs). Just choose the relevant status and click \'Update\'.</dd></dl>';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.shipped__label'} = 'Confirm Shipping With';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.shipped__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.shipped__help'} = 'Please set the Shop Status that should trigger the \'Shipping Confirmed\' status on eBay.';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.canceled__label'} = 'Undo Confirm Shipment when';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.canceled__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.canceled__help'} = 'Set the state of the order in your shop, which shall undo the  &apos;sent&apos; state on eBay. <br/><br/>
                           Note: This only means that the order state on eBay is no longer &apos;sent&apos;. It doesn&apos;t mean that the order is cancelled.';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.cancelled__label'} = 'Undo Confirm Shipment with';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.cancelled__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.cancelled__help'} = 'Please set the Shop Status that should withdraw the Sent status on eBay.<br/><br/>

Note: Part cancellations are not possible with the eBay API. This function will cancel the complete order and refund the buyer.';
MLI18n::gi()->{'ebay_config_orderimport__field__importonlypaid__label'} = 'Import only „Paid“-marked orders';
MLI18n::gi()->{'ebay_config_orderimport__field__importonlypaid__help'} = '<p>By activating this function, orders from eBay are only being imported, when they are marked on eBay as „Paid“ .
In case of PayPal orders, this happens automatically. In case of money transfer, the order must be set on eBay as „Paid“ accordingly.
</p><p>
<strong>Benefit:</strong>
The imported order is not changeable any more, since it is completed.
Data like shipping address and shipping costs are being submitted from 1:1 as ordered. Surveillance of changes and updating in the online store is not necessary anymore.</p>';
MLI18n::gi()->{'ebay_config_orderimport__field__importonlypaid__alert'} = '<p>By activating this function, orders from eBay are only being imported, when they are marked on eBay as „Paid“ .
In case of PayPal orders, this happens automatically. In case of money transfer, the order must be set on eBay as „Paid“ accordingly.
</p><p>
<strong>Benefit:</strong>
The imported order is not changeable any more, since it is completed.
Data like shipping address and shipping costs are being submitted from 1:1 as ordered. Surveillance of changes and updating in the online store is not necessary anymore.</p>';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.closed__label'} = 'End Order Summary***';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.closed__help'} = 'If an order is set to one of the chosen order statuses, new orders from this customer will not be added to this.<br />
If you do not want an order summary, please select every status.***';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shop__label'} = '{#i18n:form_config_orderimport_shop_lable#}';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shop__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shop__help'} = '{#i18n:form_config_orderimport_shop_help#}';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.paymentmethod__label'} = 'Payment Methods';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.paymentmethod__help'} = '<p>Payment method that will apply to all orders imported from eBay. Standard: “Automatic Allocation”</p>
<p>
If you choose “Automatic Allocation”, magnalister will accept the payment method chosen by the buyer on eBay. This method will then also be added to your payment methods under Shopware > Settings > Payment Methods.</p>
<p>
Additional payment methods can be added to the list via Shopware > Settings > Payment Methods, then activated here.</p>
<p>
This setting is necessary for the invoice and shipping notice, and for editing orders later in the Shop or via ERP.</p>';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.paymentmethod__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__label'} = 'Shipping Methods';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__help'} = 'Shipping method that will apply to all orders imported from eBay. Standard: “Marketplace”<br><br>
This setting is necessary for the invoice and shipping notice, and for editing orders later in the Shop or via ERP.';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__mwstfallback__label'} = 'VAT on Non-Shop*** Items';
MLI18n::gi()->{'ebay_config_orderimport__field__mwstfallback__hint'} = 'The tax rate to apply to non-Shop items on order imports, in %.';
MLI18n::gi()->{'ebay_config_orderimport__field__mwstfallback__help'} = 'If an item is not entered via magnalister, the VAT cannot be calculated. <br />
The percentage value entered here will be taken as the VAT rate for all orders imported to eBay.';
MLI18n::gi()->{'ebay_config_orderimport__field__importactive__label'} = 'Activate Import';
MLI18n::gi()->{'ebay_config_orderimport__field__importactive__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__importactive__help'} = 'Import orders from the Marketplace? <br/><br/>When activated, orders will be automatically imported every hour.<br><br>
You can adjust the automatic import times under<br> 
‘magnalister admin’ > ‘Global Configurations’ > ‘Order Calls’.<br><br>
Manual import can be activated by clicking the corresponding button in the magnalister header (left of the shopping cart).<br><br>Additionally, you can activate the stock comparison through CronJon (flat tariff*** - maximum every 4 hours) with the link:<br>
            <i>{#setting:sImportOrdersUrl#}</i><br>
Some CronJob requests may be blocked, if they are made through customers not on the flat tariff*** or if the request is made more than once every 4 hours. ';
MLI18n::gi()->{'ebay_config_orderimport__field__updateableorderstatus__label'} = 'Update Order Status When';
MLI18n::gi()->{'ebay_config_orderimport__field__updateableorderstatus__help'} = 'Order statuses that can be triggered by eBay payments. 
If the order has a different status, this cannot be changed by an eBay payment.<br /><br />
If you don\'t wish any status changes based on eBay payment, please deactivate the checkbox.<br /><br />
<b>Please note:</b>The status of summarised orders will only be changed when paid in full.';
MLI18n::gi()->{'ebay_config_orderimport__field__updateable.orderstatus__label'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__updateable.orderstatus__help'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__update.orderstatus__label'} = 'Activate Status Update';
MLI18n::gi()->{'ebay_config_orderimport__field__import__label'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__import__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__preimport.start__label'} = 'Start import from';
MLI18n::gi()->{'ebay_config_orderimport__field__preimport.start__hint'} = 'Start time';
MLI18n::gi()->{'ebay_config_orderimport__field__preimport.start__help'} = 'The date from which orders will start being imported. Please note that it is not possible to set this too far in the past, as the data only remains available on eBay for a few weeks.***';
MLI18n::gi()->{'ebay_config_orderimport__field__customergroup__label'} = 'Customer Group';
MLI18n::gi()->{'ebay_config_orderimport__field__customergroup__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__customergroup__help'} = 'The customer group that customers from new orders should be sorted into.';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.open__label'} = 'Order Status in Shop';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.open__hint'} = '';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.open__help'} = 'The status that should be transferred automatically to the Shop after a new order on eBay. 
If you are using a connected dunning process***, it is recommended to set the Order Status to ‘Paid’ (‘Configuration’ > ‘Order Status’).';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.paid__label'} = 'eBay Paid Status in Shop';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.paid__help'} = 'The status that your Shop receives, when payment is made via eBay.';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.carrier.default__label'} = 'Carrier';
MLI18n::gi()->{'ebay_config_orderimport__field__orderstatus.carrier.default__help'} = 'Preselected carriers available in Confirm Shipping on eBay';
MLI18n::gi()->{'ebay_config_emailtemplate__legend__mail'} = 'Promotion Email Template';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.send__label'} = 'Send Email?';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.send__help'} = 'Should an email be sent from your Shop to customers, to promote your Shop?';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.originator.name__label'} = 'Sender Name';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.originator.adress__label'} = 'Sender Email Address';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.subject__label'} = 'Subject';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.content__label'} = 'Email Content';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.content__hint'} = 'List of available placeholders for Subject and Content:
<dl>
                <dt>#FIRSTNAME#</dt>
                        <dd>Buyer\'s first name</dd>
                <dt>#LASTNAME#</dt>
                        <dd>Buyer\'s last name</dd>
                <dt>#EMAIL#</dt>
                        <dd>Buyer\'s email address</dd>
                <dt>#PASSWORD#</dt>
                        <dd>Buyer\'s password for logging into your Shop. Only for customers that are automatically assigned passwords – otherwise the placeholder will be replaced with ‘(as known)’***.</dd>
                <dt>#ORDERSUMMARY#</dt>
                        <dd>Summary of the purchased items. Should be written on a separate line. <br/><i>Cannot be used in the Subject!</i></dd>
                <dt>#ORIGINATOR#</dt>
                        <dd>Sender name</dd>
        </dl>';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.copy__label'} = 'Copy to Sender';
MLI18n::gi()->{'ebay_config_emailtemplate__field__mail.copy__help'} = 'A copy will be sent to the sender email address.';
MLI18n::gi()->{'ebay_config_producttemplate__legend__product__title'} = 'Product Template';
MLI18n::gi()->{'ebay_config_producttemplate__legend__product__info'} = 'Template for Product Description on eBay. (You can change the Editor under \'Global Configurations\' > \'Expert Settings\'.)***';
MLI18n::gi()->{'ebay_config_producttemplate__field__template.name__label'} = 'Product Name Template ';
MLI18n::gi()->{'ebay_config_producttemplate__field__template.name__help'} = '<dl>
                            <dt>Name of the product on eBay</dt>
                             <dd>Decide how to name the product on eBay.
                                 The placeholder <b>#TITLE#</b> will be replaced by the shop\'s product name,
                                 <b>#BASEPRICE#</b> by the price per unit, provided the data exists in the shop.</dd>
                            <dt>Please note:</dt>
                             <dd>The placeholder <b>#BASEPRICE#</b> is mostly not needed, as we submit base prices automatically to eBay, if filled in the Shop and allowed for the eBay category.</dd>
                             <dd>Use this placeholder, if you have non-metric Units (which eBay doesn\'t provide), or if you want to display base prices also in categories where eBay doesn\'t provide it.</dd>
                             <dd>If you use this placeholder, please <b>disable the price synchronization</b>. The Item Title cannot be changed on eBay, and therefore, when the price changes, the base price within the title would no longer conform to it.</dd>
                             <dd><b>#BASEPRICE#</b> is replaced while uploading the product to eBay.</dd>
<dd>eBay cannot handle <b>different base prices for Variations</b>. Therefore, we add it to the Variation titles.</dd>
<dd>Example:
<br />&nbsp;Variation group: fill quantity<ul>
<li>Variation: 0,33 l (3 EUR / l)</li>
<li>Variation: 0.5 l (2.50 EUR / l)</li>
<li>etc.</li></ul></dd>
<dd>In this case, please <b>disable the price synchronization</b> (because the Variation titles cannot be changed on eBay).</dd>
                            </dl>';
MLI18n::gi()->{'ebay_config_producttemplate__field__template.name__hint'} = 'Placeholder: #TITLE# - Product name; #BASEPRICE# - Baseprice';
MLI18n::gi()->{'ebay_config_producttemplate__field__template.content__label'} = 'Product Description Template';
MLI18n::gi()->{'ebay_config_producttemplate__field__template.content__hint'} = 'List of available placeholders for Content:
<dl>
    <dt>#TITLE#</dt>
            <dd>Product Name (Title)</dd>
    <dt>#ARTNR#</dt>
            <dd>Item Number in Shop</dd>
    <dt>#PID#</dt>
            <dd>Product ID in Shop</dd>
    <!--<dt>#PRICE#</dt>
            <dd>Price</dd>
    <dt>#VPE#</dt>
            <dd>Price per packing unit</dd>-->
    <dt>#SHORTDESCRIPTION#</dt>
            <dd>Short description from the Shop</dd>
    <dt>#DESCRIPTION#</dt>
            <dd>Description from the Shop</dd>
    <dt>#PICTURE1#</dt>
            <dd>First product image</dd>
    <dt>#PICTURE2# etc.</dt>
            <dd>Second product image; with #PICTURE3#, #PICTURE4# etc, you can transfer as many pictures as you have available in your Shop.</dd></dl>
    ';
