<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__OK__title'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Prepared Status: Error';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared Status: Open';
MLI18n::gi()->{'Ebay_Productlist_Filter_aPreparedStatus__OK'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Ebay_Productlist_Filter_aPreparedStatus__ERROR'} = 'Prepared Status: Error';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__Chinese'} = 'Chinese auction';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fixed price';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fixed price (eBay store)';
MLI18n::gi()->{'Ebay_Productlist_Header_sPreparedType'} = 'Type of Auction';
MLI18n::gi()->{'Ebay_Productlist_Prepare_sResetValuesButton'} = 'Reset (parts of) Item preparation';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__buttons__ok'} = 'ok';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__buttons__abort'} = 'cancel';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__title'} = 'Reset Item title';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__subtitle'} = 'Reset Item subtitle';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__description'} = 'Reset Item description';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__pictures'} = 'Reset Image selection';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__unprepare'} = 'Undo complete preparation';
