<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_Label_sAutoMatchSuccess'} = 'Amazon_Label_sAutoMatchSuccess';
MLI18n::gi()->{'Amazon_BUTTON_LABEL_DELETE_COMPLETE_LOG'} = 'Amazon_BUTTON_LABEL_DELETE_COMPLETE_LOG';
MLI18n::gi()->{'amazon_prepare_apply'} = 'amazon_prepare_apply';
