<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameHitmeister'} = 'Hitmeister';
MLI18n::gi()->{'hitmeister_label_title'} = 'hitmeister_label_title';
MLI18n::gi()->{'hitmeister_category'} = 'hitmeister_category';
MLI18n::gi()->{'hitmeister_label_item_id'} = 'hitmeister_label_item_id';
MLI18n::gi()->{'hitmeister_search_by_title'} = 'hitmeister_search_by_title';
MLI18n::gi()->{'hitmeister_search_by_ean'} = 'hitmeister_search_by_ean';
MLI18n::gi()->{'hitmeister_label_not_matched'} = 'hitmeister_label_not_matched';
MLI18n::gi()->{'hitmeister_upload_explanation'} = 'hitmeister_upload_explanation';
