<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_inventory_listing_quantity'} = 'hitmeister_inventory_listing_quantity';
MLI18n::gi()->{'hitmeister_inventory_listing_status'} = 'hitmeister_inventory_listing_status';
MLI18n::gi()->{'hitmeister_inventory_listing_status_active'} = 'hitmeister_inventory_listing_status_active';
MLI18n::gi()->{'hitmeister_inventory_listing_status_pending_new'} = 'hitmeister_inventory_listing_status_pending_new';
MLI18n::gi()->{'hitmeister_inventory_listing_status_pending_update'} = 'hitmeister_inventory_listing_status_pending_update';
