<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_prepare_apply_form__legend__details'} = 'hitmeister_prepare_apply_form__legend__details';
MLI18n::gi()->{'hitmeister_prepare_apply_form__legend__categories'} = 'hitmeister_prepare_apply_form__legend__categories';
MLI18n::gi()->{'hitmeister_prepare_apply_form__legend__unit'} = 'hitmeister_prepare_apply_form__legend__unit';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__categories__label'} = 'hitmeister_prepare_apply_form__field__categories__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__primarycategory__label'} = 'hitmeister_prepare_apply_form__field__primarycategory__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__catattributes__label'} = 'hitmeister_prepare_apply_form__field__catattributes__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__catattributes__hint'} = 'hitmeister_prepare_apply_form__field__catattributes__hint';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__title__label'} = 'hitmeister_prepare_apply_form__field__title__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__subtitle__label'} = 'hitmeister_prepare_apply_form__field__subtitle__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__description__label'} = 'hitmeister_prepare_apply_form__field__description__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__images__label'} = 'hitmeister_prepare_apply_form__field__images__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__price__label'} = 'hitmeister_prepare_apply_form__field__price__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__itemcondition__label'} = 'hitmeister_prepare_apply_form__field__itemcondition__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__shippingtime__label'} = 'hitmeister_prepare_apply_form__field__shippingtime__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__itemcountry__label'} = 'hitmeister_prepare_apply_form__field__itemcountry__label';
MLI18n::gi()->{'hitmeister_prepare_apply_form__field__comment__label'} = 'hitmeister_prepare_apply_form__field__comment__label';
MLI18n::gi()->{'hitmeister_prepareform_max_length_part1'} = 'hitmeister_prepareform_max_length_part1';
MLI18n::gi()->{'hitmeister_prepareform_max_length_part2'} = 'hitmeister_prepareform_max_length_part2';
MLI18n::gi()->{'hitmeister_prepareform_category'} = 'hitmeister_prepareform_category';
MLI18n::gi()->{'hitmeister_prepareform_title'} = 'hitmeister_prepareform_title';
MLI18n::gi()->{'hitmeister_prepareform_description'} = 'hitmeister_prepareform_description';
MLI18n::gi()->{'hitmeister_prepareform_category_attribute'} = 'hitmeister_prepareform_category_attribute';
MLI18n::gi()->{'hitmeister_category_no_attributes'} = 'hitmeister_category_no_attributes';
MLI18n::gi()->{'hitmeister_prepare_variations_title'} = 'hitmeister_prepare_variations_title';
