<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_prepare_match_manual__legend__unit'} = 'hitmeister_prepare_match_manual__legend__unit';
MLI18n::gi()->{'hitmeister_prepare_match_manual__legend__manualmatching'} = 'hitmeister_prepare_match_manual__legend__manualmatching';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__price__label'} = 'hitmeister_prepare_match_manual__field__price__label';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__itemcondition__label'} = 'hitmeister_prepare_match_manual__field__itemcondition__label';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__shippingtime__label'} = 'hitmeister_prepare_match_manual__field__shippingtime__label';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__itemcountry__label'} = 'hitmeister_prepare_match_manual__field__itemcountry__label';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__comment__label'} = 'hitmeister_prepare_match_manual__field__comment__label';
MLI18n::gi()->{'form_action_prepare_and_next'} = 'form_action_prepare_and_next';
MLI18n::gi()->{'hitmeister_label_product_at_hitmeister'} = 'hitmeister_label_product_at_hitmeister';
