<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparé avec succès';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparé';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifiée';
MLI18n::gi()->{'Hitmeister_Productlist_Filter_aPreparedStatus__OK'} = 'Préparé avec succès';
MLI18n::gi()->{'Hitmeister_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparé';
MLI18n::gi()->{'Hitmeister_Productlist_Filter_aPreparedStatus__OPEN'} = 'Préparation non vérifiée\'';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Manual_Title_Single'} = 'Hitmeister_Productlist_Match_Manual_Title_Single';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Manual_Title_Multi'} = 'Hitmeister_Productlist_Match_Manual_Title_Multi';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Auto_Title'} = 'Hitmeister_Productlist_Match_Auto_Title';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Auto_Summary'} = 'Hitmeister_Productlist_Match_Auto_Summary';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Manual_Desc'} = 'Hitmeister_Productlist_Match_Manual_Desc';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Auto_Desc'} = 'Hitmeister_Productlist_Match_Auto_Desc';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Auto_Confirm'} = 'Hitmeister_Productlist_Match_Auto_Confirm';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedType__manual'} = 'Hitmeister_Productlist_Cell_aPreparedType__manual';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedType__auto'} = 'Hitmeister_Productlist_Cell_aPreparedType__auto';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedType__apply'} = 'Hitmeister_Productlist_Cell_aPreparedType__apply';
