<div class="row">

    <div class="col-lg-8">
        <?php  if ($grid->getTotalItemsCount() > 0) { ?>
            <?php if ($grid->isMassactions()) { ?>
                <div class="form-group bulk-actions">
                    <div class="col-lg-6">
                        <input id="massaction-submit" type="hidden" name="massaction-submit" value="0"/>
                        <select id="grid-massactions" name="grid-massactions"  class="float-right">
                            <option value=""></option>
                            <?php foreach ($grid->getMessactions() as $massaction) { ?>
                                <option value="<?php echo $massaction['url']; ?>"><?php echo $massaction['label']; ?></option>
                            <?php }?>
                        </select>
                    </div>
                    <div class="col-lg-6">
                        <input type="submit" class="btn btn-default" name="submitMassaction" id="submitMassaction" value="<?php echo L::t("Apply");?>"/>
                    </div>
                </div>
            <?php } ?>
        <?php  } ?>
        <?php if ($grid->getFooterButtons()) { ?>
            <br/><br clear="all"/>
        <?php } ?>
        <?php foreach ($grid->getFooterButtons() as $footerButton) {
                echo "&nbsp;".$footerButton->getHtml();
        } ?>
    </div>

    <div class="col-lg-4">
        <?php if ($grid->getTotalItemsCount() > 5) { ?>
					<span class="pagination">
						<?php echo L::t("Display"); ?>:
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            <?php echo $grid->getLimit() ?>
                            <i class="icon-caret-down"></i>
                        </button>
						<ul class="dropdown-menu">
                            <input id="pagination-items-page" type="hidden" name="pagination"
                                   value="<?php echo $grid->getLimit() ?>"/>
                            <?php foreach ($grid->getLimits() as $k => $value) : ?>
                                <li>
                                    <a href="javascript:void(0);" class="pagination-items-page"
                                       data-items="<?php echo $k; ?>"><?php echo $value; ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        / <?php echo $grid->getTotalItemsCount(); ?> <?php echo L::t("result(s)"); ?>
					</span>
        <?php } ?>
        <input type="hidden" id="paginator-page" name="paginator-page" class="paginator-current-page" value="<?php echo $page; ?>"/>
        <?php if ($totalPages > 1) { ?>
            <ul class="pagination pull-right">
            <li <?php if ($page <= 1) { ?>class="disabled"<?php } ?>>
                <a href="javascript:void(0);" class="pagination-link" data-page="1">
                    <i class="icon-double-angle-left"></i>
                </a>
            </li>
            <li <?php if ($page <= 1) { ?>class="disabled"<?php } ?>>
                <a href="javascript:void(0);" class="pagination-link" data-page="<?php echo $page - 1 ?>">
                    <i class="icon-angle-left"></i>
                </a>
            </li>
            <?php $p = 0 ?>
            <?php while ($p++ < $totalPages) { ?>
                <?php if ($p < $page - 2) { ?>
                    <li class="disabled">
                        <a href="javascript:void(0);">&hellip;</a>
                    </li>
                    <?php $p = $page - 3; ?>
                <?php
                } else {
                    if ($p > $page + 2) {
                        ?>
                        <li class="disabled">
                            <a href="javascript:void(0);">&hellip;</a>
                        </li>
                        <?php $p = $totalPages ?>
                    <?php } else { ?>
                        <li <?php if ($p == $page) { ?>class="active"<?php } ?>>
                            <a href="javascript:void(0);" class="pagination-link"
                               data-page="<?php echo $p ?>"><?php echo $p ?></a>
                        </li>
                    <?php
                    }
                } // if
                ?>
            <?php } // while ?>
            <li <?php if ($page >= $totalPages) { ?>class="disabled"<?php } ?>>
                <a href="javascript:void(0);" class="pagination-link" data-page="<?php echo $page + 1 ?>">
                    <i class="icon-angle-right"></i>
                </a>
            </li>
            <li <?php if ($page >= $totalPages) { ?>class="disabled"<?php } ?>>
                <a href="javascript:void(0);" class="pagination-link" data-page="<?php echo $totalPages; ?>">
                    <i class="icon-double-angle-right"></i>
                </a>
            </li>
        </ul>
        <?php } ?>
    </div>
</div>
<script type="text/javascript">
    $('.pagination-items-page').on('click', function (e) {
        e.preventDefault();
        $('#pagination-items-page').val($(this).data("items")).closest("form").submit();
    });

    $('.pagination-link').on('click', function (e) {
        e.preventDefault();
        $('#paginator-page').val($(this).data("page")).closest("form").submit();
    });

    <?php if ($grid->isMassactions()) { ?>
    $("#submitMassaction").click(function(e) {
        e.preventDefault();
        var newPath = jQuery("#grid-massactions").val();
            <?php if ($grid->getMassactionsType() == Grid::MASSACTION_TYPE_REDIRECT) { ?>
                if (newPath.indexOf('javascript:') == 0) {
                    var actionFunction = newPath.substr(11);
                    window[actionFunction]();
                } else {
                    // redirect
                    document.location.href = newPath;
                }
            <?php } else if ($grid->getMassactionsType() == Grid::MASSACTION_TYPE_SUBMIT) { ?>
                jQuery("#massaction-submit").val(1);
                jQuery("#grid-massactions").closest("form").submit();
            <?php } ?>
    })
    <?php } ?>

</script>

<?php if (!$grid->isShortView()) { ?>
    </div> <?php // end of <div class="panel col-lg-12"> ?>
<?php } ?>
