<div class="content-header">
    <?php foreach ($grid->getButtons() as $button) {
        echo "&nbsp;" . $button->getHtml();
    } ?>
</div>

<div class="panel col-lg-12">
    <div class="panel-heading">
        <?php echo $grid->getHeader(); ?>
        <span class="panel-heading-action">
		    <a id="desc-product-refresh" class="list-toolbar-btn" href="javascript:location.reload();">
			    <span title="" data-toggle="tooltip" class="label-tooltip"
                      data-original-title="Refresh list" data-html="true">
						<i class="process-icon-refresh"></i>
				</span>
            </a>
		</span>
    </div>
    <span class="pull-right">
            <button type="submit" id="submitFilterButton_<?php echo $grid->getGridId(); ?>"
                    name="submitFilter" class="btn btn-default"
                   >
                <i class="icon-search"></i> <?php echo L::t("Search"); ?>
            </button>
            <button type="button" onclick="document.location.href='<?php echo $grid->getGridUrl(); ?>'"
                    name="submitResetButton_<?php echo $grid->getGridId(); ?>"
                    class="btn btn-warning">
                <i class="icon-eraser"></i> <?php echo L::t("Reset"); ?>
            </button>
    </span>

    <script>
        $("#submitFilterButton_<?php echo $grid->getGridId(); ?>").click(function(e){
            e.preventDefault();
            jQuery("#<?php echo $grid->getGridId(); ?>").submit();
        })

    </script>


