<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_Productlist_Label_sMatchAll'} = 'Tous';
MLI18n::gi()->{'Amazon_Productlist_Label_sMatchNotMatched'} = 'pas encore classé';
MLI18n::gi()->{'Amazon_Productlist_Match_Manual_Title_Single'} = 'Classement individuel';
MLI18n::gi()->{'Amazon_Productlist_Match_Manual_Title_Multi'} = 'Classement multiple';
MLI18n::gi()->{'Amazon_Productlist_Match_Auto_Title'} = 'Comparaison automatique';
MLI18n::gi()->{'Amazon_Productlist_Apply_Multi_Title'} = 'Demande multiple - préparation';
MLI18n::gi()->{'Amazon_Productlist_Apply_Single_Title'} = 'Demande - préparation';
MLI18n::gi()->{'Amazon_Productlist_Apply_Requiered_Fields'} = 'Remarque : Les champs marqués <span class="bull">•</span> sont à remplir obligatoirement.
';
MLI18n::gi()->{'Amazon_Productlist_Itemsearch_Select'} = 'Sélectionnez';
MLI18n::gi()->{'Amazon_Productlist_Itemsearch_Title'} = 'Titre d\'Amazon';
MLI18n::gi()->{'Amazon_Productlist_Itemsearch_Category'} = 'Catégorie d\'Amazon';
MLI18n::gi()->{'Amazon_Productlist_Itemsearch_Price'} = 'Hit de prix';
MLI18n::gi()->{'Amazon_Productlist_Itemsearch_Asin'} = 'ASIN';
MLI18n::gi()->{'Amazon_Productlist_Itemsearch_DontMatch'} = 'Ne pas comparer';
MLI18n::gi()->{'Amazon_Productlist_Itemsearch_Search'} = 'Rechercher sur Amazon';
MLI18n::gi()->{'Amazon_Productlist_Itemsearch_SearchAsin'} = 'Entrée directe ASIN';
MLI18n::gi()->{'Amazon_Productlist_Cell_aPreparedStatus__true__title'} = 'Préparé';
MLI18n::gi()->{'Amazon_Productlist_Cell_aPreparedStatus__false__title'} = 'Défectueux';
MLI18n::gi()->{'Amazon_Productlist_History'} = 'Historique';
MLI18n::gi()->{'Amazon_Productlist_Filter_aPreparedStatus__true'} = 'Préparé avec succès';
MLI18n::gi()->{'Amazon_Productlist_Filter_aPreparedStatus__false'} = 'Mal préparé';
MLI18n::gi()->{'Amazon_Productlist_Cell_aPreparedType__manual'} = 'classer manuellement';
MLI18n::gi()->{'Amazon_Productlist_Cell_aPreparedType__auto'} = 'classer automatiquement';
MLI18n::gi()->{'Amazon_Productlist_Cell_aPreparedType__apply'} = 'Créez de nouveaux produits';
