<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ayn24_config_account_title'} = 'Login Details';
MLI18n::gi()->{'ayn24_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'ayn24_config_account_price'} = 'Price Calculation';
MLI18n::gi()->{'ayn24_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'ayn24_config_account_orderimport'} = 'Order Import';
MLI18n::gi()->{'ayn24_config_account_emailtemplate'} = 'Promotion Email Template';
MLI18n::gi()->{'ayn24_config_account_emailtemplate_sender'} = 'Example Shop';
MLI18n::gi()->{'ayn24_config_account_emailtemplate_sender_email'} = 'example@onlineshop.com';
MLI18n::gi()->{'ayn24_config_account_emailtemplate_subject'} = 'Your Order from #SHOPURL#';
MLI18n::gi()->{'ayn24_config_account_emailtemplate_content'} = 'ayn24_config_account_emailtemplate_content';
MLI18n::gi()->{'meinpaket_preimport_start_help'} = 'The date from which orders will start being imported. Please note that it is not possible to set this too far in the past, as the data only remains available on Alyn24 for a few weeks.***';
MLI18n::gi()->{'ayn24_config_account__legend__account'} = 'Login Details';
MLI18n::gi()->{'ayn24_config_account__legend__tabident'} = '';
MLI18n::gi()->{'ayn24_config_account__field__tabident__label'} = '{#i18n:ML_LABEL_TAB_IDENT#}';
MLI18n::gi()->{'ayn24_config_account__field__tabident__help'} = '{#i18n:ML_TEXT_TAB_IDENT#}';
MLI18n::gi()->{'ayn24_config_account__field__username__label'} = 'Username';
MLI18n::gi()->{'ayn24_config_account__field__password__label'} = 'Password';
MLI18n::gi()->{'ayn24_config_prepare__legend__prepare'} = 'Prepare Items';
MLI18n::gi()->{'ayn24_config_prepare__legend__shipping'} = 'ayn24_config_prepare__legend__shipping';
MLI18n::gi()->{'ayn24_config_prepare__legend__checkin'} = 'Upload Item: Presets';
MLI18n::gi()->{'ayn24_config_prepare__field__prepare.status__label'} = 'Status Filter';
MLI18n::gi()->{'ayn24_config_prepare__field__prepare.status__valuehint'} = 'Only transfer active items';
MLI18n::gi()->{'ayn24_config_prepare__field__lang__label'} = 'Item Description';
MLI18n::gi()->{'ayn24_config_prepare__field__catmatch.mpshopcats__label'} = 'Own Categories';
MLI18n::gi()->{'ayn24_config_prepare__field__catmatch.mpshopcats__valuehint'} = 'ayn24_config_prepare__field__catmatch.mpshopcats__valuehint';
MLI18n::gi()->{'ayn24_config_prepare__field__shippingcost__label'} = 'Shipping costs';
MLI18n::gi()->{'ayn24_config_prepare__field__shippingcost__help'} = 'ayn24_config_prepare__field__shippingcost__help';
MLI18n::gi()->{'ayn24_config_prepare__field__shippingcostfixed__label'} = 'ayn24_config_prepare__field__shippingcostfixed__label';
MLI18n::gi()->{'ayn24_config_prepare__field__shippingcostfixed__valuehint'} = 'ayn24_config_prepare__field__shippingcostfixed__valuehint';
MLI18n::gi()->{'ayn24_config_prepare__field__shippingcostfixed__help'} = 'ayn24_config_prepare__field__shippingcostfixed__help';
MLI18n::gi()->{'ayn24_config_prepare__field__shippingtype__label'} = 'ayn24_config_prepare__field__shippingtype__label';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.status__label'} = 'Status Filter';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.status__valuehint'} = 'Only transfer active items';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.quantity__label'} = 'Inventory Item Count';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.quantity__help'} = 'Please enter how much of the inventory should be available on the marketplace.<br/>
                        <br/>
You can change the individual item count directly under \'Upload\'. In this case it is recommended that you turn off automatic<br/>
synchronization under \'Synchronization of Inventory\' > \'Stock Sync to Marketplace\'.<br/>
                        <br/>
To avoid overselling, you can activate \'Transfer shop inventory minus value from the right field\'.
                        <br/>
<strong>Example:</strong> Setting the value at 2 gives &#8594; Shop inventory: 10 &#8594; Allyouneed inventory: 8<br/>
                        <br/>
                        <strong>Please note:</strong>If you want to set an inventory count for an item in the Marketplace to \'0\', which is already set as Inactive in the Shop, independent of the actual inventory count, please proceed as follows:<br/>
                        <ul>
                        <li>"Synchronize Inventory"> Set "Edit Shop Inventory" to "Automatic Synchronization with CronJob"</li>
                        <li>"Global Configuration" > "Product Status" > Activate setting "If product status is inactive, treat inventory count as 0"</li>
                        </ul>';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.skipean__label'} = 'ayn24_config_prepare__field__checkin.skipean__label';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.skipean__valuehint'} = 'ayn24_config_prepare__field__checkin.skipean__valuehint';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.skipean__help'} = 'ayn24_config_prepare__field__checkin.skipean__help';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.leadtimetoship__label'} = 'Lead Time in Days';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.leadtimetoship__help'} = 'ayn24_config_prepare__field__checkin.leadtimetoship__help';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.manufacturerfallback__label'} = 'Alternative Manufacturer';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.manufacturerfallback__help'} = 'ayn24_config_prepare__field__checkin.manufacturerfallback__help';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.shortdesc__label'} = 'Short description';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.shortdesc__help'} = 'ayn24_config_prepare__field__checkin.shortdesc__help';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.longdesc__label'} = 'Description';
MLI18n::gi()->{'ayn24_config_prepare__field__checkin.longdesc__help'} = 'ayn24_config_prepare__field__checkin.longdesc__help';
MLI18n::gi()->{'ayn24_config_price__legend__price'} = 'Price Calculation';
MLI18n::gi()->{'ayn24_config_price__field__price__label'} = 'Price';
MLI18n::gi()->{'ayn24_config_price__field__price__help'} = 'Please enter a price markup or markdown, either in percentage or fixed amount. Use a minus sign (-) before the amount to denote markdown.';
MLI18n::gi()->{'ayn24_config_price__field__price.addkind__label'} = '';
MLI18n::gi()->{'ayn24_config_price__field__price.factor__label'} = '';
MLI18n::gi()->{'ayn24_config_price__field__price.signal__label'} = 'Decimal Amount';
MLI18n::gi()->{'ayn24_config_price__field__price.signal__help'} = 'This textfield shows the decimal value that will appear in the item price on Ayn24.<br/><br/>
                <strong>Example:</strong> <br />
Value in textfeld: 99 <br />
                Original price: 5.58 <br />
                Final amount: 5.99 <br /><br />
This function is useful when marking the price up or down***. <br/>
Leave this field empty if you do not wish to set any decimal amount. <br/>
The format requires a maximum of 2 numbers.';
MLI18n::gi()->{'ayn24_config_price__field__priceoptions__label'} = 'ayn24_config_price__field__priceoptions__label';
MLI18n::gi()->{'ayn24_config_price__field__priceoptions__help'} = '{#i18n:configform_price_field_priceoptions_help#}';
MLI18n::gi()->{'ayn24_config_price__field__price.group__label'} = '';
MLI18n::gi()->{'ayn24_config_price__field__price.usespecialoffer__label'} = '';
MLI18n::gi()->{'ayn24_config_price__field__price.usespecialoffer__valuehint'} = 'Use special offer prices';
MLI18n::gi()->{'ayn24_config_price__field__exchangerate_update__label'} = 'Exchange Rate';
MLI18n::gi()->{'ayn24_config_price__field__exchangerate_update__valuehint'} = 'Automatically update exchange rate';
MLI18n::gi()->{'ayn24_config_price__field__exchangerate_update__help'} = '{#i18n:form_config_orderimport_exchangerate_update_help#}';
MLI18n::gi()->{'ayn24_config_price__field__exchangerate_update__alert'} = '{#i18n:form_config_orderimport_exchangerate_update_alert#}';
MLI18n::gi()->{'ayn24_config_orderimport__legend__importactive'} = 'Order Import';
MLI18n::gi()->{'ayn24_config_orderimport__legend__mwst'} = 'VAT';
MLI18n::gi()->{'ayn24_config_orderimport__legend__orderstatus'} = 'ayn24_config_orderimport__legend__orderstatus';
MLI18n::gi()->{'ayn24_config_orderimport__field__importactive__label'} = 'Activate Import';
MLI18n::gi()->{'ayn24_config_orderimport__field__importactive__help'} = 'ayn24_config_orderimport__field__importactive__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__import__label'} = '';
MLI18n::gi()->{'ayn24_config_orderimport__field__preimport.start__label'} = 'ayn24_config_orderimport__field__preimport.start__label';
MLI18n::gi()->{'ayn24_config_orderimport__field__preimport.start__hint'} = 'Start Date';
MLI18n::gi()->{'ayn24_config_orderimport__field__preimport.start__help'} = 'The date from which orders will start being imported. Please note that it is not possible to set this too far in the past, as the data only remains available on Any24 for a few weeks.***';
MLI18n::gi()->{'ayn24_config_orderimport__field__customergroup__label'} = 'Customer Group';
MLI18n::gi()->{'ayn24_config_orderimport__field__customergroup__help'} = 'The customer group that customers from new orders should be sorted into.';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderimport.shop__label'} = '{#i18n:form_config_orderimport_shop_lable#}';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderimport.shop__hint'} = '';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderimport.shop__help'} = '{#i18n:form_config_orderimport_shop_help#}';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.open__label'} = 'Order Status in Shop';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.open__help'} = 'ayn24_config_orderimport__field__orderstatus.open__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderimport.shippingmethod__label'} = 'Shipping Method';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderimport.shippingmethod__help'} = 'ayn24_config_orderimport__field__orderimport.shippingmethod__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderimport.paymentmethod__label'} = 'Payment Methods';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderimport.paymentmethod__help'} = 'ayn24_config_orderimport__field__orderimport.paymentmethod__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__mwst.fallback__label'} = 'VAT on Non-Shop*** Items';
MLI18n::gi()->{'ayn24_config_orderimport__field__mwst.fallback__hint'} = 'The tax rate to apply to non-Shop items on order imports, in %.';
MLI18n::gi()->{'ayn24_config_orderimport__field__mwst.fallback__help'} = 'ayn24_config_orderimport__field__mwst.fallback__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.sync__label'} = 'Status Synchronization';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.sync__help'} = 'ayn24_config_orderimport__field__orderstatus.sync__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.shipped__label'} = 'Confirm Shipping With';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.shipped__help'} = 'ayn24_config_orderimport__field__orderstatus.shipped__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.canceled.customerrequest__label'} = 'ayn24_config_orderimport__field__orderstatus.canceled.customerrequest__label';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.canceled.customerrequest__help'} = 'ayn24_config_orderimport__field__orderstatus.canceled.customerrequest__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.canceled.outofstock__label'} = 'ayn24_config_orderimport__field__orderstatus.canceled.outofstock__label';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.canceled.outofstock__help'} = 'ayn24_config_orderimport__field__orderstatus.canceled.outofstock__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.canceled.damagedgoods__label'} = 'ayn24_config_orderimport__field__orderstatus.canceled.damagedgoods__label';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.canceled.damagedgoods__help'} = 'ayn24_config_orderimport__field__orderstatus.canceled.damagedgoods__help';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.canceled.dealerrequest__label'} = 'ayn24_config_orderimport__field__orderstatus.canceled.dealerrequest__label';
MLI18n::gi()->{'ayn24_config_orderimport__field__orderstatus.canceled.dealerrequest__help'} = 'ayn24_config_orderimport__field__orderstatus.canceled.dealerrequest__help';
MLI18n::gi()->{'ayn24_config_sync__legend__sync'} = 'Inventory Synchronization';
MLI18n::gi()->{'ayn24_config_sync__field__stocksync.tomarketplace__label'} = 'Stock Sync to Marketplace';
MLI18n::gi()->{'ayn24_config_sync__field__stocksync.tomarketplace__help'} = 'ayn24_config_sync__field__stocksync.tomarketplace__help';
MLI18n::gi()->{'ayn24_config_sync__field__stocksync.tomarketplace__values__auto'} = '{#i18n:configform_sync_value_auto#}';
MLI18n::gi()->{'ayn24_config_sync__field__stocksync.tomarketplace__values__abs'} = 'ayn24_config_sync__field__stocksync.tomarketplace__values__abs';
MLI18n::gi()->{'ayn24_config_sync__field__stocksync.tomarketplace__values__rel'} = 'ayn24_config_sync__field__stocksync.tomarketplace__values__rel';
MLI18n::gi()->{'ayn24_config_sync__field__stocksync.tomarketplace__values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'ayn24_config_sync__field__stocksync.frommarketplace__label'} = 'Stock Sync from Marketplace';
MLI18n::gi()->{'ayn24_config_sync__field__stocksync.frommarketplace__help'} = 'ayn24_config_sync__field__stocksync.frommarketplace__help';
MLI18n::gi()->{'ayn24_config_sync__field__inventorysync.price__label'} = 'Item Price';
MLI18n::gi()->{'ayn24_config_sync__field__inventorysync.price__help'} = 'ayn24_config_sync__field__inventorysync.price__help';
MLI18n::gi()->{'ayn24_config_sync__field__inventorysync.price__values__auto'} = '{#i18n:configform_sync_value_auto#}';
MLI18n::gi()->{'ayn24_config_sync__field__inventorysync.price__values__edit'} = 'ayn24_config_sync__field__inventorysync.price__values__edit';
MLI18n::gi()->{'ayn24_config_sync__field__inventorysync.price__values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'ayn24_config_emailtemplate__legend__mail'} = 'Promotion Email Template';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.send__label'} = 'Send Email?';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.send__help'} = 'ayn24_config_emailtemplate__field__mail.send__help';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.originator.name__label'} = 'Sender Name';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.originator.adress__label'} = 'Sender Email Address';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.subject__label'} = 'Subject';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.content__label'} = 'Email Content';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.content__hint'} = 'List of available placeholders for Subject and Content:
<dl>
                    <dt>#FIRSTNAME#</dt>
                    <dd>Buyer\'s first name</dd>
                    <dt>#LASTNAME#</dt>
                    <dd>Buyer\'s last name</dd>
                    <dt>#EMAIL#</dt>
                    <dd>Buyer\'s email address</dd>
                    <dt>#PASSWORD#</dt>
                    <dd>Buyer’s password for logging in to your Shop. Only for customers that are automatically assigned passwords – otherwise the placeholder will be replaced with ‘(as known)’***.</dd>
                    <dt>#ORDERSUMMARY#</dt>
                    <dd>Summary of the purchased items. Should be written on a separate line. <br/><i>Cannot be used in the Subject!</i>
                    </dd>
                    <dt>#MARKETPLACE#</dt>
                    <dd>Marketplace Name</dd>
                    <dt>#SHOPURL#</dt>
                    <dd>Your Shop URL</dd>
                    <dt>#ORIGINATOR#</dt>
                    <dd>Sender Name</dd>
                </dl>/dd';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.copy__label'} = 'Copy to Sender';
MLI18n::gi()->{'ayn24_config_emailtemplate__field__mail.copy__help'} = 'A copy will be sent to the sender email address.';
