<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameCdiscount'} = 'sModuleNameCdiscount';
MLI18n::gi()->{'cdiscount_articles_fee'} = 'cdiscount_articles_fee';
MLI18n::gi()->{'cdiscount_articles_fee_process'} = 'cdiscount_articles_fee_process';
MLI18n::gi()->{'cdiscount_inventory_listing_lastSyncTime'} = 'cdiscount_inventory_listing_lastSyncTime';
MLI18n::gi()->{'cdiscount_inventory_listing_itemId'} = 'cdiscount_inventory_listing_itemId';
MLI18n::gi()->{'cdiscount_inventory_listing_auction_has_bids'} = 'cdiscount_inventory_listing_auction_has_bids';
MLI18n::gi()->{'cdiscount_inventory_listing_auction_has_bids_tooltip'} = 'cdiscount_inventory_listing_auction_has_bids_tooltip';
