<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'bepado_config_account_title'} = 'Login Details';
MLI18n::gi()->{'bepado_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'bepado_config_account_price'} = 'Price Calculation';
MLI18n::gi()->{'bepado_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'bepado_config_account_orderimport'} = 'Order Import';
MLI18n::gi()->{'bepado_config_account_emailtemplate'} = 'bepado_config_account_emailtemplate';
MLI18n::gi()->{'bepado_config_account_emailtemplate_sender'} = 'bepado_config_account_emailtemplate_sender';
MLI18n::gi()->{'bepado_config_account_emailtemplate_sender_email'} = 'beispiel@onlineshop.de';
MLI18n::gi()->{'bepado_config_account_emailtemplate_subject'} = 'Your Order from #SHOPURL#';
MLI18n::gi()->{'bepado_config_account_emailtemplate_content'} = 'bepado_config_account_emailtemplate_content';
MLI18n::gi()->{'bepado_config_account__legend__account'} = 'Login Details';
MLI18n::gi()->{'bepado_config_account__legend__tabident'} = '';
MLI18n::gi()->{'bepado_config_account__field__tabident__label'} = '{#i18n:ML_LABEL_TAB_IDENT#}';
MLI18n::gi()->{'bepado_config_account__field__tabident__help'} = '{#i18n:ML_TEXT_TAB_IDENT#}';
MLI18n::gi()->{'bepado_config_account__field__apikey__label'} = 'bepado_config_account__field__apikey__label';
MLI18n::gi()->{'bepado_config_account__field__apikey__hint'} = '';
MLI18n::gi()->{'bepado_config_account__field__mpusername__label'} = 'Username';
MLI18n::gi()->{'bepado_config_account__field__mppassword__label'} = 'bepado_config_account__field__mppassword__label';
MLI18n::gi()->{'bepado_config_account__field__ftpusername__label'} = 'bepado_config_account__field__ftpusername__label';
MLI18n::gi()->{'bepado_config_account__field__ftppassword__label'} = 'bepado_config_account__field__ftppassword__label';
MLI18n::gi()->{'bepado_config_account__field__shopid__label'} = 'bepado_config_account__field__shopid__label';
MLI18n::gi()->{'bepado_config_prepare__legend__prepare'} = 'Prepare Items';
MLI18n::gi()->{'bepado_config_prepare__legend__shipping'} = 'bepado_config_prepare__legend__shipping';
MLI18n::gi()->{'bepado_config_prepare__legend__upload'} = 'Upload Item: Presets';
MLI18n::gi()->{'bepado_config_prepare__field__prepare.status__label'} = 'Status Filter';
MLI18n::gi()->{'bepado_config_prepare__field__prepare.status__valuehint'} = 'Only transfer active items';
MLI18n::gi()->{'bepado_config_prepare__field__checkin.status__label'} = 'Status Filter';
MLI18n::gi()->{'bepado_config_prepare__field__checkin.status__valuehint'} = 'Only transfer active items';
MLI18n::gi()->{'bepado_config_prepare__field__lang__label'} = 'Item Description';
MLI18n::gi()->{'bepado_config_prepare__field__quantity__label'} = 'Inventory Item Count';
MLI18n::gi()->{'bepado_config_prepare__field__quantity__hint'} = '';
MLI18n::gi()->{'bepado_config_prepare__field__quantity__help'} = 'Please enter how much of the inventory should be available on the marketplace.<br/>
                        <br/>
You can change the individual item count directly under \'Upload\'. In this case it is recommended that you turn off automatic<br/>
synchronization under \'Synchronization of Inventory\' > \'Stock Sync to Marketplace\'.<br/>
                        <br/>
To avoid overselling, you can activate \'Transfer shop inventory minus value from the right field\'.
                        <br/>
<strong>Example:</strong> Setting the value at 2 gives &#8594; Shop inventory: 10 &#8594; Amazon inventory: 8<br/>
                        <br/>
                        <strong>Please note:</strong>If you want to set an inventory count for an item in the Marketplace to \'0\', which is already set as Inactive in the Shop, independent of the actual inventory count, please proceed as follows:<br/>
                        <ul>
                        <li>\'Synchronize Inventory"> Set "Edit Shop Inventory" to "Automatic Synchronization with CronJob"</li>
                        <li>"Global Configuration" > "Product Status" > Activate setting "If product status is inactive, treat inventory count as 0"</li>
                        </ul>';
MLI18n::gi()->{'bepado_config_prepare__field__shippingtime__label'} = 'bepado_config_prepare__field__shippingtime__label';
MLI18n::gi()->{'bepado_config_prepare__field__shippingcontainer__label'} = 'Shipping costs';
MLI18n::gi()->{'bepado_config_prepare__field__shippingcountry__label'} = 'bepado_config_prepare__field__shippingcountry__label';
MLI18n::gi()->{'bepado_config_prepare__field__shippingservice__label'} = 'Carrier';
MLI18n::gi()->{'bepado_config_prepare__field__shippingcost__label'} = 'Shipping costs';
MLI18n::gi()->{'bepado_config_price__legend__price'} = 'Price Calculation';
MLI18n::gi()->{'bepado_config_price__field__price__label'} = 'Price (B2C)';
MLI18n::gi()->{'bepado_config_price__field__price__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__price__help'} = 'Please enter a price markup or markdown, either in percentage or fixed amount. Use a minus sign (-) before the amount to denote markdown.';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.addkind__label'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.addkind__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.factor__label'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.factor__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.signal__label'} = 'Decimal Amount';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.signal__hint'} = 'Decimal Amount';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.signal__help'} = 'bepado_config_price__field__b2c.price.signal__help';
MLI18n::gi()->{'bepado_config_price__field__priceoptions__label'} = 'bepado_config_price__field__priceoptions__label';
MLI18n::gi()->{'bepado_config_price__field__priceoptions__help'} = '{#i18n:configform_price_field_priceoptions_help#}';
MLI18n::gi()->{'bepado_config_price__field__priceoptions__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.group__label'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.group__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.usespecialoffer__label'} = 'Use special offer prices';
MLI18n::gi()->{'bepado_config_price__field__b2c.price.usespecialoffer__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price__label'} = 'bepado_config_price__field__b2b.price__label';
MLI18n::gi()->{'bepado_config_price__field__b2b.price__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price__help'} = 'bepado_config_price__field__b2b.price__help';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.addkind__label'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.addkind__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.active__label'} = 'bepado_config_price__field__b2b.price.active__label';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.active__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.factor__label'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.factor__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.signal__label'} = 'Decimal Amount';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.signal__hint'} = 'Decimal Amount';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.signal__help'} = 'bepado_config_price__field__b2b.price.signal__help';
MLI18n::gi()->{'bepado_config_price__field__b2b.priceoptions__label'} = 'bepado_config_price__field__b2b.priceoptions__label';
MLI18n::gi()->{'bepado_config_price__field__b2b.priceoptions__help'} = '{#i18n:configform_price_field_priceoptions_help#}';
MLI18n::gi()->{'bepado_config_price__field__b2b.priceoptions__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.group__label'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.group__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.usespecialoffer__label'} = 'Use special offer prices';
MLI18n::gi()->{'bepado_config_price__field__b2b.price.usespecialoffer__hint'} = '';
MLI18n::gi()->{'bepado_config_price__field__exchangerate_update__label'} = 'Exchange Rate';
MLI18n::gi()->{'bepado_config_price__field__exchangerate_update__hint'} = 'Automatically update exchange rate';
MLI18n::gi()->{'bepado_config_price__field__exchangerate_update__help'} = '{#i18n:form_config_orderimport_exchangerate_update_help#}';
MLI18n::gi()->{'bepado_config_price__field__exchangerate_update__alert'} = '{#i18n:form_config_orderimport_exchangerate_update_alert#}';
MLI18n::gi()->{'bepado_config_sync__legend__sync'} = 'Inventory Synchronization';
MLI18n::gi()->{'bepado_config_sync__field__stocksync.tomarketplace__label'} = 'bepado_config_sync__field__stocksync.tomarketplace__label';
MLI18n::gi()->{'bepado_config_sync__field__stocksync.tomarketplace__hint'} = '';
MLI18n::gi()->{'bepado_config_sync__field__stocksync.tomarketplace__help'} = 'bepado_config_sync__field__stocksync.tomarketplace__help';
MLI18n::gi()->{'bepado_config_sync__field__stocksync.frommarketplace__label'} = 'bepado_config_sync__field__stocksync.frommarketplace__label';
MLI18n::gi()->{'bepado_config_sync__field__stocksync.frommarketplace__hint'} = '';
MLI18n::gi()->{'bepado_config_sync__field__stocksync.frommarketplace__help'} = 'bepado_config_sync__field__stocksync.frommarketplace__help';
MLI18n::gi()->{'bepado_config_sync__field__inventorysync.price__label'} = 'Item Price';
MLI18n::gi()->{'bepado_config_sync__field__inventorysync.price__hint'} = '';
MLI18n::gi()->{'bepado_config_sync__field__inventorysync.price__help'} = 'bepado_config_sync__field__inventorysync.price__help';
MLI18n::gi()->{'bepado_config_orderimport__legend__importactive'} = 'Order Import';
MLI18n::gi()->{'bepado_config_orderimport__legend__mwst'} = 'VAT';
MLI18n::gi()->{'bepado_config_orderimport__legend__orderstatus'} = 'bepado_config_orderimport__legend__orderstatus';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.sync__label'} = 'Status Synchronization';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.sync__hint'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.sync__help'} = 'bepado_config_orderimport__field__orderstatus.sync__help';
MLI18n::gi()->{'bepado_config_orderimport__field__orderimport.shop__label'} = '{#i18n:form_config_orderimport_shop_lable#}';
MLI18n::gi()->{'bepado_config_orderimport__field__orderimport.shop__hint'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__orderimport.shop__help'} = '{#i18n:form_config_orderimport_shop_help#}';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.shipped__label'} = 'bepado_config_orderimport__field__orderstatus.shipped__label';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.shipped__hint'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.shipped__help'} = 'bepado_config_orderimport__field__orderstatus.shipped__help';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.canceled__label'} = 'Cancel Order With';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.canceled__hint'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.canceled__help'} = 'bepado_config_orderimport__field__orderstatus.canceled__help';
MLI18n::gi()->{'bepado_config_orderimport__field__mwst.fallback__label'} = 'VAT on Non-Shop*** Items';
MLI18n::gi()->{'bepado_config_orderimport__field__mwst.fallback__hint'} = 'The tax rate to apply to non-Shop items on order imports, in %.';
MLI18n::gi()->{'bepado_config_orderimport__field__mwst.fallback__help'} = 'bepado_config_orderimport__field__mwst.fallback__help';
MLI18n::gi()->{'bepado_config_orderimport__field__importactive__label'} = 'Activate Import';
MLI18n::gi()->{'bepado_config_orderimport__field__importactive__hint'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__importactive__help'} = 'bepado_config_orderimport__field__importactive__help';
MLI18n::gi()->{'bepado_config_orderimport__field__import__label'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__import__hint'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__preimport.start__label'} = 'bepado_config_orderimport__field__preimport.start__label';
MLI18n::gi()->{'bepado_config_orderimport__field__preimport.start__hint'} = 'Start Date';
MLI18n::gi()->{'bepado_config_orderimport__field__preimport.start__help'} = 'The date from which orders will start being imported. Please note that it is not possible to set this too far in the past, as the data only remains available on DaWanda for a few weeks.***';
MLI18n::gi()->{'bepado_config_orderimport__field__customergroup__label'} = 'Customer Group';
MLI18n::gi()->{'bepado_config_orderimport__field__customergroup__hint'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__customergroup__help'} = 'The customer group that customers from new orders should be sorted into. ';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.open__label'} = 'Order Status in Shop';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.open__hint'} = '';
MLI18n::gi()->{'bepado_config_orderimport__field__orderstatus.open__help'} = 'bepado_config_orderimport__field__orderstatus.open__help';
MLI18n::gi()->{'bepado_config_emailtemplate__legend__mail'} = 'bepado_config_emailtemplate__legend__mail';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.send__label'} = 'bepado_config_emailtemplate__field__mail.send__label';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.send__help'} = 'bepado_config_emailtemplate__field__mail.send__help';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.originator.name__label'} = 'bepado_config_emailtemplate__field__mail.originator.name__label';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.originator.adress__label'} = 'bepado_config_emailtemplate__field__mail.originator.adress__label';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.subject__label'} = 'bepado_config_emailtemplate__field__mail.subject__label';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.content__label'} = 'bepado_config_emailtemplate__field__mail.content__label';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.content__hint'} = 'bepado_config_emailtemplate__field__mail.content__hint';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.copy__label'} = 'bepado_config_emailtemplate__field__mail.copy__label';
MLI18n::gi()->{'bepado_config_emailtemplate__field__mail.copy__help'} = 'bepado_config_emailtemplate__field__mail.copy__help';
