<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'check24_config_orderimport__field__orderimport.paymentmethod__label'} = 'check24_config_orderimport__field__orderimport.paymentmethod__label';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.paymentmethod__help'} = 'check24_config_orderimport__field__orderimport.paymentmethod__help';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.paymentmethod__hint'} = '';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.shippingmethod__label'} = 'check24_config_orderimport__field__orderimport.shippingmethod__label';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.shippingmethod__help'} = 'check24_config_orderimport__field__orderimport.shippingmethod__help';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'check24_config_orderimport__field__paymentstatus__label'} = 'Statut de paiement dans la boutique';
MLI18n::gi()->{'check24_config_orderimport__field__paymentstatus__hint'} = '';
MLI18n::gi()->{'ayn24_config_orderimport__field__customergroup__help'} = '{#i18n:global_config_orderimport_field_customergroup_help#}';
