<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Shopware_Orderimport_CountryCodeIsEmptyError'} = 'Shopware_Orderimport_CountryCodeIsEmptyError';
MLI18n::gi()->{'Shopware_Orderimport_CountryCodeDontExistsError'} = 'Shopware_Orderimport_CountryCodeDontExistsError';
MLI18n::gi()->{'Shopware_Orderimport_CurrencyCodeDontExistsError'} = 'Shopware_Orderimport_CurrencyCodeDontExistsError';
MLI18n::gi()->{'Shopware_Orderimport_CustomerGroup_Notloggedin'} = 'Ne pas créer de compte client';
MLI18n::gi()->{'global_config_orderimport_field_customergroup_help'} = 'global_config_orderimport_field_customergroup_help';
MLI18n::gi()->{'shopware_orderstatus_carrier_defaultField_value_shippingname'} = 'shopware_orderstatus_carrier_defaultField_value_shippingname';
