<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ricardo_config_producttemplate__field__template.content__label'} = 'ricardo_config_producttemplate__field__template.content__label';
MLI18n::gi()->{'ricardo_config_producttemplate__field__template.content__hint'} = 'ricardo_config_producttemplate__field__template.content__hint';
