<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ricardo_prepare_form__field__dedescription__label'} = 'ricardo_prepare_form__field__dedescription__label';
MLI18n::gi()->{'ricardo_prepare_form__field__dedescription__hint'} = 'ricardo_prepare_form__field__dedescription__hint';
MLI18n::gi()->{'ricardo_prepare_form__field__dedescription__optional__checkbox__labelNegativ'} = 'ricardo_prepare_form__field__dedescription__optional__checkbox__labelNegativ';
MLI18n::gi()->{'ricardo_prepare_form__field__frdescription__label'} = 'ricardo_prepare_form__field__frdescription__label';
MLI18n::gi()->{'ricardo_prepare_form__field__frdescription__hint'} = 'ricardo_prepare_form__field__frdescription__hint';
MLI18n::gi()->{'ricardo_prepare_form__field__frdescription__optional__checkbox__labelNegativ'} = 'ricardo_prepare_form__field__frdescription__optional__checkbox__labelNegativ';
