<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'check24_prepare_form__legend__details'} = 'check24_prepare_form__legend__details';
MLI18n::gi()->{'check24_prepare_form__legend__categories'} = 'check24_prepare_form__legend__categories';
MLI18n::gi()->{'check24_prepare_form__field__shippingtime__label'} = 'check24_prepare_form__field__shippingtime__label';
MLI18n::gi()->{'check24_prepare_form__field__shippingtime__hint'} = '';
MLI18n::gi()->{'check24_prepare_form__field__shippingcost__label'} = 'check24_prepare_form__field__shippingcost__label';
MLI18n::gi()->{'check24_prepare_form__field__shippingcost__hint'} = '';
