<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'configform_check_entries_error'} = 'configform_check_entries_error';
MLI18n::gi()->{'configform_quantity_value_error'} = 'configform_quantity_value_error';
MLI18n::gi()->{'configform_price_factor_error'} = 'configform_price_factor_error';
MLI18n::gi()->{'configform_price_signal_error'} = 'configform_price_signal_error';
MLI18n::gi()->{'configform_ust_error'} = 'configform_ust_error';
