<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sInventorySyncByService'} = 'sInventorySyncByService';
MLI18n::gi()->{'sOrderStatusSyncByService'} = 'sOrderStatusSyncByService';
MLI18n::gi()->{'sAddItemProductWithZeroQuantity'} = 'Items with 0 stock will be omitted. ';
