<?php
/**
 * File logGrid.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * It is available through the world-wide-web at this URL:
 * http://involic.com/license.txt
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to license@involic.com so
 * we can send you a copy immediately.
 *
 * eBay Listener Itegration with PrestaShop e-commerce platform.
 * Adding possibilty list PrestaShop Product dirrectly to eBay.
 *
 * @author      Involic <contacts@involic.com>
 * @copyright   Copyright (c) 2011-2015 by Involic (http://www.involic.com)
 * @license     http://involic.com/license.txt
 */
?>
<form action="<?php echo UrlHelper::getUrl("synchronization/log"); ?>" method="post">
    <div class="float-right">
        <label style="padding-top: 4px; float: none;" for="autoclearlog-setting"><?php echo L::t("Auto-clear Log");?>:</label>
        <?php
            echo HtmlHelper::dropDownList('autoclearlog-setting', $autoclearlogValue, array(
                '0' => L::t("Disabled"),
                '7' => L::t("Older that 7 days"),
                '14' => L::t("Older that 14 days"),
                '30' => L::t("Older that month")
            ), array(
                'id' => "autoclearlog-setting"
            ));
        ?>
       
        <button type="submit"
                class="button btn btn-primary btn-small"
                name="saveClearSetting">
            <i class="icon-ok icon-white"></i> <?php echo L::t("Save"); ?></button>

        <button type="submit"
                class="button btn btn-warning btn-small"
                name="clearAllLog">
            <i class="icon-trash icon-white"></i> <?php echo L::t("Clear All"); ?></button>
    </div>
</form>

<br clear="all"/>
<?php echo $grid; ?>
