<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'configform_quantity_values__stock__title'} = 'Prendre en charge le stock de la boutique';
MLI18n::gi()->{'configform_quantity_values__stock__textoption'} = '';
MLI18n::gi()->{'configform_quantity_values__stocksub__title'} = 'Prendre en charge le stock de la boutique moins la valeur du champ de droite';
MLI18n::gi()->{'configform_quantity_values__stocksub__textoption'} = '1';
MLI18n::gi()->{'configform_quantity_values__lump__title'} = 'Forfaitaire (dans le champ de droite)';
MLI18n::gi()->{'configform_quantity_values__lump__textoption'} = '1';
MLI18n::gi()->{'configform_price_addkind_values__percent'} = 'x% prix boutique majoré ou rabais';
MLI18n::gi()->{'configform_price_addkind_values__addition'} = 'x prix boutique majoré ou rabais';
MLI18n::gi()->{'configform_sync_value_auto'} = 'Synchronisation automatique via CronJob (recommandée)';
MLI18n::gi()->{'configform_sync_value_fast'} = 'configform_sync_value_fast';
MLI18n::gi()->{'configform_sync_value_no'} = 'Aucune synchronisation';
MLI18n::gi()->{'configform_sync_values__auto'} = '{#i18n:configform_sync_value_auto#}';
MLI18n::gi()->{'configform_sync_values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'configform_fast_sync_values__auto'} = '{#i18n:configform_sync_value_auto#}';
MLI18n::gi()->{'configform_fast_sync_values__auto_fast'} = '{#i18n:configform_sync_value_fast#}';
MLI18n::gi()->{'configform_fast_sync_values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'configform_stocksync_values__rel'} = 'Une commande réduit la quantité en stock du magasin (recommandée)';
MLI18n::gi()->{'configform_stocksync_values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'configform_price_field_priceoptions_help'} = 'Cette fonction permet d’indiquer à la place de marché, les différences de prix, selon vos groupes de clients. <br>
Si vous n’avez pas défini de prix pour l’un de vos groupes clients, le prix de votre boutique sera utilisé. <br>
Ainsi, par exemple, vous pouvez donner un prix différent à une quantité quelconque d’article pour un groupe particulier de clients, tout en conservant les configurations différentes ou initiales, inhérentes à ce prix pour un autre groupe de clients.<br>
<ol>
<li>Créez un groupe de clients dans votre boutique en ligne, par exemple : “clients réguliers”</li>
<li>Vous pouvez alors définir les prix souhaités pour ces groupes de clients et ainsi de suite.</li>
</ol>
';
