<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'dawanda_config_account_title'} = 'Données d\'accès';
MLI18n::gi()->{'dawanda_config_account_prepare'} = 'Préparation de l\'article';
MLI18n::gi()->{'dawanda_config_account_price'} = 'Calcul du prix';
MLI18n::gi()->{'dawanda_config_account_sync'} = 'Synchronisation';
MLI18n::gi()->{'dawanda_config_account_orderimport'} = 'Importation des commandes';
MLI18n::gi()->{'dawanda_config_account__legend__account'} = 'Données d\'accès';
MLI18n::gi()->{'dawanda_config_account__legend__tabident'} = '';
MLI18n::gi()->{'dawanda_config_account__field__tabident__label'} = '{#i18n:ML_LABEL_TAB_IDENT#}';
MLI18n::gi()->{'dawanda_config_account__field__tabident__hint'} = '';
MLI18n::gi()->{'dawanda_config_account__field__tabident__help'} = '{#i18n:ML_TEXT_TAB_IDENT#}';
MLI18n::gi()->{'dawanda_config_account__field__mpusername__label'} = 'Nom du membre';
MLI18n::gi()->{'dawanda_config_account__field__mpusername__hint'} = '';
MLI18n::gi()->{'dawanda_config_account__field__mppassword__label'} = 'Mot de passe';
MLI18n::gi()->{'dawanda_config_account__field__mppassword__hint'} = '';
MLI18n::gi()->{'dawanda_config_account__field__apikey__label'} = 'Clé&#8209;pour l\'application';
MLI18n::gi()->{'dawanda_config_account__field__apikey__hint'} = '';
MLI18n::gi()->{'dawanda_config_prepare__legend__prepare'} = 'Préparation de l\'article';
MLI18n::gi()->{'dawanda_config_prepare__legend__upload'} = 'Téléchargez l\'article: les paramétrages par défaut ';
MLI18n::gi()->{'dawanda_config_prepare__field__prepare.status__label'} = 'Statut ';
MLI18n::gi()->{'dawanda_config_prepare__field__prepare.status__hint'} = 'Ne prendre que l\'article actif.';
MLI18n::gi()->{'dawanda_config_prepare__field__producttype__label'} = 'Type de produit';
MLI18n::gi()->{'dawanda_config_prepare__field__producttype__hint'} = '';
MLI18n::gi()->{'dawanda_config_prepare__field__returnpolicy__label'} = 'Droit de révocation';
MLI18n::gi()->{'dawanda_config_prepare__field__returnpolicy__hint'} = '';
MLI18n::gi()->{'dawanda_config_prepare__field__checkin.status__label'} = 'Statut';
MLI18n::gi()->{'dawanda_config_prepare__field__checkin.status__hint'} = 'Ne prendre que l\'article actif';
MLI18n::gi()->{'dawanda_config_prepare__field__langs__label'} = 'Description de l\'article';
MLI18n::gi()->{'dawanda_config_prepare__field__langs__hint'} = '';
MLI18n::gi()->{'dawanda_config_prepare__field__langs__matching__titlesrc'} = 'Langue de DaWanda';
MLI18n::gi()->{'dawanda_config_prepare__field__langs__matching__titledst'} = 'Langue de la boutique';
MLI18n::gi()->{'dawanda_config_prepare__field__quantity__label'} = 'Nombre d\'unités en stock';
MLI18n::gi()->{'dawanda_config_prepare__field__quantity__hint'} = '';
MLI18n::gi()->{'dawanda_config_prepare__field__quantity__help'} = '    Spécifiez ici quelle quantité de cet article doit être disponible en stock sur la place de marché.<br/>
                <br/>
				Vous pouvez changer le nombre directement sous "<i>Télécharger</i>", changer individuellement - dans ce cas ci, il est recommandé<br/> de désactiver la synchronisation automatique, sous <br/>"<i>Synchronisation des inventaires</i>" > "<i>changement dans le stock" en  boutique.</i>".<br/>
				<br/>
				Pour éviter les excès de ventes, vous pouvez activer la valeur<br/>
				"<i>reprendre le stock de l\'inventaire en boutique, moins la valeur du champ de droite".<br/>
				<br/>
				<strong>Exemple :</strong> Mettez comme valeur "<i>2</i>". Donne &#8594; Stock en boutique: 10 &#8594; Stock sur DaWanda: 8<br/>
				<br/>
				<strong>Remarque :</strong>Si vous souhaitez gérer un article, défini comme étant "inactif" dans la boutique, quelle que soit la quantité réelle,<br/>
 également comme quantité "<i>0</i>" sur la place de marché, procédez comme suit.:<br/>
				<ul>
                    <li>"<i>Synchronisation des Inventaires</i>" > "<i>Changement dans le stock en boutique</i>" sous l\'onglet "<i>Synchronisation automatique via CronJob"</i></li>
                    <li>"<i>Configuration globale " > "<i>Status du produit</i>" > "<i>et activez "Si le statut du produit est placé comme étant inactif, le niveau des stocks sera alors  enregistré comme quantité 0 "</i></li>
				</ul>';
MLI18n::gi()->{'dawanda_config_prepare__field__checkin.leadtimetoship__label'} = 'Expédition';
MLI18n::gi()->{'dawanda_config_prepare__field__checkin.leadtimetoship__hint'} = '';
MLI18n::gi()->{'dawanda_config_prepare__field__checkin.manufacturerfallback__label'} = 'D\'autres fabricants';
MLI18n::gi()->{'dawanda_config_prepare__field__checkin.manufacturerfallback__hint'} = '';
MLI18n::gi()->{'dawanda_config_prepare__field__checkin.manufacturerfallback__help'} = 'Si un produit n\'a pas été enregistré par un fabricant, le fabricant spécifié ici sera alors utilisé.';
MLI18n::gi()->{'dawanda_config_prepare__field__imagesize__label'} = '{#i18n:form_config_orderimport_imagesize_lable#}';
MLI18n::gi()->{'dawanda_config_prepare__field__imagesize__help'} = '{#i18n:form_config_orderimport_imagesize_help#}';
MLI18n::gi()->{'dawanda_config_prepare__field__imagesize__hint'} = '{#i18n:form_config_orderimport_imagesize_hint#}';
MLI18n::gi()->{'dawanda_config_price__legend__price'} = 'Calcul du prix';
MLI18n::gi()->{'dawanda_config_price__field__price__label'} = 'Prix';
MLI18n::gi()->{'dawanda_config_price__field__price__hint'} = '';
MLI18n::gi()->{'dawanda_config_price__field__price__help'} = 'Veuillez donner un pourcentage, un prix majoré, un rabais ou un prix fixe prédéfini. Le rabais commence par un moins devant le chiffre.';
MLI18n::gi()->{'dawanda_config_price__field__price.addkind__label'} = '';
MLI18n::gi()->{'dawanda_config_price__field__price.addkind__hint'} = '';
MLI18n::gi()->{'dawanda_config_price__field__price.factor__label'} = '';
MLI18n::gi()->{'dawanda_config_price__field__price.factor__hint'} = '';
MLI18n::gi()->{'dawanda_config_price__field__price.signal__label'} = 'Séparateur décimal';
MLI18n::gi()->{'dawanda_config_price__field__price.signal__hint'} = 'Séparateur décimal';
MLI18n::gi()->{'dawanda_config_price__field__price.signal__help'} = 'Cette zone de texte sera utilisée dans les transmissions de données vers Dawanda, (prix après la virgule).<br/><br/>

<strong>Par exemple :</strong> <br /> 
Valeur dans la zone de texte: 99 <br /> 
Prix d\'origine: 5.58 <br /> 
Prix final: 5.99 <br /><br />

La fonction aide en particulier, pour les majorations ou les rabais en pourcentage sur les prix.
Laissez le champ vide si vous souhaitez ne pas transmettre de prix avec une virgule.
Le format d\'entrée est un chiffre entier avec max. 2 chiffres.';
MLI18n::gi()->{'dawanda_config_price__field__priceoptions__label'} = 'Options de tarification';
MLI18n::gi()->{'dawanda_config_price__field__priceoptions__help'} = '{#i18n:configform_price_field_priceoptions_help#}';
MLI18n::gi()->{'dawanda_config_price__field__priceoptions__hint'} = '';
MLI18n::gi()->{'dawanda_config_price__field__price.group__label'} = '';
MLI18n::gi()->{'dawanda_config_price__field__price.group__hint'} = '';
MLI18n::gi()->{'dawanda_config_price__field__price.usespecialoffer__label'} = 'Utilisez également des tarifs spéciaux';
MLI18n::gi()->{'dawanda_config_price__field__price.usespecialoffer__hint'} = '';
MLI18n::gi()->{'dawanda_config_price__field__exchangerate_update__label'} = 'Taux de change';
MLI18n::gi()->{'dawanda_config_price__field__exchangerate_update__hint'} = 'Mise à jour automatique des Taux de change';
MLI18n::gi()->{'dawanda_config_price__field__exchangerate_update__help'} = 'La fonction est activée: Si la monnaie de la boutique est différente de la monnaie sur la place de marché, le prix lors du règlement sera alors automatiquement calculé selon le taux de change actuel de la monnaie sur Yahoo Finances.<br /><br />

AVERTISSEMENT : RedGecko GmbH n\'assume aucune responsabilité pour l\'exactitude du taux de change. Vérifiez, s\'il vous plaît, et contrôlez la transmission de ces valeurs dans votre compte Dawanda.';
MLI18n::gi()->{'dawanda_config_price__field__exchangerate_update__alert'} = '{#i18n:form_config_orderimport_exchangerate_update_alert#}';
MLI18n::gi()->{'dawanda_config_sync__legend__sync'} = 'Synchronisation des inventaires';
MLI18n::gi()->{'dawanda_config_sync__field__stocksync.tomarketplace__label'} = 'Changement dans le stock de la boutique';
MLI18n::gi()->{'dawanda_config_sync__field__stocksync.tomarketplace__hint'} = '';
MLI18n::gi()->{'dawanda_config_sync__field__stocksync.tomarketplace__help'} = '                   <p>
La fonction "synchronisation automatique" compare toutes les 4 heures (à partir de 0:00 dans la nuit) l\'état actuel des stocks sur Dawanda et les stocks en boutique.(selon la configuration si nécessaire avec déduction)<br>
Ainsi les valeurs du statut venant de la base de données sont vérifiées et appliquées même si des changements, par exemple, dans la gestion des marchandises, sont seulement réalisés dans la base de données.<br><br>
Un réglage manuel peut être déclenché, en cliquant sur la touche de fonction correspondante dans l\'en-tête de magnalister (à gauche).<br><br>
En outre, vous pouvez utiliser la synchronisation des statuts de commande (dès le "tarif Flat" - ou au maximum toutes les 15 minutes) en déclenchant les importations via CronJob, et en cliquant sur le lien suivant vers votre boutique:<br> <i>{#setting:sSyncInventoryUrl#}</i><br>
Les importations déclenchées via CronJob par des clients qui ne sont pas au "tarif Flat" ou qui ne respectent pas le délai de 15 minutes, seront bloqués.<br><br>
<b>Remarque :</b> Les paramètres de "configuration" de &rarr; "le processus de réglage" &rarr; "Le nombre d\'unités en stock" seront pris en compte.
				</p>
';
MLI18n::gi()->{'dawanda_config_sync__field__stocksync.frommarketplace__label'} = 'Changement dans le stock DaWanda';
MLI18n::gi()->{'dawanda_config_sync__field__stocksync.frommarketplace__hint'} = '';
MLI18n::gi()->{'dawanda_config_sync__field__stocksync.frommarketplace__help'} = 'Si par exemple un article a été acheté 3 fois chez DaWanda, le stock en boutique va se réduire de 3 unités.<br /><br />
                <strong>Important:</strong> Cette fonction s\'exécute uniquement si vous avez activé l\'importation de commande!
';
MLI18n::gi()->{'dawanda_config_sync__field__inventorysync.price__label'} = 'Prix de l\'article';
MLI18n::gi()->{'dawanda_config_sync__field__inventorysync.price__hint'} = '';
MLI18n::gi()->{'dawanda_config_sync__field__inventorysync.price__help'} = '       <p>
                    la fonction "synchronisation automatique" compare toutes les 4 heures (à partir de 0:00 dans la nuit) l\'état actuel des prix sur DaWanda et les prix de votre boutique.<br>
                    Ainsi les valeurs venant de la base de données sont vérifiées et appliquées même si des changements, par exemple, dans la gestion des marchandises, sont seulement réalisés dans la base de données.
                    <br><br>
                    <b>Remarque :</b> Les réglages sous l\'onglet "Configuration" &rarr; "Calcul du prix" seront pris en compte.
                </p>';
MLI18n::gi()->{'dawanda_config_orderimport__legend__importactive'} = 'Importation des commandes';
MLI18n::gi()->{'dawanda_config_orderimport__legend__mwst'} = 'Taxe sur la valeur';
MLI18n::gi()->{'dawanda_config_orderimport__legend__orderstatus'} = 'Synchronisation du statut de la commande de la boutique DaWanda';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.sync__label'} = 'Statut de la synchronisation';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.sync__hint'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.sync__help'} = '<dl>
                    <dt>Synchronisation automatique via CronJob (recommandée)</dt>
                    <dd>
                        La synchronisation automatique de la fonction via CronJob transmet toutes les 2 heures (à partir de 0:00 dans la nuit) l\'état actuel des commandes sur DaWanda.<br/>
                        Ainsi les valeurs venant de la base de données sont vérifiées et appliquées même si des changements, par exemple, dans la gestion des marchandises, sont seulement réalisés dans la base de données.<br/><br/>
                       Un réglage manuel peut être déclenché, en traitant directement une commande de votre boutique en ligne. Vous réglez alors le statut correspondant de la commande et cliquez sur Actualiser.<br/>
                       Vous pouvez aussi cliquer sur la touche de fonction correspondante dans l\'en-tête de magnalister (à gauche), pour transmettre immédiatement le statut correspondant.<br/><br/>
                        En outre, vous pouvez utiliser la synchronisation des statuts de commande (dès le "tarif Flat" - ou au maximum toutes les 15 minutes) en déclenchant les importations via CronJob, et en cliquant sur le lien suivant vers votre boutique:<br/><br/>
                        <i>{#setting:sSyncOrderStatusUrl#}</i><br/><br/>
                        Les importations déclenchées via CronJob par des clients qui ne sont pas au "tarif Flat" ou qui ne respectent pas le délai de 15 minutes, seront bloqués.
                    </dd>
                </dl>';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.shipped__label'} = 'Confirmez l\'expédition avec';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.shipped__hint'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.shipped__help'} = 'Modifiez ici le statut de la boutique, qui doit "confirmer la livraison" automatiquement sur DaWanda.';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderimport.shop__label'} = '{#i18n:form_config_orderimport_shop_lable#}';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderimport.shop__hint'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderimport.shop__help'} = '{#i18n:form_config_orderimport_shop_help#}';
MLI18n::gi()->{'dawanda_config_orderimport__field__mwst.fallback__label'} = 'TVA pour les articles ne venant pas de la boutique';
MLI18n::gi()->{'dawanda_config_orderimport__field__mwst.fallback__hint'} = 'Le taux d\'imposition lors d\'une importation de commandes d\'articles ne venant pas de la boutique sera alors calculé en %.';
MLI18n::gi()->{'dawanda_config_orderimport__field__mwst.fallback__help'} = '       Si l\'article n\'a pas été enregistré sur magnalister, la TVA ne peut pas être déterminée.<br />
                Comme solution alternative, la valeur sera fixée en pourcentage pour chaque produit enregistré, dont la TVA n\'est pas connue par DaWanda, lors de l\'importation.
';
MLI18n::gi()->{'dawanda_config_orderimport__field__importactive__label'} = 'Activez l\'importation';
MLI18n::gi()->{'dawanda_config_orderimport__field__importactive__hint'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__importactive__help'} = '            Est-ce que les importations de commandes doivent être effectuées à partir de la place de marché?.<br><br>Si la fonction est activée, les commandes seront automatiquement importées toutes les heures.<br><br>            
                               Vous pouvez régler vous-même la durée de l\'importation automatique des commandes en cliquant sur <br> 
				"magnalister Admin" &rarr; "configuration globale" &rarr; "Importation des commandes".<br><br>
				Vous pouvez déclencher une importation manuellement, en cliquant sur la touche de fonction correspondante dans l\'en-tête de magnalister (à gauche).<br><br>
				En outre, vous pouvez également déclencher l\'importation des commandes (dès le "tarif Flat" - au maximum toutes les 15 minutes) Via CronJob, en suivant le lien suivant vers votre boutique: <br>
    			<i>{#setting:sImportOrdersUrl#}</i><br><br>
    			Les importations de commandes effectuées via CronJob par des clients, qui ne sont pas en "Flat tarif", ou qui ne respectent pas les 15 minutes de délai, seront bloqués.';
MLI18n::gi()->{'dawanda_config_orderimport__field__import__label'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__import__hint'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__preimport.start__label'} = 'Premier lancement de l\'importation';
MLI18n::gi()->{'dawanda_config_orderimport__field__preimport.start__hint'} = 'Moment du lancement de l\'importation';
MLI18n::gi()->{'dawanda_config_orderimport__field__preimport.start__help'} = 'Point de départ, dès que la première importation de commandes est effectuée. Veuillez noter que celle-ci ne peut être éloignée dans le temps, car les données de DaWanda ne peuvent pas dépasser plus de quelques semaines au maximum.

';
MLI18n::gi()->{'dawanda_config_orderimport__field__customergroup__label'} = 'Groupes clients';
MLI18n::gi()->{'dawanda_config_orderimport__field__customergroup__hint'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__customergroup__help'} = 'Les groupes de clients, pourront s\'associer pour passer de nouvelles commandes.

';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.open__label'} = 'Statut de la commande boutique';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.open__hint'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__orderstatus.open__help'} = '                Le statut de la commande est défini, pour qu\'une importation de commandes venant de DaWanda soit automatiquement envoyée vers votre boutique.<br/>
                Si vous utilisez un système interne d\'avertissements, il est recommandé, de définir le statut de la commande comme étant "payé" (Configuration → Statut de la commande).';
MLI18n::gi()->{'dawanda_config_orderimport__field__customersync__label'} = 'Les clients fidèles';
MLI18n::gi()->{'dawanda_config_orderimport__field__customersync__hint'} = '';
MLI18n::gi()->{'dawanda_config_orderimport__field__customersync__help'} = '                DaWanda génère à chaque commande une nouvelle adresse E-Mail de l\'acheteur (transfert) pouvant venir de la commande précédente.<br />
                 <br />
                Dans le menu déroulant, choisissez si vous voulez mettre à jour les coordonnées et autres données de base comme l\'E-Mail, pour le retour des clients fidèles et donc reprendre les données ou si vous souhaitez enregistrer de nouveau entièrement le client.';
MLI18n::gi()->{'dawanda_config_orderimport__field__customersync__values__1'} = 'Mise à jour des données clients';
MLI18n::gi()->{'dawanda_config_orderimport__field__customersync__values__0'} = 'Créez de nouvelles données clients';
