<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Dawanda_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'Dawanda_CheckinForm__Amount'} = 'Nombre';
MLI18n::gi()->{'Dawanda_CheckinForm__ShippingTime'} = 'Livraison (jours)';
MLI18n::gi()->{'Dawanda_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'Dawanda_CheckinForm__SuggestedPrice'} = 'Calculé (de la configuration)';
MLI18n::gi()->{'Dawanda_CheckinForm__HitPrice'} = 'Hit de prix';
MLI18n::gi()->{'Dawanda_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'Dawanda_CheckinForm__SuggestedAmount'} = 'Calculé (de la configuration)';
