<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Dawanda_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparé avec succès';
MLI18n::gi()->{'Dawanda_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Erreur de préparation';
MLI18n::gi()->{'Dawanda_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non contrôlée';
MLI18n::gi()->{'Dawanda_Productlist_Filter_aPreparedStatus__OK'} = 'Préparé avec succès';
MLI18n::gi()->{'Dawanda_Productlist_Filter_aPreparedStatus__ERROR'} = 'Erreur de préparation';
MLI18n::gi()->{'Dawanda_Productlist_Filter_aPreparedStatus__OPEN'} = 'Préparation non contrôlée';
MLI18n::gi()->{'Dawanda_Productlist_Cell_aPreparedType__Chinese'} = 'Augmentation des enchères (chinois)';
MLI18n::gi()->{'Dawanda_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Prix fixe';
MLI18n::gi()->{'Dawanda_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Prix fixe (magasin DaWanda)';
MLI18n::gi()->{'Dawanda_Productlist_Header_sPreparedType'} = 'Type de vente aux enchères';
