<?php
/**
 * File edit.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * It is available through the world-wide-web at this URL:
 * http://involic.com/license.txt
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to license@involic.com so
 * we can send you a copy immediately.
 *
 * eBay Listener Itegration with PrestaShop e-commerce platform.
 * Adding possibilty list PrestaShop Product dirrectly to eBay.
 *
 * @author      Involic <contacts@involic.com>
 * @copyright   Copyright (c) 2011-2015 by Involic (http://www.involic.com)
 * @license     http://involic.com/license.txt
 */
?>

<?php echo $gridHtml; ?>
<br/>
<div id="sellingSellection" style="display:none">
    <?php echo HtmlHelper::blockStart(""); ?>
    <?php
        $sm = new Selling_ListModel();
        echo HtmlHelper::dropDownList('sellingSelection', '', $sm->getSelect()->getItems(), array(
            'id' => 'sellingSelection'
        ));
    ?>
    <button type="button"
            onclick="confirmSellingSelection()"
            class="button btn btn-primary btn-small"
            ><?php echo L::t("Confirm"); ?></button>
    <?php echo HtmlHelper::blockEnd(); ?>
</div>
<script type="text/javascript">
    function showSellingSelection() {
        jQuery("#sellingSellection").toggle();
        return false;
    }

function confirmSellingSelection()
{
    jQuery("#hidden_moveTo").val(jQuery("#sellingSelection").val())
    jQuery("#sellings_products").submit();
}

</script>