<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'MercadoLivre_CheckinForm__Price'} = 'Preço';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Amount'} = 'Quantidade';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShippingTime'} = 'Envio (dias)';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShopPrice'} = 'Loja';
MLI18n::gi()->{'MercadoLivre_CheckinForm__SuggestedPrice'} = 'Calculado (de acordo com a configuração)';
MLI18n::gi()->{'MercadoLivre_CheckinForm__HitPrice'} = 'Preço alvo';
MLI18n::gi()->{'MercadoLivre_CheckinForm__AvailibleAmount'} = 'Disponível';
MLI18n::gi()->{'MercadoLivre_CheckinForm__SuggestedAmount'} = 'Calculado (de acordo com a configuração)';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Condition'} = 'Condição do item';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ListingType'} = 'Preço de lista';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Conditions__new'} = 'Novo';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Conditions__not_specified'} = 'Não especificado';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Conditions__used'} = 'Usado';
MLI18n::gi()->{'MercadoLivre_CheckinForm__BuyingMode'} = 'Modo de compra';
MLI18n::gi()->{'MercadoLivre_CheckinForm__BuyingModes__buy_it_now'} = 'Compre agora';
MLI18n::gi()->{'MercadoLivre_CheckinForm__BuyingModes__auction'} = 'Leilão';
MLI18n::gi()->{'MercadoLivre_CheckinForm__BuyingModes__classified'} = 'Classificado';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShippingMode'} = 'Método de envio';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShippingModes__custom'} = 'Personalizado';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShippingModes__not_specified'} = 'não especificado';
