<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'mercadolivre_prepare_form__legend__details'} = 'Detalhes do produto';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__categories'} = 'Categorias do MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatching__0'} = 'Atributo no MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatching__1'} = 'Atributo da minha loja virtual';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__configmatching'} = 'Configuração no MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepare_form__field__categories__label'} = 'Categorias do MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepare_form__field__primarycategory__label'} = '1. Categoria MercadoLivre:';
MLI18n::gi()->{'mercadolivre_prepare_form__field__currency__label'} = 'Moeda';
MLI18n::gi()->{'mercadolivre_prepare_form__field__itemcondition__label'} = 'Condição do Item';
MLI18n::gi()->{'mercadolivre_prepare_form__field__listingtype__label'} = 'Tipo de listagem';
MLI18n::gi()->{'mercadolivre_prepare_form__field__buyingmode__label'} = 'Modo de compra';
MLI18n::gi()->{'mercadolivre_prepare_form__field__shippingmode__label'} = 'Método de envio';
MLI18n::gi()->{'mercadolivre_prepare_form__field__webshopattribute__label'} = 'Atributo da loja virtual';
MLI18n::gi()->{'mercadolivre_prepare_form__field__attributematching__matching__titlesrc'} = 'Valor na loja';
MLI18n::gi()->{'mercadolivre_prepare_form__field__attributematching__matching__titledst'} = 'Valor no MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepareform_max_length_part1'} = 'Comprimento máximo de';
MLI18n::gi()->{'mercadolivre_prepareform_max_length_part2'} = 'atributo é';
MLI18n::gi()->{'mercadolivre_prepareform_reqired_fieds'} = '<p><b>Observação:</b> Os campos marcados com <span class="bull">•</span> são obrigatórios e precisam ser preenchidos.</p>';
