<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Mercadolivre_Productlist_Cell_aPreparedStatus__OK__title'} = 'Preparado com sucesso';
MLI18n::gi()->{'Mercadolivre_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Preparados com erro';
MLI18n::gi()->{'Mercadolivre_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Preparados sem verificação';
MLI18n::gi()->{'Mercadolivre_Productlist_Filter_aPreparedStatus__OK'} = 'Preparado com sucesso';
MLI18n::gi()->{'Mercadolivre_Productlist_Filter_aPreparedStatus__ERROR'} = 'Preparados com erro';
MLI18n::gi()->{'Mercadolivre_Productlist_Filter_aPreparedStatus__OPEN'} = 'Preparados sem verificação';
MLI18n::gi()->{'Mercadolivre_Productlist_Cell_aPreparedType__Chinese'} = 'Leilão (chinês)';
MLI18n::gi()->{'Mercadolivre_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Preço fixo';
MLI18n::gi()->{'Mercadolivre_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Preço fixo (no MercadoLivre)';
MLI18n::gi()->{'Mercadolivre_Productlist_Header_sPreparedType'} = 'Tipo de Venda';
