<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'fyndiq_config_orderimport__field__paymentstatus__label'} = 'fyndiq_config_orderimport__field__paymentstatus__label';
MLI18n::gi()->{'fyndiq_config_orderimport__field__paymentstatus__hint'} = '';
MLI18n::gi()->{'fyndiq_config_orderimport__field__customergroup__help'} = '{#i18n:global_config_orderimport_field_customergroup_help#}';
