<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'bepado_prepare_form__legend__categories'} = 'bepado_prepare_form__legend__categories';
MLI18n::gi()->{'bepado_prepare_form__legend__shipping'} = 'bepado_prepare_form__legend__shipping';
MLI18n::gi()->{'bepado_prepare_form__legend__details'} = 'bepado_prepare_form__legend__details';
MLI18n::gi()->{'bepado_prepare_form__field__b2b_price_active__label'} = 'bepado_prepare_form__field__b2b_price_active__label';
MLI18n::gi()->{'bepado_prepare_form__field__b2b_price_active__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__categories__label'} = 'bepado_prepare_form__field__categories__label';
MLI18n::gi()->{'bepado_prepare_form__field__categories__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__category__label'} = 'bepado_prepare_form__field__category__label';
MLI18n::gi()->{'bepado_prepare_form__field__category__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__shippingtime__label'} = 'bepado_prepare_form__field__shippingtime__label';
MLI18n::gi()->{'bepado_prepare_form__field__shippingtime__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcontainer__label'} = 'bepado_prepare_form__field__shippingcontainer__label';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcountry__label'} = 'bepado_prepare_form__field__shippingcountry__label';
MLI18n::gi()->{'bepado_prepare_form__field__shippingservice__label'} = 'bepado_prepare_form__field__shippingservice__label';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcost__label'} = 'bepado_prepare_form__field__shippingcost__label';
