<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_ERROR_GLOBAL'} = 'An error occured.
Please try again later. If the error does not disappear within the next few hours,
please contact us: {#i18n:MAGNA_SUPPORT_URL#}.';
