<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_config_producttemplate__field__template.name__label'} = 'ebay_config_producttemplate__field__template.name__label';
MLI18n::gi()->{'ebay_config_producttemplate__field__template.name__help'} = 'ebay(19519) ML_CONFIG_FIELD_EMPTY_OR_MISSING';
