<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_prepare_form__field__title__label'} = 'ebay_prepare_form__field__title__label';
MLI18n::gi()->{'ebay_prepare_form__field__title__hint'} = 'Titre maxi. 80 caratères';
MLI18n::gi()->{'ebay_prepare_form__field__title__optional__checkbox__labelNegativ'} = 'Toujours reprendre les noms d\'articles de la boutique.';
